/**
 * GENERATED FILE — do not edit by hand.
 * Run: node scripts/generate-approved-pages.mjs
 *
 * Byte-identical reproduction of the approved reference document:
 *   ui-reference/my_mcp_tools_loading_experience_v2_1368x753.html
 *   bytes  : 589330
 *   sha256 : 115d44492592a8b5543781b507ddeea1ac9e55d6aa8b534cca5573fc59339306
 *
 * Any edit here breaks the approved-visual contract enforced by
 * test/approved-pages-byte-identity.test.ts.
 */
import { DW_AUTH_LOGO_B64 } from "./assets";

export const LOADING_SHA256 = "115d44492592a8b5543781b507ddeea1ac9e55d6aa8b534cca5573fc59339306";

export const LOADING_HTML: string =
  [
  "<!doctype html>",
  "<html lang=\"en\">",
  "<head>",
  "<meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">",
  "<title>DreamWorker \u2014 Loading Refined 1368\u00d7753</title>",
  "<!-- Display-only. No network requests, external URLs, or redirects. Future hook: DreamWorkerLoadingUI. -->",
  "<style>",
  ":root{",
  "  --ink:#07123f;--muted:#6075b0;--muted2:#8193c1;--line:#d9e5f3;--line2:#cbd9ee;",
  "  --blue:#2b79ef;--cyan:#25bfe7;--teal:#129fa9;--mint:#3bd1b8;--green:#12b97a;",
  "}",
  "*{box-sizing:border-box}",
  "html,body{margin:0;width:100%;height:100%;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,\"Segoe UI\",Arial,sans-serif;color:var(--ink);background:#eaf2f8}",
  "body{overflow:hidden} button,input{font:inherit} a{text-decoration:none;color:inherit}",
  ".viewport{width:100vw;height:100vh;display:grid;place-items:center;background:linear-gradient(180deg,#f4f9fd,#eaf2f8)}",
  ".stage{",
  "  position:relative;width:1368px;height:753px;overflow:hidden;transform-origin:center;",
  "  background:",
  "    radial-gradient(520px 300px at 58% 21%,rgba(104,205,237,.10),transparent 70%),",
  "    radial-gradient(480px 240px at 79% 12%,rgba(95,206,220,.055),transparent 70%),",
  "    linear-gradient(180deg,#fbfdff 0%,#f6faff 66%,#fafdff 100%);",
  "  box-shadow:0 24px 70px rgba(24,55,92,.13)",
  "}",
  "@media(max-width:1368px),(max-height:753px){.stage{transform:scale(min(calc(100vw / 1368),calc(100vh / 753)))}}",
  ".logo-lockup-img{display:block;object-fit:contain;image-rendering:auto}",
  ".top-actions{position:absolute;right:48px;top:28px;display:flex;gap:14px;z-index:9}",
  ".icon-btn,.lang-btn{",
  "  height:38px;border:1px solid rgba(201,220,239,.70);border-radius:10px;background:rgba(255,255,255,.34);",
  "  color:#193c7e;display:flex;align-items:center;justify-content:center;",
  "  box-shadow:inset 0 1px 0 rgba(255,255,255,.86),0 3px 10px rgba(60,98,142,.025)",
  "}",
  ".icon-btn{width:38px}.lang-btn{width:76px;gap:9px;font-size:13px}",
  ".icon-btn svg,.lang-btn svg{width:19px;height:19px;stroke:currentColor;fill:none;stroke-width:1.65;stroke-linecap:round;stroke-linejoin:round}",
  ".wave-field{position:absolute;left:0;right:0;bottom:38px;width:100%;height:303px;z-index:0;pointer-events:none}",
  ".footer{position:absolute;left:48px;right:48px;bottom:22px;z-index:7;display:flex;align-items:center;color:#687db7;font-size:9px}",
  ".footer .fbrand{color:#0e63e8;font-weight:700}.footer .sep{margin:0 11px;color:#a1b2d2}.footer .right{margin-left:auto;display:flex;gap:24px}.footer a{color:#6277b0}",
  "",
  ".stage{background:radial-gradient(560px 370px at 50% 28%,rgba(78,201,226,.10),transparent 68%),linear-gradient(180deg,#fbfdff 0%,#f4faff 70%,#fafdff 100%)}",
  ".loading-brand{position:absolute;left:0;right:0;top:64px;height:150px;z-index:6;display:flex;align-items:center;justify-content:center}",
  ".loading-brand .logo-lockup-img{width:254px;height:auto}",
  ".spinner-wrap{position:absolute;left:50%;top:222px;transform:translateX(-50%);width:146px;height:146px;z-index:7}",
  ".spinner-halo{position:absolute;inset:8px;border-radius:50%;background:radial-gradient(circle,rgba(62,194,220,.12),rgba(83,174,232,.045) 50%,transparent 72%);filter:blur(10px)}",
  ".spinner{position:absolute;inset:0;border-radius:50%;background:conic-gradient(from -28deg,rgba(62,222,188,1) 0deg,rgba(104,241,205,1) 54deg,rgba(99,224,216,.22) 104deg,rgba(255,255,255,.12) 160deg,rgba(77,170,255,.18) 222deg,rgba(62,166,248,1) 286deg,rgba(57,214,223,.75) 334deg,rgba(62,222,188,1) 360deg);-webkit-mask:radial-gradient(farthest-side,transparent calc(100% - 8px),#000 0);mask:radial-gradient(farthest-side,transparent calc(100% - 8px),#000 0);filter:drop-shadow(0 8px 14px rgba(47,164,214,.16));animation:spin 2.3s linear infinite}",
  "@keyframes spin{to{transform:rotate(360deg)}}",
  ".loading-copy{position:absolute;left:0;right:0;top:390px;text-align:center;z-index:6}.loading-copy h1{margin:0;font-size:25px;letter-spacing:-.65px;color:#08123f;font-weight:790}.loading-copy p{margin:8px 0 0;font-size:13px;color:#6479b6}",
  ".progress{position:absolute;left:250px;right:250px;top:486px;height:74px;z-index:6}.progress-line{position:absolute;left:72px;right:72px;top:10px;height:2px;background:#ccd9ed}.progress-fill{position:absolute;left:72px;top:10px;height:2px;width:166px;background:linear-gradient(90deg,#3ed9bd,#4fb7ea);transition:width .45s ease}",
  ".steps{position:absolute;inset:0;display:grid;grid-template-columns:repeat(4,1fr)}.step{position:relative;text-align:center;color:#6478b5;font-size:10px;line-height:1.35}.step .node{width:18px;height:18px;border-radius:50%;border:2px solid #bacdea;background:#f7fbff;margin:1px auto 14px;position:relative;z-index:2;box-shadow:0 0 0 4px rgba(248,252,255,.78)}",
  ".step.active .node,.step.done .node{background:#14b98a;border-color:#14b98a}.step.active,.step.done{color:#10265e}",
  ".security{position:absolute;left:50%;top:586px;transform:translateX(-50%);width:350px;height:70px;z-index:6;border:1px solid rgba(210,226,243,.92);border-radius:10px;background:linear-gradient(145deg,rgba(255,255,255,.82),rgba(241,249,253,.69));display:flex;align-items:center;padding:0 20px;gap:15px;box-shadow:inset 0 1px 0 rgba(255,255,255,.86)}",
  ".security svg{width:28px;height:28px;stroke:#0fa6a2;fill:none;stroke-width:1.7;stroke-linecap:round;stroke-linejoin:round;flex:none}.security strong{display:block;color:#147e91;font-size:10.5px;font-weight:550}.security span{display:block;margin-top:4px;color:#708bb4;font-size:9.5px}",
  "",
  "/* Loading brand refinement \u2014 same visual hierarchy as the approved reference */",
  ".loading-brand{",
  "  position:absolute;",
  "  left:0;",
  "  right:0;",
  "  top:69px;",
  "  height:120px;",
  "  z-index:6;",
  "  display:flex;",
  "  flex-direction:column;",
  "  align-items:center;",
  "  justify-content:flex-start;",
  "}",
  ".loading-mark-shell{",
  "  position:relative;",
  "  width:92px;",
  "  height:65px;",
  "  display:flex;",
  "  align-items:center;",
  "  justify-content:center;",
  "}",
  ".loading-mark-shell:before{",
  "  content:\"\";",
  "  position:absolute;",
  "  width:72px;",
  "  height:42px;",
  "  border-radius:50%;",
  "  background:radial-gradient(ellipse at center,rgba(23,158,231,.14),rgba(35,212,181,.05) 55%,transparent 76%);",
  "  filter:blur(8px);",
  "}",
  ".loading-mark{",
  "  position:relative;",
  "  z-index:2;",
  "  display:block;",
  "  width:86px;",
  "  height:auto;",
  "  max-height:63px;",
  "  object-fit:contain;",
  "  filter:drop-shadow(0 5px 10px rgba(20,109,195,.10));",
  "}",
  ".loading-wordmark{",
  "  margin-top:0;",
  "  color:#08123f;",
  "  font-size:22px;",
  "  line-height:1;",
  "  font-weight:760;",
  "  letter-spacing:-.5px;",
  "}",
  ".loading-subbrand{",
  "  margin-top:5px;",
  "  color:#3a5491;",
  "  font-size:13px;",
  "  line-height:1;",
  "  font-weight:500;",
  "}",
  ".spinner-wrap{top:220px}",
  ".loading-copy{top:386px}",
  ".progress{top:482px}",
  ".security{top:583px}",
  ".stage{",
  "  background:",
  "    radial-gradient(560px 360px at 50% 27%,rgba(76,197,225,.085),transparent 68%),",
  "    linear-gradient(180deg,#fcfdff 0%,#f4faff 70%,#fbfdff 100%);",
  "}",
  ".spinner{",
  "  filter:drop-shadow(0 7px 13px rgba(47,164,214,.13));",
  "}",
  ".wave-field{opacity:.82}",
  "",
  "",
  "/* Experience v2 \u2014 loading choreography, type, feedback */",
  "html,body{",
  "  -webkit-font-smoothing:antialiased;",
  "  text-rendering:optimizeLegibility;",
  "  font-family:\"SF Pro Text\",\"Segoe UI Variable Text\",\"Inter\",\"Segoe UI\",ui-sans-serif,system-ui,sans-serif;",
  "}",
  ".loading-wordmark,.loading-copy h1{",
  "  font-family:\"SF Pro Display\",\"Segoe UI Variable Display\",\"Inter\",\"Segoe UI\",ui-sans-serif,system-ui,sans-serif",
  "}",
  ".loading-wordmark{font-weight:760;letter-spacing:-.58px}",
  ".loading-copy h1{font-size:26px;font-weight:790;letter-spacing:-.78px;transition:color .25s ease,transform .25s ease}",
  ".loading-copy p{font-size:12.7px;letter-spacing:-.03px;transition:opacity .18s ease,transform .18s ease}",
  ".loading-copy.is-changing p{opacity:.22;transform:translateY(2px)}",
  ".spinner-wrap{transition:transform .25s ease,filter .25s ease}",
  ".spinner-wrap:before{",
  "  content:\"\";position:absolute;inset:-16px;border-radius:50%;border:1px solid rgba(82,198,228,.075);",
  "  animation:haloPulse 2.5s ease-in-out infinite",
  "}",
  ".spinner-wrap:after{",
  "  content:\"\";position:absolute;left:50%;top:50%;width:88px;height:88px;border-radius:50%;",
  "  transform:translate(-50%,-50%);background:radial-gradient(circle,rgba(255,255,255,.86),rgba(245,252,255,.58) 58%,transparent 72%);",
  "  box-shadow:0 0 24px rgba(93,198,226,.055)",
  "}",
  "@keyframes haloPulse{0%,100%{transform:scale(.96);opacity:.35}50%{transform:scale(1.05);opacity:.8}}",
  ".spinner{z-index:2}",
  ".spinner:before{",
  "  content:\"\";position:absolute;left:13px;top:6px;width:21px;height:6px;border-radius:50%;",
  "  background:rgba(255,255,255,.78);filter:blur(1px);transform:rotate(-18deg)",
  "}",
  ".spinner-halo{animation:haloBreath 2.7s ease-in-out infinite}",
  "@keyframes haloBreath{0%,100%{opacity:.72;transform:scale(.96)}50%{opacity:1;transform:scale(1.04)}}",
  ".spinner-center{",
  "  position:absolute;left:50%;top:50%;z-index:4;transform:translate(-50%,-50%);",
  "  width:66px;height:66px;border-radius:50%;display:flex;flex-direction:column;align-items:center;justify-content:center;",
  "  color:#346ca9;pointer-events:none",
  "}",
  ".spinner-percent{font-size:16px;font-weight:750;letter-spacing:-.45px;color:#184f91}",
  ".spinner-caption{margin-top:2px;font-size:6.7px;letter-spacing:.8px;text-transform:uppercase;color:#7895bd}",
  ".progress-line{height:2px;border-radius:999px;overflow:visible;background:linear-gradient(90deg,#d7e5f1,#cbd9ed,#d9e6f2)}",
  ".progress-fill{",
  "  height:2px;border-radius:999px;background:linear-gradient(90deg,#23c79e,#4ed5cf 45%,#4e9ff4);",
  "  box-shadow:0 0 9px rgba(53,190,203,.18);transition:width .55s cubic-bezier(.2,.75,.25,1)",
  "}",
  ".progress-fill:after{",
  "  content:\"\";position:absolute;right:-3px;top:-2px;width:6px;height:6px;border-radius:50%;",
  "  background:#48bde1;box-shadow:0 0 0 4px rgba(72,189,225,.08),0 0 10px rgba(42,198,193,.28)",
  "}",
  ".step{transition:color .25s ease,transform .25s ease;font-weight:470}",
  ".step .node{transition:background .25s ease,border-color .25s ease,box-shadow .25s ease,transform .25s ease}",
  ".step.active{font-weight:650;color:#0e2a67;transform:translateY(-1px)}",
  ".step.active .node{box-shadow:0 0 0 5px rgba(20,185,138,.075),0 0 15px rgba(20,185,138,.15);animation:nodePulse 1.5s ease-in-out infinite}",
  ".step.done{color:#3972a4}.step.done .node{box-shadow:0 0 0 4px rgba(20,185,138,.055)}",
  "@keyframes nodePulse{0%,100%{transform:scale(1)}50%{transform:scale(1.08)}}",
  ".loading-detail{",
  "  position:absolute;left:0;right:0;top:545px;text-align:center;z-index:7;",
  "  color:#7b90ba;font-size:8.7px;letter-spacing:.08px;opacity:.9",
  "}",
  ".loading-detail strong{color:#486b9e;font-weight:600}",
  ".security{",
  "  transition:transform .3s ease,border-color .3s ease,box-shadow .3s ease;",
  "  box-shadow:0 9px 24px rgba(51,88,127,.035),inset 0 1px 0 rgba(255,255,255,.88)",
  "}",
  ".security:hover{transform:translateX(-50%) translateY(-1px);border-color:#cbddec;box-shadow:0 12px 28px rgba(51,88,127,.055)}",
  ".security-icon-shell{",
  "  width:36px;height:36px;border-radius:9px;background:rgba(228,249,247,.66);display:grid;place-items:center;flex:none;",
  "  box-shadow:inset 0 0 0 1px rgba(19,166,162,.06)",
  "}",
  ".security-icon-shell svg{width:24px;height:24px}",
  ".loading-toast{",
  "  position:absolute;left:50%;top:682px;transform:translate(-50%,5px);z-index:15;min-width:230px;",
  "  padding:8px 12px;border:1px solid #dbe7f3;border-radius:9px;background:rgba(255,255,255,.92);",
  "  box-shadow:0 10px 25px rgba(45,80,119,.08);color:#476892;font-size:8.7px;text-align:center;",
  "  opacity:0;pointer-events:none;transition:opacity .2s ease,transform .2s ease",
  "}",
  ".loading-toast.show{opacity:1;transform:translate(-50%,0)}",
  ".loading-toast.error{border-left:3px solid #d85c68;color:#b24e5d}",
  ".loading-toast.success{border-left:3px solid #14af70;color:#0d8c5a}",
  ".stage.state-success .spinner{",
  "  animation-duration:.75s;background:conic-gradient(from 0deg,#2fd0a4,#55dfc4,#41b7ee,#2fd0a4)",
  "}",
  ".stage.state-success .loading-copy h1{color:#0c8758}",
  ".stage.state-error .spinner{",
  "  animation:none;background:conic-gradient(from 0deg,#e6909b,#df6675,#f2b4bc,#e6909b)",
  "}",
  ".stage.state-error .loading-copy h1{color:#b94f5f}",
  ".stage.state-paused .spinner,.stage.state-paused .spinner-halo{animation-play-state:paused}",
  "@media(prefers-reduced-motion:reduce){",
  "  *,*:before,*:after{animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important}",
  "}",
  "",
  "</style>",
  "</head>",
  "<body>",
  "<div class=\"viewport\"><main class=\"stage\">",
  "  ",
  "<section class=\"loading-brand\" aria-label=\"DreamWorker MCP Control Plane\">",
  "  <div class=\"loading-mark-shell\"><img class=\"loading-mark\" src=\"data:image/png;base64,",
].join("\n") +
  DW_AUTH_LOGO_B64 +
  [
  "\" alt=\"\"></div>",
  "  <div class=\"loading-wordmark\">DreamWorker</div>",
  "  <div class=\"loading-subbrand\">MCP Control Plane</div>",
  "</section>",
  "  <div class=\"spinner-wrap\">",
  "      <div class=\"spinner-halo\"></div><div class=\"spinner\"></div>",
  "      <div class=\"spinner-center\"><div id=\"spinner-percent\" class=\"spinner-percent\">18%</div><div class=\"spinner-caption\">secure</div></div>",
  "    </div>",
  "  <section class=\"loading-copy\"><h1 id=\"loading-title\">Signing you in...</h1><p id=\"loading-subtitle\">Connecting to your environment</p></section>",
  "  <section class=\"progress\">",
  "    <div class=\"progress-line\"></div><div id=\"progress-fill\" class=\"progress-fill\"></div>",
  "    <div class=\"steps\">",
  "      <div class=\"step active\" data-step=\"0\"><div class=\"node\"></div><div>Authenticating</div></div>",
  "      <div class=\"step\" data-step=\"1\"><div class=\"node\"></div><div>Loading<br>workspace</div></div>",
  "      <div class=\"step\" data-step=\"2\"><div class=\"node\"></div><div>Checking<br>permissions</div></div>",
  "      <div class=\"step\" data-step=\"3\"><div class=\"node\"></div><div>Almost there...</div></div>",
  "    </div>",
  "  </section>",
  "  <div id=\"loading-detail\" class=\"loading-detail\"><strong>Secure session</strong> \u00b7 authenticating your control-plane access</div>",
  "  <div class=\"security\"><div class=\"security-icon-shell\"><svg viewBox=\"0 0 24 24\"><path d=\"M12 3 19 6v5c0 4.5-2.8 7.9-7 10-4.2-2.1-7-5.5-7-10V6l7-3Z\"/><path d=\"m9 12 2 2 4-4\"/></svg></div><div><strong>Your data stays private and secure.</strong><span>Powered by open tools.</span></div></div>",
  "  ",
  "<svg class=\"wave-field\" viewBox=\"0 0 1368 330\" preserveAspectRatio=\"none\" aria-hidden=\"true\">",
  "  <defs>",
  "    <linearGradient id=\"wb1\" x1=\"0\" x2=\"1\"><stop stop-color=\"#dcefff\" stop-opacity=\".08\"/><stop offset=\".44\" stop-color=\"#79b8ff\" stop-opacity=\".44\"/><stop offset=\".72\" stop-color=\"#2d86f5\" stop-opacity=\".64\"/><stop offset=\"1\" stop-color=\"#dff4ff\" stop-opacity=\".05\"/></linearGradient>",
  "    <linearGradient id=\"wb2\" x1=\"0\" x2=\"1\"><stop stop-color=\"#ecf8ff\" stop-opacity=\".04\"/><stop offset=\".48\" stop-color=\"#4198f7\" stop-opacity=\".36\"/><stop offset=\".82\" stop-color=\"#84d3ff\" stop-opacity=\".22\"/><stop offset=\"1\" stop-color=\"#f0fbff\" stop-opacity=\".02\"/></linearGradient>",
  "    <linearGradient id=\"wm1\" x1=\"0\" x2=\"1\"><stop stop-color=\"#effffb\" stop-opacity=\".03\"/><stop offset=\".46\" stop-color=\"#55d8c9\" stop-opacity=\".46\"/><stop offset=\".78\" stop-color=\"#21c5a8\" stop-opacity=\".56\"/><stop offset=\"1\" stop-color=\"#e6fbf8\" stop-opacity=\".04\"/></linearGradient>",
  "    <filter id=\"waveBlur\"><feGaussianBlur stdDeviation=\"8\"/></filter>",
  "  </defs>",
  "  <path d=\"M0 213C121 178 235 190 348 240c106 47 211 52 312 8 103-45 153-119 230-137 87-19 137 72 218 98 90 29 168-28 260-42v163H0Z\" fill=\"url(#wb2)\"/>",
  "  <path d=\"M0 252c155-15 252 43 371 37 126-7 191-62 274-116 79-50 139-88 209-48 89 52 99 126 206 118 99-7 163-61 308-53v140H0Z\" fill=\"url(#wb1)\" opacity=\".77\"/>",
  "  <path d=\"M0 280c129-9 246 30 357 17 131-15 186-94 277-115 92-21 147 21 214 74 66 53 143 62 222 22 74-38 150-96 298-76v128H0Z\" fill=\"url(#wm1)\" opacity=\".72\"/>",
  "  <path d=\"M116 302c132-5 239-33 336-100 91-63 145-101 214-68 63 31 105 119 180 136 87 20 136-63 237-71 87-6 169 42 285 65\" fill=\"none\" stroke=\"#5a9ff7\" stroke-opacity=\".46\" stroke-width=\"1.2\"/>",
  "  <path d=\"M214 315c124-18 220-62 311-130 85-64 138-87 198-54 64 36 90 119 174 139 91 22 146-72 249-73 74-1 142 36 222 67\" fill=\"none\" stroke=\"#4cd5bd\" stroke-opacity=\".46\" stroke-width=\"1.1\"/>",
  "  <ellipse cx=\"690\" cy=\"239\" rx=\"165\" ry=\"41\" fill=\"#49c6db\" opacity=\".06\" filter=\"url(#waveBlur)\"/>",
  "</svg>",
  "",
  "<div id=\"loading-toast\" class=\"loading-toast\" role=\"status\" aria-live=\"polite\"></div>",
  "</main></div>",
  "<script>",
  "",
  "(function(){",
  "  const stage=document.querySelector('.stage');",
  "  const steps=[...document.querySelectorAll('.step')];",
  "  const fill=document.getElementById('progress-fill');",
  "  const title=document.getElementById('loading-title');",
  "  const subtitle=document.getElementById('loading-subtitle');",
  "  const detail=document.getElementById('loading-detail');",
  "  const percent=document.getElementById('spinner-percent');",
  "  const toast=document.getElementById('loading-toast');",
  "",
  "  const states=[",
  "    {title:'Signing you in...',subtitle:'Connecting to your environment',detail:'Secure session \u00b7 authenticating your control-plane access',progress:18,step:0},",
  "    {title:'Signing you in...',subtitle:'Loading your workspace',detail:'Workspace \u00b7 preparing providers, models, routes and tools',progress:43,step:1},",
  "    {title:'Signing you in...',subtitle:'Checking permissions',detail:'Permissions \u00b7 validating your administrative capabilities',progress:69,step:2},",
  "    {title:'Almost there...',subtitle:'Preparing your control plane',detail:'Final checks \u00b7 synchronizing the dashboard experience',progress:91,step:3}",
  "  ];",
  "",
  "  let index=0,timer=null,paused=false,completed=false;",
  "",
  "  function emit(name,payload){window.dispatchEvent(new CustomEvent(name,{detail:payload}));}",
  "  function showToast(message,type=''){",
  "    toast.textContent=message;toast.className='loading-toast show '+type;",
  "    clearTimeout(window.__dwLoadToast);",
  "    window.__dwLoadToast=setTimeout(()=>toast.className='loading-toast',1900);",
  "  }",
  "  function setProgress(value){",
  "    value=Math.max(0,Math.min(100,Math.round(value)));",
  "    const min=166,max=728;",
  "    fill.style.width=(min+(max-min)*(value/100))+'px';",
  "    percent.textContent=value+'%';",
  "  }",
  "  function setCopy(text){",
  "    const copy=document.querySelector('.loading-copy');",
  "    copy.classList.add('is-changing');",
  "    setTimeout(()=>{subtitle.textContent=text;copy.classList.remove('is-changing');},115);",
  "  }",
  "  function render(state,customDetail){",
  "    completed=false;stage.classList.remove('state-success','state-error');",
  "    steps.forEach((el,i)=>{el.classList.toggle('done',i<state.step);el.classList.toggle('active',i===state.step);});",
  "    title.textContent=state.title;setCopy(state.subtitle);",
  "    const parts=state.detail.split(' \u00b7 ');",
  "    detail.innerHTML='<strong>'+parts[0]+'</strong> \u00b7 '+(customDetail||parts.slice(1).join(' \u00b7 '));",
  "    setProgress(state.progress);",
  "    emit('dreamworker:loading-step',{index:state.step,progress:state.progress,subtitle:state.subtitle});",
  "  }",
  "  function setStep(step,message){",
  "    const s=states[Math.max(0,Math.min(states.length-1,Number(step)||0))];",
  "    index=s.step;render(s,message);",
  "  }",
  "  function schedule(){",
  "    clearTimeout(timer);",
  "    if(paused||completed)return;",
  "    const delays=[1550,1650,1750,1750];",
  "    timer=setTimeout(()=>{",
  "      if(index<states.length-1){index++;render(states[index]);schedule();}",
  "      else complete();",
  "    },delays[index]||1600);",
  "  }",
  "  function start(){",
  "    paused=false;completed=false;index=0;",
  "    stage.classList.remove('state-paused','state-error','state-success');",
  "    render(states[0]);schedule();emit('dreamworker:loading-start',{});",
  "  }",
  "  function pause(){",
  "    paused=true;clearTimeout(timer);stage.classList.add('state-paused');",
  "    showToast('Loading preview paused.');emit('dreamworker:loading-pause',{index});",
  "  }",
  "  function resume(){",
  "    if(!paused)return;",
  "    paused=false;stage.classList.remove('state-paused');",
  "    showToast('Loading preview resumed.');schedule();emit('dreamworker:loading-resume',{index});",
  "  }",
  "  function setError(message='Unable to complete authentication.'){",
  "    clearTimeout(timer);completed=true;",
  "    stage.classList.remove('state-success','state-paused');stage.classList.add('state-error');",
  "    title.textContent='Unable to continue';subtitle.textContent=message;",
  "    detail.innerHTML='<strong>Action required</strong> \u00b7 check authentication or workspace access';",
  "    showToast(message,'error');emit('dreamworker:loading-error',{message});",
  "  }",
  "  function complete(message='Your control plane is ready'){",
  "    clearTimeout(timer);completed=true;",
  "    stage.classList.remove('state-error','state-paused');stage.classList.add('state-success');",
  "    steps.forEach(el=>{el.classList.add('done');el.classList.remove('active');});",
  "    setProgress(100);title.textContent='Ready';subtitle.textContent=message;",
  "    detail.innerHTML='<strong>Complete</strong> \u00b7 dashboard handoff is ready';",
  "    showToast('Workspace ready. No redirect is performed in preview mode.','success');",
  "    emit('dreamworker:loading-complete',{progress:100});",
  "  }",
  "  function reset(){clearTimeout(timer);start();}",
  "",
  "  window.DreamWorkerLoadingUI={start,setStep,setProgress,setError,complete,reset,pause,resume,showToast};",
  "",
  "  document.querySelector('.security').addEventListener('click',()=>{paused?resume():pause();});",
  "  start();",
  "})();",
  "",
  "</script>",
  "</body></html>",
].join("\n");
