/**
 * GENERATED FILE — do not edit by hand.
 * Run: node scripts/generate-approved-pages.mjs
 *
 * Byte-identical reproduction of the approved reference document:
 *   ui-reference/my_mcp_tools_providers_experience_v1_1368x753.html
 *   bytes  : 585809
 *   sha256 : 9ef29a8c4ee8068c54342fe01017d94d63100bbd9ac549fd836da648d383f00a
 *
 * Any edit here breaks the approved-visual contract enforced by
 * test/approved-pages-byte-identity.test.ts.
 */
import { DW_CONSOLE_LOGO_B64 } from "./assets";

export const PROVIDERS_SHA256 = "9ef29a8c4ee8068c54342fe01017d94d63100bbd9ac549fd836da648d383f00a";

export const PROVIDERS_HTML: string =
  [
  "<!doctype html>",
  "<html lang=\"en\">",
  "<head>",
  "<meta charset=\"utf-8\">",
  "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">",
  "<title>DreamWorker MCP Control Plane \u2014 Approved Dashboard Full Detail</title>",
  "<!--",
  "MY MCP TOOLS \u2014 approved Overview recreation / full-detail vector refinement",
  "Reference viewport: 1368 \u00d7 753",
  "Display-only / offline:",
  "- no external assets",
  "- no fetch/XHR/WebSocket",
  "- no redirects",
  "- no backend connection",
  "Integration hooks are local-only and can be connected later without redesigning the page.",
  "-->",
  "<style>",
  ":root{",
  "  --navy-950:#071d42;",
  "  --navy-900:#0a2855;",
  "  --navy-850:#0c3268;",
  "  --navy-800:#123d78;",
  "  --blue:#176ff2;",
  "  --blue-2:#2e91ff;",
  "  --cyan:#20bce8;",
  "  --mint:#29d5b4;",
  "  --green:#11aa69;",
  "  --green-2:#17c17b;",
  "  --green-bg:#e9faf2;",
  "  --ink:#08123e;",
  "  --ink-2:#143b7d;",
  "  --muted:#6178b3;",
  "  --muted-2:#7e91c0;",
  "  --line:#dce7f3;",
  "  --soft:#f3f8fd;",
  "  --soft-2:#f8fbff;",
  "  --white:#fff;",
  "  --shadow:0 8px 22px rgba(37,73,118,.055);",
  "}",
  "*{box-sizing:border-box}",
  "html,body{",
  "  margin:0;width:100%;height:100%;",
  "  font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,\"Segoe UI\",Arial,sans-serif;",
  "  color:var(--ink);background:#eaf2f8",
  "}",
  "body{overflow:hidden}",
  "button,input{font:inherit}",
  "a{text-decoration:none;color:inherit}",
  "svg.icon{width:100%;height:100%;display:block;stroke:currentColor;fill:none;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}",
  ".viewport{",
  "  width:100vw;height:100vh;display:grid;place-items:center;",
  "  background:linear-gradient(180deg,#f4f8fc,#e8f0f7)",
  "}",
  ".app{",
  "  position:relative;width:1368px;height:753px;overflow:hidden;transform-origin:center;",
  "  background:#f9fbfe;box-shadow:0 24px 70px rgba(20,48,85,.16)",
  "}",
  "@media(max-width:1368px),(max-height:753px){",
  "  .app{transform:scale(min(calc(100vw / 1368),calc(100vh / 753)))}",
  "}",
  "",
  "/* SIDEBAR */",
  ".sidebar{",
  "  position:absolute;left:0;top:0;width:207px;height:753px;z-index:5;color:#e2edff;overflow:hidden;",
  "  background:",
  "    radial-gradient(210px 440px at 106% 45%,rgba(27,119,212,.20),transparent 58%),",
  "    linear-gradient(180deg,#0b2c5e 0%,#08244d 54%,#071c3d 100%);",
  "  border-right:1px solid rgba(130,191,240,.22);",
  "  box-shadow:12px 0 30px rgba(21,56,101,.11)",
  "}",
  ".sidebar:after{",
  "  content:\"\";position:absolute;right:0;top:0;width:1px;height:100%;",
  "  background:linear-gradient(180deg,rgba(106,200,255,.72),rgba(106,200,255,.05) 46%,rgba(48,212,191,.34))",
  "}",
  ".brand{",
  "  position:absolute;left:24px;top:18px;width:160px;text-align:center",
  "}",
  ".dw-mark{width:104px;height:76px;margin:0 auto 1px;filter:drop-shadow(0 6px 12px rgba(14,119,211,.22))}",
  ".brand strong{display:block;color:#fff;font-size:21px;line-height:1;font-weight:760;letter-spacing:-.55px}",
  ".brand span{display:block;margin-top:5px;color:#c3d7f3;font-size:13px;line-height:1;font-weight:500}",
  "",
  ".nav{",
  "  position:absolute;left:12px;top:144px;width:183px;",
  "  display:flex;flex-direction:column;gap:3px",
  "}",
  ".nav-item{",
  "  position:relative;height:43px;border-radius:8px;display:flex;align-items:center;gap:13px;",
  "  padding:0 14px;color:#e1ebfb;font-size:13px;border:1px solid transparent;cursor:pointer",
  "}",
  ".nav-item .ni{width:21px;height:21px;color:#edf5ff;flex:none}",
  ".nav-item.active{",
  "  background:linear-gradient(90deg,rgba(29,99,212,.82),rgba(35,112,207,.46));",
  "  border-color:rgba(54,172,255,.55);",
  "  box-shadow:inset 0 1px 0 rgba(255,255,255,.04),0 7px 20px rgba(0,86,193,.16);",
  "  color:#fff;font-weight:650",
  "}",
  ".nav-item.active:before{",
  "  content:\"\";position:absolute;left:0;top:8px;width:3px;height:26px;border-radius:5px;",
  "  background:#1de0b2;box-shadow:0 0 10px rgba(29,224,178,.50)",
  "}",
  ".nav-item:hover{background:rgba(255,255,255,.05)}",
  "",
  ".side-foot{",
  "  position:absolute;left:29px;right:29px;bottom:21px;padding-top:15px;",
  "  border-top:1px solid rgba(142,183,232,.27);color:#bfd0eb",
  "}",
  ".side-foot b{display:block;font-size:10px;color:#f1f6ff;margin-bottom:5px}",
  ".side-foot span{display:block;font-size:9px;line-height:1.55}",
  ".side-foot .version{margin-top:6px;color:#95afd3}",
  "",
  "/* HEADER */",
  ".header{",
  "  position:absolute;left:207px;top:0;width:1161px;height:55px;z-index:4;",
  "  background:rgba(255,255,255,.97);border-bottom:1px solid #dfe8f3;",
  "  box-shadow:0 3px 11px rgba(46,77,113,.035)",
  "}",
  ".search{",
  "  position:absolute;left:24px;top:11px;width:632px;height:34px;border:1px solid #d7e3f2;border-radius:9px;",
  "  background:#f8fbff;display:flex;align-items:center;padding:0 11px;gap:9px;color:#345b98",
  "}",
  ".search .si{width:17px;height:17px;color:#193f86}",
  ".search input{flex:1;border:0;outline:0;background:transparent;color:#31558f;font-size:11px}",
  ".search input::placeholder{color:#667fb0}",
  ".kbd{",
  "  height:23px;min-width:47px;border:1px solid #dbe5f3;background:#fff;border-radius:6px;",
  "  display:grid;place-items:center;color:#5d77aa;font-size:9px",
  "}",
  ".head-right{position:absolute;right:22px;top:0;height:55px;display:flex;align-items:center;gap:10px}",
  ".prod{",
  "  height:32px;padding:0 13px;border-radius:999px;background:#e9fbf2;color:#07834f;",
  "  display:flex;align-items:center;gap:7px;font-size:10px;font-weight:650",
  "}",
  ".prod .pc{width:15px;height:15px}",
  ".hicon{position:relative;width:31px;height:31px;display:grid;place-items:center;color:#153d82}",
  ".hicon .hi{width:19px;height:19px}",
  ".badge{",
  "  position:absolute;right:0;top:1px;width:13px;height:13px;border-radius:50%;background:#ff3434;",
  "  border:2px solid white;color:white;font-size:6.5px;display:grid;place-items:center",
  "}",
  ".headuser{display:flex;align-items:center;gap:8px;margin-left:2px}",
  ".headuser .avatar{width:32px;height:32px;border-radius:50%;display:grid;place-items:center;color:white;background:linear-gradient(145deg,#16bf74,#0baaa8);font-size:11px}",
  ".headuser b{display:block;font-size:10.5px;color:#0b1948}.headuser small{display:block;font-size:7.8px;color:#6d83af;margin-top:1px}",
  ".headuser .chev{width:14px;height:14px;color:#183e7e;margin-left:4px}",
  "",
  "/* MAIN */",
  ".main{",
  "  position:absolute;left:207px;top:55px;width:1161px;height:698px;",
  "  background:",
  "    radial-gradient(circle at 73% 0%,rgba(76,197,234,.10),transparent 26%),",
  "    linear-gradient(180deg,#fbfdff,#f8fbff)",
  "}",
  ".hero{",
  "  position:absolute;left:25px;top:25px;width:1112px;height:119px",
  "}",
  ".date{font-size:9.7px;color:#295095;margin-bottom:10px}",
  ".hero h1{",
  "  margin:0;font-size:34px;line-height:1;color:#08123d;font-weight:820;letter-spacing:-1.05px",
  "}",
  ".hero h1 .wave-hand{font-size:25px;vertical-align:4px;margin-left:6px}",
  ".hero p{margin:8px 0 0;font-size:13.2px;color:#536fa9}",
  ".hero-art{position:absolute;right:117px;top:-9px;width:440px;height:126px;opacity:.96}",
  ".hero-tag{",
  "  position:absolute;right:2px;top:17px;width:120px;color:#365990;font-size:17px;line-height:.96;font-weight:600",
  "}",
  ".hero-tag .accent{width:17px;height:2px;background:#16bd70;margin:8px 0}",
  ".hero-tag small{display:block;color:#6a81ad;font-size:8px;line-height:1.32;font-weight:400}",
  "",
  "/* METRICS */",
  ".metrics{",
  "  position:absolute;left:25px;top:145px;width:1112px;height:89px;",
  "  display:grid;grid-template-columns:repeat(4,1fr);gap:11px",
  "}",
  ".card{",
  "  background:rgba(255,255,255,.98);border:1px solid var(--line);border-radius:10px;",
  "  box-shadow:var(--shadow)",
  "}",
  ".metric{position:relative;height:89px}",
  ".micon{",
  "  position:absolute;left:14px;top:14px;width:48px;height:48px;border-radius:10px;",
  "  background:#eef5ff;color:#146fea;display:grid;place-items:center",
  "}",
  ".micon.green{background:#e9fbf3;color:#0aa967}",
  ".micon .mi{width:28px;height:28px}",
  ".mtitle{position:absolute;left:77px;top:17px;font-size:10px;color:#163c7b;font-weight:700}",
  ".mvalue{position:absolute;left:77px;top:36px;font-size:21px;font-weight:800;color:#0b1747}",
  ".msub{position:absolute;left:77px;top:63px;font-size:9px;color:#657fb4}",
  ".marrow{position:absolute;right:14px;top:35px;width:17px;height:17px;color:#1f50a2}",
  ".metric-check{position:absolute;right:15px;bottom:13px;width:14px;height:14px;color:#0ea866}",
  ".metric-check svg{fill:currentColor;stroke:none}",
  "",
  "/* PANELS */",
  ".panel{",
  "  position:absolute;background:#fff;border:1px solid var(--line);border-radius:10px;box-shadow:var(--shadow);overflow:hidden",
  "}",
  ".panelhead{",
  "  height:49px;padding:11px 12px 0;display:flex;align-items:flex-start;gap:9px",
  "}",
  ".phicon{",
  "  width:31px;height:31px;border-radius:8px;background:#eef5ff;color:#126fea;display:grid;place-items:center;flex:none",
  "}",
  ".phicon.green{background:#eafbf3;color:#0aaa69}",
  ".phicon .pi{width:18px;height:18px}",
  ".phtitle{font-size:13px;font-weight:800;line-height:1.05}.phsub{font-size:8.5px;color:#647fb3;margin-top:3px}",
  ".view{",
  "  margin-left:auto;height:28px;border:0;background:transparent;color:#153c80;padding:0 4px;font-size:9px;",
  "  display:flex;align-items:center;gap:6px;cursor:pointer",
  "}",
  ".view .vi{width:14px;height:14px}",
  "",
  "/* PROVIDERS */",
  ".providers{left:25px;top:247px;width:657px;height:171px}",
  ".providers .body{",
  "  position:absolute;left:11px;right:11px;top:49px;bottom:12px;display:grid;grid-template-columns:repeat(3,1fr);gap:9px",
  "}",
  ".prov{",
  "  position:relative;border:1px solid #dfe8f4;border-radius:8px;padding:10px;background:linear-gradient(180deg,#fff,#fbfdff)",
  "}",
  ".provtop{display:flex;align-items:center;gap:8px}",
  ".plogo{width:36px;height:36px;border-radius:9px;display:grid;place-items:center;flex:none}",
  ".google-logo{background:white}",
  ".anthropic-logo{background:#f5e2d4;color:#111;font-size:20px;font-weight:850}",
  ".openai-logo{background:white;color:#0a1743}",
  ".pname{font-size:9.8px;font-weight:800;color:#0f1c4d}",
  ".healthy{display:flex;align-items:center;gap:5px;margin-top:4px;color:#07935b;font-size:7.8px;font-weight:600}",
  ".healthy i{width:6px;height:6px;border-radius:50%;background:#0dae69}",
  ".parrow{margin-left:auto;width:15px;height:15px;color:#154e9f}",
  ".pstats{display:grid;grid-template-columns:1fr .8fr .8fr;align-items:center;gap:5px;margin-top:10px}",
  ".modelbadge{width:max-content;border-radius:999px;background:#edf5ff;color:#1e56a9;padding:5px 8px;font-size:7px}",
  ".pstat b{display:block;font-size:9.5px;color:#0f245e}.pstat small{display:block;font-size:6.7px;color:#6980b0;margin-top:1px}",
  "",
  "/* HEALTH */",
  ".health{left:693px;top:247px;width:444px;height:198px}",
  ".health .panelhead{height:52px}",
  ".allhealthy{",
  "  margin-left:auto;margin-top:2px;height:26px;padding:0 9px;border-radius:999px;background:#e8faf1;",
  "  color:#078b56;display:flex;align-items:center;gap:6px;font-size:8.2px;font-weight:650",
  "}",
  ".allhealthy i{width:6px;height:6px;border-radius:50%;background:#0dae69}",
  ".health-table{padding:0 11px}",
  ".hrow{",
  "  height:24px;display:grid;grid-template-columns:1.55fr 1fr .55fr;align-items:center;",
  "  border-top:1px solid #edf2f7;font-size:7.7px;color:#173d7b",
  "}",
  ".hrow:first-child{border-top:1px solid #e8eef6}",
  ".hcomp{display:flex;align-items:center;gap:7px}.hcomp i{width:7px;height:7px;border-radius:50%;background:#0eaa66}",
  ".hstatus{color:#09915a;font-weight:600;display:flex;align-items:center;gap:6px}.hstatus i{width:6px;height:6px;border-radius:50%;background:#0eaa66}",
  ".hlat{color:#627bb0}",
  "",
  "/* ACTIVITY */",
  ".activity{left:25px;top:430px;width:657px;height:279px}",
  ".activity .panelhead{height:49px}",
  ".activity-body{padding:0 11px}",
  ".arow{",
  "  height:38px;border-top:1px solid #edf2f7;display:grid;",
  "  grid-template-columns:30px 1.4fr 1fr 74px 70px;align-items:center;font-size:7.8px",
  "}",
  ".arow .statusdot{width:7px;height:7px;border-radius:50%;background:#0eaa66;margin-left:3px}",
  ".aevent b{display:block;font-size:8.6px;color:#10265b}.aevent span{display:block;color:#6a81b2;margin-top:2px}",
  ".success{",
  "  height:22px;width:70px;border-radius:999px;background:#e8faf1;color:#078b56;",
  "  display:flex;align-items:center;justify-content:center;gap:6px;font-size:7.4px;font-weight:600",
  "}",
  ".success i{width:6px;height:6px;border-radius:50%;background:#0eaa66}",
  ".atime{color:#5f79ad}",
  "",
  "/* QUICK ACTIONS + QUOTE */",
  ".quick{left:693px;top:457px;width:444px;height:143px}",
  ".quick .panelhead{height:48px}",
  ".quick-grid{padding:0 11px 10px;display:grid;grid-template-columns:1fr 1fr;gap:8px}",
  ".action{",
  "  height:38px;border:1px solid #dfe8f5;border-radius:7px;background:#fff;display:grid;",
  "  grid-template-columns:29px 1fr 14px;align-items:center;gap:8px;padding:0 8px;cursor:pointer;color:#0f245c",
  "}",
  ".action:hover{background:#fbfdff;border-color:#ceddec}",
  ".aico{width:28px;height:28px;border-radius:7px;background:#eef5ff;color:#126fea;display:grid;place-items:center}",
  ".aico .ai{width:17px;height:17px}",
  ".atxt{font-size:8.3px}.action .ar{width:14px;height:14px;color:#214e9c}",
  ".quote{",
  "  left:693px;top:611px;width:444px;height:98px;padding:0 17px;",
  "  display:flex;align-items:center;gap:12px;color:#5d7fbd;font-size:10px;",
  "  background:linear-gradient(180deg,#f8fbff,#f3f8fd)",
  "}",
  ".qmark{font-size:30px;color:#6f8dc6;line-height:1}.qbrand{margin-left:auto;color:#173f85;font-size:10px;font-weight:650}",
  ".qline{width:18px;height:1px;background:#6fa4e5;margin-left:auto}",
  "",
  "/* SMALL FEEDBACK */",
  ".toast{",
  "  position:absolute;right:19px;top:67px;z-index:20;padding:8px 10px;border:1px solid #dbe6f2;border-radius:8px;",
  "  background:rgba(255,255,255,.97);box-shadow:0 9px 24px rgba(26,62,108,.12);font-size:8px;color:#31568f;",
  "  opacity:0;transform:translateY(-4px);pointer-events:none;transition:.16s ease",
  "}",
  ".toast.show{opacity:1;transform:translateY(0)}",
  "",
  "/* Full-quality vector/detail refinement */",
  ".brand-exact{",
  "  left:15px;top:11px;width:177px;height:123px;",
  "  display:flex;align-items:center;justify-content:center;",
  "  filter:drop-shadow(0 8px 18px rgba(17,95,183,.13))",
  "}",
  ".nav{top:145px}",
  ".nav-item .ni{",
  "  width:22px;height:22px;display:grid;place-items:center;",
  "  filter:drop-shadow(0 1px 0 rgba(255,255,255,.04))",
  "}",
  ".nav-item svg.icon{stroke-width:1.78}",
  ".nav-item.active .ni{color:#fff}",
  ".nav-item.active .ni svg{filter:drop-shadow(0 0 5px rgba(98,196,255,.16))}",
  ".phicon,.micon,.aico{",
  "  overflow:hidden;",
  "  box-shadow:inset 0 1px 0 rgba(255,255,255,.74),inset 0 0 0 1px rgba(18,103,213,.025)",
  "}",
  ".phicon:after,.micon:after,.aico:after{",
  "  content:\"\";position:absolute;width:22px;height:22px;border-radius:50%;",
  "  background:currentColor;opacity:.035;transform:translate(12px,-12px)",
  "}",
  ".micon,.phicon,.aico{position:relative}",
  ".micon .mi,.phicon .pi,.aico .ai{position:relative;z-index:2}",
  ".micon svg.icon,.phicon svg.icon,.aico svg.icon{stroke-width:1.75}",
  ".hicon .hi svg,.search .si svg,.headuser .chev svg,.prod svg{stroke-width:1.72}",
  ".wave-hand{display:inline-flex;width:27px;height:27px;vertical-align:-5px;margin-left:5px}",
  ".wave-hand svg{width:100%;height:100%;display:block;filter:drop-shadow(0 3px 5px rgba(210,139,0,.14))}",
  ".hero-art{filter:drop-shadow(0 8px 18px rgba(38,154,205,.05))}",
  ".google-logo{box-shadow:inset 0 0 0 1px #eef2f7}",
  ".anthropic-logo,.openai-logo{overflow:hidden;box-shadow:inset 0 0 0 1px rgba(21,37,71,.06)}",
  ".parrow svg,.view svg,.action .ar svg{stroke-width:1.9}",
  ".health-pill,.allhealthy,.success{box-shadow:inset 0 0 0 1px rgba(13,162,97,.035)}",
  ".sidebar{",
  "  background:",
  "    radial-gradient(210px 360px at 103% 18%,rgba(25,131,222,.23),transparent 58%),",
  "    radial-gradient(230px 320px at 104% 67%,rgba(24,206,180,.07),transparent 68%),",
  "    linear-gradient(180deg,#0b2c5e 0%,#08244d 54%,#071c3d 100%)",
  "}",
  ".sidebar:before{",
  "  content:\"\";position:absolute;left:0;right:0;top:0;height:138px;pointer-events:none;",
  "  background:radial-gradient(140px 90px at 50% 42%,rgba(20,155,236,.11),transparent 67%)",
  "}",
  ".card,.panel{box-shadow:0 8px 22px rgba(37,73,118,.052),inset 0 1px 0 rgba(255,255,255,.72)}",
  ".metric:hover,.panel:hover{border-color:#d4e1ee;box-shadow:0 10px 25px rgba(37,73,118,.062)}",
  ".provider{transition:border-color .16s ease,box-shadow .16s ease,transform .16s ease}",
  ".prov:hover{border-color:#d2e0ef;box-shadow:0 6px 14px rgba(28,70,119,.045);transform:translateY(-1px)}",
  ".action{transition:border-color .15s ease,box-shadow .15s ease,transform .15s ease}",
  ".action:hover{transform:translateY(-1px);box-shadow:0 5px 13px rgba(33,73,119,.045)}",
  "",
  "",
  "/* Sidebar brand \u2014 matched to the approved dashboard reference */",
  ".brand-exact{",
  "  position:absolute;",
  "  left:0;",
  "  top:13px;",
  "  width:207px;",
  "  height:116px;",
  "  display:flex;",
  "  flex-direction:column;",
  "  align-items:center;",
  "  justify-content:flex-start;",
  "  filter:none;",
  "  text-align:center;",
  "  z-index:3;",
  "}",
  ".brand-mark-shell{",
  "  position:relative;",
  "  width:92px;",
  "  height:65px;",
  "  display:flex;",
  "  align-items:center;",
  "  justify-content:center;",
  "  margin:0 auto 1px;",
  "}",
  ".brand-mark-shell:before{",
  "  content:\"\";",
  "  position:absolute;",
  "  width:76px;",
  "  height:44px;",
  "  border-radius:50%;",
  "  background:radial-gradient(ellipse at center,rgba(31,158,242,.17),rgba(28,126,221,.055) 53%,transparent 75%);",
  "  filter:blur(8px);",
  "  pointer-events:none;",
  "}",
  ".brand-mark-img{",
  "  position:relative;",
  "  z-index:2;",
  "  display:block;",
  "  width:90px;",
  "  height:auto;",
  "  max-height:65px;",
  "  object-fit:contain;",
  "  filter:drop-shadow(0 5px 10px rgba(4,20,54,.22));",
  "}",
  ".brand-wordmark{",
  "  margin-top:0;",
  "  color:#ffffff;",
  "  font-size:17px;",
  "  line-height:1.05;",
  "  font-weight:760;",
  "  letter-spacing:-.38px;",
  "  text-shadow:0 1px 8px rgba(5,24,56,.28);",
  "}",
  ".brand-subtitle{",
  "  margin-top:4px;",
  "  color:#c9ddf7;",
  "  font-size:10.5px;",
  "  line-height:1;",
  "  font-weight:500;",
  "  letter-spacing:.05px;",
  "  text-shadow:0 1px 5px rgba(6,30,68,.22);",
  "}",
  "/* Keep navigation aligned exactly under the compact brand lockup */",
  ".nav{top:145px}",
  "",
  "",
  "/* Dashboard Experience V2 \u2014 typography, feedback, states, micro-interactions */",
  "html,body{",
  "  -webkit-font-smoothing:antialiased;",
  "  text-rendering:optimizeLegibility;",
  "  font-family:\"SF Pro Text\",\"Segoe UI Variable Text\",\"Inter\",\"Segoe UI\",ui-sans-serif,system-ui,sans-serif;",
  "}",
  ".hero h1,.phtitle,.brand-wordmark,.mvalue{",
  "  font-family:\"SF Pro Display\",\"Segoe UI Variable Display\",\"Inter\",\"Segoe UI\",ui-sans-serif,system-ui,sans-serif;",
  "}",
  "",
  "/* Global focus language */",
  "button,a,input,[tabindex]{outline:none}",
  "button:focus-visible,a:focus-visible,input:focus-visible,[tabindex]:focus-visible{",
  "  box-shadow:0 0 0 3px rgba(43,121,239,.13)!important;",
  "  border-color:#8cb8ef!important;",
  "}",
  "",
  "/* Sidebar / header refinement */",
  ".sidebar{",
  "  box-shadow:14px 0 34px rgba(17,53,98,.12),inset -1px 0 0 rgba(130,191,240,.12);",
  "}",
  ".brand-wordmark{letter-spacing:-.46px}",
  ".brand-subtitle{letter-spacing:.03px}",
  ".nav-item{",
  "  transition:background .16s ease,border-color .16s ease,transform .16s ease,color .16s ease,box-shadow .16s ease;",
  "}",
  ".nav-item:hover{transform:translateX(1px)}",
  ".nav-item.active{",
  "  box-shadow:inset 0 1px 0 rgba(255,255,255,.04),0 8px 22px rgba(0,86,193,.18),0 0 0 1px rgba(70,181,255,.035);",
  "}",
  ".nav-item .ni{transition:transform .16s ease,filter .16s ease}",
  ".nav-item:hover .ni{transform:scale(1.04)}",
  "",
  ".search{",
  "  transition:border-color .16s ease,box-shadow .16s ease,background .16s ease,transform .16s ease;",
  "}",
  ".search:focus-within{",
  "  border-color:#9dbfe9;background:#fff;",
  "  box-shadow:0 0 0 3px rgba(54,118,213,.07),0 8px 22px rgba(45,83,130,.045);",
  "}",
  ".search input{font-weight:480;letter-spacing:.005px}",
  ".kbd{transition:background .16s ease,border-color .16s ease;color .16s ease}",
  ".search:focus-within .kbd{background:#f4f8fd;border-color:#cfddec;color:#315d9e}",
  ".hicon,.prod,.headuser{transition:transform .15s ease,background .15s ease,box-shadow .15s ease}",
  ".hicon:hover{transform:translateY(-1px);background:#f3f8fe;border-radius:8px}",
  ".prod:hover{transform:translateY(-1px);box-shadow:0 5px 14px rgba(20,168,103,.08)}",
  "",
  "/* Hero */",
  ".hero h1{font-weight:810;letter-spacing:-1.15px}",
  ".hero p{letter-spacing:-.02px}",
  ".hero-art{transition:filter .4s ease,opacity .4s ease;filter:drop-shadow(0 9px 18px rgba(42,156,207,.045))}",
  ".hero:hover .hero-art{filter:drop-shadow(0 11px 22px rgba(42,156,207,.065));opacity:1}",
  "",
  "/* Cards */",
  ".card,.panel{",
  "  transition:transform .16s ease,border-color .16s ease,box-shadow .16s ease;",
  "}",
  ".metric{overflow:hidden;cursor:default}",
  ".metric:before{",
  "  content:\"\";position:absolute;top:-60%;left:-40%;width:28%;height:220%;pointer-events:none;",
  "  background:linear-gradient(90deg,transparent,rgba(255,255,255,.72),transparent);",
  "  transform:rotate(17deg);opacity:0;",
  "}",
  ".metric:hover{",
  "  transform:translateY(-2px);border-color:#d1dfed;",
  "  box-shadow:0 12px 28px rgba(36,74,120,.072),inset 0 1px 0 rgba(255,255,255,.9);",
  "}",
  ".metric:hover:before{opacity:.48;animation:metricSweep .85s ease both}",
  "@keyframes metricSweep{from{left:-38%}to{left:120%}}",
  ".metric:hover .micon{transform:scale(1.035)}",
  ".micon{transition:transform .16s ease,box-shadow .16s ease}",
  ".metric:hover .marrow{transform:translateX(2px)}",
  ".marrow{transition:transform .16s ease}",
  "",
  ".panel:hover{border-color:#d3e0ed;box-shadow:0 11px 27px rgba(37,73,118,.064),inset 0 1px 0 rgba(255,255,255,.76)}",
  ".view{transition:color .15s ease,transform .15s ease,background .15s ease}",
  ".view:hover{color:#0e5ec4;transform:translateX(1px)}",
  "",
  ".prov{transition:transform .16s ease,border-color .16s ease,box-shadow .16s ease,background .16s ease;cursor:pointer}",
  ".prov:hover{transform:translateY(-2px);border-color:#cfddec;background:#fff;box-shadow:0 7px 17px rgba(31,73,121,.06)}",
  ".prov:hover .parrow{transform:translateX(2px)}",
  ".parrow{transition:transform .16s ease}",
  "",
  ".hrow,.arow{transition:background .14s ease,color .14s ease}",
  ".hrow:hover,.arow:hover{background:#f8fbff}",
  ".hrow:hover .hcomp,.arow:hover .aevent b{color:#0d4c9e}",
  "",
  ".action{",
  "  position:relative;overflow:hidden;",
  "  transition:transform .14s ease,border-color .14s ease,box-shadow .14s ease,background .14s ease;",
  "}",
  ".action:hover{transform:translateY(-1px);border-color:#ceddec;background:#fbfdff;box-shadow:0 6px 14px rgba(33,73,119,.05)}",
  ".action:active{transform:translateY(0)}",
  ".action.is-busy{pointer-events:none;color:#6a80ad}",
  ".action.is-busy:after{",
  "  content:\"\";position:absolute;right:8px;width:12px;height:12px;border-radius:50%;",
  "  border:1.5px solid #b8cce7;border-top-color:#2d7ce4;animation:dashSpin .7s linear infinite;",
  "}",
  ".action.is-success{border-color:#a9dbc8;background:#f6fcf9}",
  "@keyframes dashSpin{to{transform:rotate(360deg)}}",
  "",
  "/* Professional toast feedback */",
  ".toast{",
  "  min-width:235px;max-width:330px;padding:10px 12px;border-radius:10px;",
  "  background:rgba(255,255,255,.96);border:1px solid #dbe6f2;",
  "  box-shadow:0 12px 30px rgba(26,62,108,.13);backdrop-filter:blur(10px);",
  "  font-size:8.6px;line-height:1.35;color:#31568f;",
  "  opacity:0;transform:translateY(-7px) scale(.985);",
  "  transition:opacity .18s ease,transform .18s ease,border-color .18s ease;",
  "}",
  ".toast.show{opacity:1;transform:translateY(0) scale(1)}",
  ".toast.success{border-left:3px solid #16b777;color:#14784f}",
  ".toast.error{border-left:3px solid #d75d6a;color:#b34f5d}",
  ".toast.info{border-left:3px solid #3a9fe8;color:#315f96}",
  ".toast strong{display:block;color:#153d7f;font-size:9px;margin-bottom:2px}",
  "",
  "/* Command palette \u2014 local-only search/navigation feedback */",
  ".command-backdrop{",
  "  position:absolute;inset:0;z-index:40;background:rgba(8,27,61,.12);backdrop-filter:blur(3px);",
  "  opacity:0;pointer-events:none;transition:opacity .16s ease;",
  "}",
  ".command-backdrop.open{opacity:1;pointer-events:auto}",
  ".command-palette{",
  "  position:absolute;left:50%;top:88px;width:560px;z-index:41;",
  "  transform:translate(-50%,-8px) scale(.985);opacity:0;pointer-events:none;",
  "  background:rgba(255,255,255,.985);border:1px solid #d8e4f2;border-radius:14px;",
  "  box-shadow:0 26px 70px rgba(22,56,103,.22);overflow:hidden;",
  "  transition:opacity .16s ease,transform .16s ease;",
  "}",
  ".command-palette.open{opacity:1;transform:translate(-50%,0) scale(1);pointer-events:auto}",
  ".command-search{",
  "  height:48px;border-bottom:1px solid #e6edf6;display:flex;align-items:center;gap:10px;padding:0 14px",
  "}",
  ".command-search svg{width:18px;height:18px;stroke:#315e9f;fill:none;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}",
  ".command-search input{flex:1;border:0;outline:0;background:transparent;color:#173c79;font-size:11px}",
  ".command-esc{font-size:8px;color:#7187b3;border:1px solid #dbe5f1;border-radius:5px;padding:3px 6px;background:#f8fbff}",
  ".command-results{max-height:320px;padding:7px}",
  ".command-group-label{padding:7px 9px 5px;color:#8296bd;font-size:7.4px;text-transform:uppercase;letter-spacing:1px;font-weight:700}",
  ".command-item{",
  "  height:41px;border-radius:8px;display:grid;grid-template-columns:31px 1fr auto;align-items:center;gap:9px;padding:0 9px;",
  "  color:#183b79;cursor:pointer;border:1px solid transparent",
  "}",
  ".command-item:hover,.command-item.active{background:#f3f8fe;border-color:#e1eaf5}",
  ".command-item .ci{width:28px;height:28px;border-radius:7px;background:#edf5ff;color:#176fdf;display:grid;place-items:center}",
  ".command-item .ci svg{width:16px;height:16px;stroke:currentColor;fill:none;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}",
  ".command-item b{display:block;font-size:9.3px;color:#153d7f}.command-item small{display:block;margin-top:1px;font-size:7.2px;color:#7589b3}",
  ".command-item .hint{font-size:7.2px;color:#8ca0c2}",
  ".command-empty{padding:24px;text-align:center;color:#8496ba;font-size:9px}",
  "",
  "/* Local UI busy/skeleton hook for future admin integration */",
  ".app.is-refreshing .metric,.app.is-refreshing .panel{pointer-events:none}",
  ".app.is-refreshing .metric:after,.app.is-refreshing .panel:after{",
  "  content:\"\";position:absolute;inset:0;z-index:9;pointer-events:none;",
  "  background:linear-gradient(105deg,transparent 30%,rgba(235,244,252,.72) 47%,transparent 64%);",
  "  animation:dashSkeleton 1.1s ease-in-out infinite;",
  "}",
  "@keyframes dashSkeleton{from{transform:translateX(-90%)}to{transform:translateX(90%)}}",
  "",
  "/* Initial reveal */",
  ".app:not(.ui-ready) .metric,.app:not(.ui-ready) .panel{opacity:0;transform:translateY(5px)}",
  ".app.ui-ready .metric,.app.ui-ready .panel{opacity:1}",
  ".metric:nth-child(1){transition-delay:20ms}.metric:nth-child(2){transition-delay:45ms}.metric:nth-child(3){transition-delay:70ms}.metric:nth-child(4){transition-delay:95ms}",
  "",
  "@media(prefers-reduced-motion:reduce){",
  "  *,*:before,*:after{animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important}",
  "}",
  "",
  "",
  "/* Providers page \u2014 inspired by the reference while preserving DreamWorker frame */",
  ".providers-page{",
  "  background:",
  "    radial-gradient(500px 170px at 71% 0%,rgba(68,188,228,.08),transparent 68%),",
  "    linear-gradient(180deg,#fbfdff,#f8fbff);",
  "}",
  ".providers-hero{position:absolute;left:26px;top:20px;width:1110px;height:132px}",
  ".providers-eyebrow{font-size:8.4px;color:#2e5da1;margin-bottom:8px}",
  ".providers-hero h1{",
  "  margin:0;font-family:\"SF Pro Display\",\"Segoe UI Variable Display\",\"Inter\",\"Segoe UI\",sans-serif;",
  "  font-size:32px;line-height:1;font-weight:810;letter-spacing:-1.05px;color:#08123e",
  "}",
  ".providers-hero p{margin:9px 0 0;font-size:12.4px;color:#536ea8}",
  ".providers-hero-wave{position:absolute;right:110px;top:-8px;width:470px;height:120px;filter:drop-shadow(0 8px 18px rgba(37,155,207,.04))}",
  ".providers-quote{",
  "  position:absolute;right:0;top:13px;width:125px;color:#31579a;font-size:8.8px;line-height:1.25",
  "}",
  ".quote-dot{display:block;color:#82b4f2;font-size:12px;margin-bottom:3px}",
  ".quote-line{display:inline-block;width:20px;height:1px;background:#1875e7;vertical-align:middle;margin-right:6px}",
  ".providers-quote strong{font-size:8px;color:#0d5ddc;font-weight:700}",
  "",
  ".provider-metrics{",
  "  position:absolute;left:26px;top:139px;width:1110px;height:92px;",
  "  display:grid;grid-template-columns:repeat(4,1fr);gap:11px",
  "}",
  ".provider-metric{position:relative;height:92px;padding:13px 12px}",
  ".pm-icon{",
  "  position:absolute;left:13px;top:13px;width:48px;height:48px;border-radius:10px;",
  "  display:grid;place-items:center;color:#176fe6;background:#eef5ff",
  "}",
  ".pm-icon.green{color:#0ba968;background:#e9fbf3}",
  ".pm-icon svg{width:28px;height:28px}",
  ".pm-copy{position:absolute;left:78px;top:13px}",
  ".pm-copy span{display:block;font-size:8.8px;color:#1e4380;font-weight:650}",
  ".pm-copy strong{display:block;margin-top:6px;font-size:20px;line-height:1;color:#0a1745;font-weight:800;letter-spacing:-.45px}",
  ".pm-copy small{display:block;margin-top:7px;font-size:8px;color:#6a80af}",
  ".pm-trend{",
  "  position:absolute;right:14px;top:36px;height:24px;padding:0 8px;border-radius:12px;",
  "  display:flex;align-items:center;font-size:8px;font-weight:650",
  "}",
  ".pm-trend.good{background:#e9faf2;color:#0a9a5e}",
  "",
  ".providers-workspace{",
  "  position:absolute;left:26px;top:244px;width:1110px;height:441px;border-radius:11px;overflow:hidden",
  "}",
  ".provider-toolbar{",
  "  height:61px;border-bottom:1px solid #e8eef6;display:flex;align-items:center;padding:0 13px;gap:12px",
  "}",
  ".provider-search{",
  "  width:470px;height:36px;border:1px solid #d8e4f1;border-radius:8px;background:#fbfdff;",
  "  display:flex;align-items:center;gap:9px;padding:0 11px;color:#315d9d;",
  "  transition:border-color .16s ease,box-shadow .16s ease,background .16s ease",
  "}",
  ".provider-search:focus-within{border-color:#9dbfe9;background:#fff;box-shadow:0 0 0 3px rgba(50,118,216,.065)}",
  ".provider-search svg{width:17px;height:17px}",
  ".provider-search input{border:0;outline:0;background:transparent;flex:1;font-size:9.5px;color:#315589}",
  ".provider-search input::placeholder{color:#6f85b1}",
  ".provider-toolbar-right{margin-left:auto;display:flex;align-items:center;gap:9px}",
  ".toolbar-select{",
  "  height:36px;min-width:130px;padding:0 11px;border:1px solid #d8e4f1;border-radius:8px;background:#fff;",
  "  color:#153b79;font-size:8.5px;display:flex;align-items:center;justify-content:space-between;gap:9px;",
  "  transition:border-color .15s ease,box-shadow .15s ease,transform .15s ease",
  "}",
  ".toolbar-select:hover{border-color:#c7d8eb;transform:translateY(-1px)}",
  ".toolbar-select svg{width:14px;height:14px}",
  ".view-toggle{height:36px;border:1px solid #d8e4f1;border-radius:8px;background:#fff;display:flex;overflow:hidden}",
  ".view-toggle-btn{width:38px;border:0;background:#fff;color:#5673aa;display:grid;place-items:center}",
  ".view-toggle-btn+ .view-toggle-btn{border-left:1px solid #e4ebf4}",
  ".view-toggle-btn.active{background:#f1f7fe;color:#126edf}",
  ".view-toggle-btn svg{width:16px;height:16px}",
  ".add-provider-btn{",
  "  height:36px;padding:0 15px;border:0;border-radius:8px;color:#fff;",
  "  background:linear-gradient(90deg,#18b887,#1596d8);box-shadow:0 8px 18px rgba(28,149,185,.15);",
  "  display:flex;align-items:center;gap:8px;font-size:8.8px;font-weight:650;",
  "  transition:transform .15s ease,box-shadow .15s ease,filter .15s ease",
  "}",
  ".add-provider-btn:hover{transform:translateY(-1px);box-shadow:0 11px 22px rgba(28,149,185,.18);filter:saturate(1.04)}",
  ".add-provider-btn svg{width:16px;height:16px}",
  "",
  ".provider-table-shell{position:absolute;left:11px;right:11px;top:72px;bottom:50px}",
  ".provider-table-head{",
  "  height:30px;border-radius:7px 7px 0 0;background:#f2f6fb;color:#42649a;",
  "  display:grid;grid-template-columns:2.1fr 1.35fr .9fr 1.05fr .85fr 1.2fr 1.05fr .55fr;",
  "  align-items:center;padding:0 13px;font-size:7.2px;font-weight:650",
  "}",
  ".provider-table-body{display:flex;flex-direction:column;gap:7px;padding-top:7px}",
  ".provider-row{",
  "  min-height:48px;border:1px solid #e1e9f4;border-radius:8px;background:#fff;",
  "  display:grid;grid-template-columns:2.1fr 1.35fr .9fr 1.05fr .85fr 1.2fr 1.05fr .55fr;",
  "  align-items:center;padding:0 13px;",
  "  box-shadow:0 4px 11px rgba(42,75,113,.025);",
  "  transition:transform .14s ease,border-color .14s ease,box-shadow .14s ease,background .14s ease",
  "}",
  ".provider-row:hover{transform:translateY(-1px);border-color:#cfddec;box-shadow:0 7px 15px rgba(42,75,113,.045)}",
  ".provider-cell{font-size:7.8px;color:#173d7c}",
  ".provider-ident{display:flex;align-items:center;gap:11px}",
  ".provider-ident strong{display:block;color:#0d1948;font-size:8.8px}",
  ".provider-ident small{display:block;margin-top:3px;color:#6d82b1;font-size:7px}",
  ".provider-logo{width:34px;height:34px;border-radius:8px;display:grid;place-items:center;flex:none;background:#fff}",
  ".provider-logo.google{box-shadow:inset 0 0 0 1px #eef2f7}.provider-logo.google svg{width:27px;height:27px}",
  ".provider-logo.anthropic{background:#efe0d5;color:#171312;font-size:15px;font-weight:850}",
  ".provider-logo.openai{box-shadow:inset 0 0 0 1px #edf1f6}.provider-logo.openai svg{width:28px;height:28px}",
  ".provider-logo.azure{background:#eef8ff}.provider-logo.azure span{font-size:18px;font-weight:900;color:#1682dc}",
  ".provider-logo.mistral{background:linear-gradient(180deg,#ffdf38,#ff8148);color:#111;font-size:16px;font-weight:900}",
  ".provider-logo.cohere{display:flex;gap:2px;align-items:center;justify-content:center}",
  ".provider-logo.cohere span{display:block;border-radius:50%}.provider-logo.cohere span:nth-child(1){width:16px;height:10px;background:#315c5a}.provider-logo.cohere span:nth-child(2){width:10px;height:10px;background:#ff8064}.provider-logo.cohere span:nth-child(3){width:14px;height:14px;background:#9f7ac7}",
  ".status-pill{",
  "  width:max-content;height:24px;padding:0 9px;border-radius:13px;display:flex;align-items:center;gap:6px;font-size:7.5px;font-weight:650",
  "}",
  ".status-pill i{width:6px;height:6px;border-radius:50%}",
  ".status-pill.healthy{background:#e8faf2;color:#078b56}.status-pill.healthy i{background:#10ad69}",
  ".status-pill.degraded{background:#eaf3ff;color:#1768d8}.status-pill.degraded i{background:#2b7ce8}",
  ".status-pill.disabled{background:#eef2f7;color:#60779f}.status-pill.disabled i{background:#91a4c0}",
  ".muted-cell{color:#637eaf}.strong-cell{color:#0e1c4f;font-weight:650}",
  ".trend-cell svg{width:105px;height:28px;display:block}",
  ".last-check{display:flex;align-items:center;gap:6px;color:#6e83b2}.last-check i{width:6px;height:6px;border-radius:50%;background:#12ae69}",
  ".row-action{width:26px;height:26px;border:0;background:transparent;color:#1f5bb0;font-weight:800;letter-spacing:1px;border-radius:6px}",
  ".row-action:hover{background:#f1f6fd}",
  ".disabled-row{opacity:.72;background:#fcfdff}",
  "",
  ".provider-footer{",
  "  position:absolute;left:0;right:0;bottom:0;height:49px;border-top:1px solid #e8eef6;",
  "  display:flex;align-items:center;justify-content:space-between;padding:0 14px;color:#6b82b3;font-size:7.5px",
  "}",
  ".provider-pagination{display:flex;align-items:center;gap:7px}",
  ".page-btn{",
  "  width:32px;height:31px;border:1px solid #dbe5f2;border-radius:8px;background:#fff;color:#48669a;display:grid;place-items:center;font-size:8px",
  "}",
  ".page-btn svg{width:14px;height:14px}.page-btn.active{border-color:#3a82ef;color:#145ec9;box-shadow:0 0 0 2px rgba(58,130,239,.06)}.page-btn:disabled{opacity:.45}",
  "",
  ".providers-page .toast{top:18px;right:18px}",
  "@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation-duration:.001ms!important;transition-duration:.001ms!important}}",
  "",
  "</style>",
  "</head>",
  "<body>",
  "",
  "",
  "<svg width=\"0\" height=\"0\" aria-hidden=\"true\" style=\"position:absolute\">",
  "<defs>",
  "  <symbol id=\"i-home\" viewBox=\"0 0 24 24\">",
  "    <path d=\"M4.6 10.4 12 4.3l7.4 6.1v8.5H4.6Z\" fill=\"currentColor\" opacity=\".12\" stroke=\"none\"/>",
  "    <path d=\"M3.4 10.7 12 3.7l8.6 7\"/>",
  "    <path d=\"M5.4 9.9v9.7h13.2V9.9\"/>",
  "    <path d=\"M9.1 19.6v-5.4h5.8v5.4\"/>",
  "    <path d=\"M8.3 9.9h7.4\" opacity=\".55\"/>",
  "  </symbol>",
  "",
  "  <symbol id=\"i-db\" viewBox=\"0 0 24 24\">",
  "    <ellipse cx=\"12\" cy=\"5.2\" rx=\"7.2\" ry=\"3.15\" fill=\"currentColor\" opacity=\".12\" stroke=\"none\"/>",
  "    <path d=\"M4.8 5.2v6.1c0 1.9 3.2 3.3 7.2 3.3s7.2-1.4 7.2-3.3V5.2\"/>",
  "    <path d=\"M4.8 11.2v6c0 1.9 3.2 3.3 7.2 3.3s7.2-1.4 7.2-3.3v-6\"/>",
  "    <ellipse cx=\"12\" cy=\"5.2\" rx=\"7.2\" ry=\"3.15\"/>",
  "    <path d=\"M7.4 8.7c1.2.45 2.8.72 4.6.72s3.4-.27 4.6-.72\" opacity=\".55\"/>",
  "  </symbol>",
  "",
  "  <symbol id=\"i-cube\" viewBox=\"0 0 24 24\">",
  "    <path d=\"m12 3.3 8 4.5-8 4.5-8-4.5Z\" fill=\"currentColor\" opacity=\".13\" stroke=\"none\"/>",
  "    <path d=\"m12 3.3 8 4.5v8.7L12 21l-8-4.5V7.8Z\"/>",
  "    <path d=\"m4 7.8 8 4.5 8-4.5\"/>",
  "    <path d=\"M12 12.3V21\"/>",
  "    <path d=\"m8.1 5.5 8 4.5\" opacity=\".38\"/>",
  "  </symbol>",
  "",
  "  <symbol id=\"i-nodes\" viewBox=\"0 0 24 24\">",
  "    <circle cx=\"12\" cy=\"5\" r=\"3\" fill=\"currentColor\" opacity=\".13\" stroke=\"none\"/>",
  "    <circle cx=\"5\" cy=\"18\" r=\"3\" fill=\"currentColor\" opacity=\".13\" stroke=\"none\"/>",
  "    <circle cx=\"19\" cy=\"18\" r=\"3\" fill=\"currentColor\" opacity=\".13\" stroke=\"none\"/>",
  "    <circle cx=\"12\" cy=\"5\" r=\"2.5\"/>",
  "    <circle cx=\"5\" cy=\"18\" r=\"2.5\"/>",
  "    <circle cx=\"19\" cy=\"18\" r=\"2.5\"/>",
  "    <path d=\"M12 7.5v4.2M7.1 16l3.5-4.5M16.9 16l-3.5-4.5\"/>",
  "  </symbol>",
  "",
  "  <symbol id=\"i-route\" viewBox=\"0 0 24 24\">",
  "    <circle cx=\"6\" cy=\"12\" r=\"2.8\" fill=\"currentColor\" opacity=\".13\" stroke=\"none\"/>",
  "    <circle cx=\"18\" cy=\"6\" r=\"2.8\" fill=\"currentColor\" opacity=\".13\" stroke=\"none\"/>",
  "    <circle cx=\"18\" cy=\"18\" r=\"2.8\" fill=\"currentColor\" opacity=\".13\" stroke=\"none\"/>",
  "    <circle cx=\"6\" cy=\"12\" r=\"2.3\"/>",
  "    <circle cx=\"18\" cy=\"6\" r=\"2.3\"/>",
  "    <circle cx=\"18\" cy=\"18\" r=\"2.3\"/>",
  "    <path d=\"m8.2 10.9 7.5-3.7M8.2 13.1l7.5 3.7\"/>",
  "    <path d=\"m13.9 6.7 1.9.5-.5 1.9M13.9 17.3l1.9-.5-.5-1.9\" opacity=\".65\"/>",
  "  </symbol>",
  "",
  "  <symbol id=\"i-terminal\" viewBox=\"0 0 24 24\">",
  "    <rect x=\"3.2\" y=\"4\" width=\"17.6\" height=\"16\" rx=\"2.4\" fill=\"currentColor\" opacity=\".06\" stroke=\"none\"/>",
  "    <rect x=\"3.2\" y=\"4\" width=\"17.6\" height=\"16\" rx=\"2.4\"/>",
  "    <path d=\"M3.6 8h16.8\"/>",
  "    <circle cx=\"6.4\" cy=\"6.1\" r=\".65\" fill=\"currentColor\" stroke=\"none\"/>",
  "    <circle cx=\"8.7\" cy=\"6.1\" r=\".65\" fill=\"currentColor\" stroke=\"none\" opacity=\".7\"/>",
  "    <path d=\"m7.2 11.3 2.7 2.7-2.7 2.7M12.7 16.7h4\"/>",
  "  </symbol>",
  "",
  "  <symbol id=\"i-heart\" viewBox=\"0 0 24 24\">",
  "    <path d=\"M20.7 4.8a5.35 5.35 0 0 0-7.6 0L12 5.9l-1.1-1.1a5.35 5.35 0 0 0-7.6 7.6L12 21l8.7-8.6a5.35 5.35 0 0 0 0-7.6Z\" fill=\"currentColor\" opacity=\".08\" stroke=\"none\"/>",
  "    <path d=\"M20.7 4.8a5.35 5.35 0 0 0-7.6 0L12 5.9l-1.1-1.1a5.35 5.35 0 0 0-7.6 7.6L12 21l8.7-8.6a5.35 5.35 0 0 0 0-7.6Z\"/>",
  "    <path d=\"M4.8 12.1h4.1l1.45-3.1 3.1 6.1 1.45-3h4.25\"/>",
  "  </symbol>",
  "",
  "  <symbol id=\"i-bars\" viewBox=\"0 0 24 24\">",
  "    <rect x=\"4.2\" y=\"11\" width=\"2.8\" height=\"8.5\" rx=\"1.2\" fill=\"currentColor\" opacity=\".13\" stroke=\"none\"/>",
  "    <rect x=\"10.6\" y=\"5\" width=\"2.8\" height=\"14.5\" rx=\"1.2\" fill=\"currentColor\" opacity=\".13\" stroke=\"none\"/>",
  "    <rect x=\"17\" y=\"8\" width=\"2.8\" height=\"11.5\" rx=\"1.2\" fill=\"currentColor\" opacity=\".13\" stroke=\"none\"/>",
  "    <path d=\"M5.6 19.5V11M12 19.5V5M18.4 19.5V8\"/>",
  "  </symbol>",
  "",
  "  <symbol id=\"i-doc\" viewBox=\"0 0 24 24\">",
  "    <path d=\"M6 3.2h9l4 4v13.6H6Z\" fill=\"currentColor\" opacity=\".06\" stroke=\"none\"/>",
  "    <path d=\"M6 3.2h9l4 4v13.6H6Z\"/>",
  "    <path d=\"M15 3.2v5h5\"/>",
  "    <path d=\"M9 12h7M9 15.7h7M9 8.5h2.5\"/>",
  "  </symbol>",
  "",
  "  <symbol id=\"i-gear\" viewBox=\"0 0 24 24\">",
  "    <circle cx=\"12\" cy=\"12\" r=\"3.05\" fill=\"currentColor\" opacity=\".12\" stroke=\"none\"/>",
  "    <circle cx=\"12\" cy=\"12\" r=\"3.05\"/>",
  "    <path d=\"M19.3 15.2a7.8 7.8 0 0 0 .2-1.25l2-1.5-2-3.45-2.4 1a7.4 7.4 0 0 0-2.1-1.8l-.35-3H9.35l-.35 3A7.4 7.4 0 0 0 6.9 10l-2.4-1-2 3.45 2 1.5a7.8 7.8 0 0 0 .2 1.25l-2 1.5 2 3.45 2.4-1A7.4 7.4 0 0 0 9 21l.35 3h5.3L15 21a7.4 7.4 0 0 0 2.1-1.8l2.4 1 2-3.45-2.2-1.55Z\" transform=\"scale(.88) translate(1.64 1.64)\"/>",
  "  </symbol>",
  "",
  "  <symbol id=\"i-search\" viewBox=\"0 0 24 24\">",
  "    <circle cx=\"10.8\" cy=\"10.8\" r=\"6.6\"/>",
  "    <path d=\"m15.7 15.7 4.3 4.3\"/>",
  "    <path d=\"M8.6 8.6c.7-.7 1.5-1 2.4-1\" opacity=\".45\"/>",
  "  </symbol>",
  "",
  "  <symbol id=\"i-sun\" viewBox=\"0 0 24 24\">",
  "    <circle cx=\"12\" cy=\"12\" r=\"4.2\" fill=\"currentColor\" opacity=\".10\" stroke=\"none\"/>",
  "    <circle cx=\"12\" cy=\"12\" r=\"4.2\"/>",
  "    <path d=\"M12 2v2.1M12 19.9V22M4.9 4.9l1.5 1.5M17.6 17.6l1.5 1.5M2 12h2.1M19.9 12H22M4.9 19.1l1.5-1.5M17.6 6.4l1.5-1.5\"/>",
  "  </symbol>",
  "",
  "  <symbol id=\"i-bell\" viewBox=\"0 0 24 24\">",
  "    <path d=\"M18 8.6a6 6 0 1 0-12 0c0 6.6-2.8 6.8-3 8.8h18c-.2-2-3-2.2-3-8.8Z\" fill=\"currentColor\" opacity=\".07\" stroke=\"none\"/>",
  "    <path d=\"M18 8.6a6 6 0 1 0-12 0c0 6.6-2.8 6.8-3 8.8h18c-.2-2-3-2.2-3-8.8Z\"/>",
  "    <path d=\"M9.8 20.1a2.5 2.5 0 0 0 4.4 0\"/>",
  "  </symbol>",
  "",
  "  <symbol id=\"i-check\" viewBox=\"0 0 24 24\">",
  "    <circle cx=\"12\" cy=\"12\" r=\"8.2\" fill=\"currentColor\" opacity=\".11\" stroke=\"none\"/>",
  "    <circle cx=\"12\" cy=\"12\" r=\"8.2\"/>",
  "    <path d=\"m8.5 12 2.3 2.4 4.8-5.3\"/>",
  "  </symbol>",
  "",
  "  <symbol id=\"i-chevron\" viewBox=\"0 0 24 24\">",
  "    <path d=\"m9 5.5 6.5 6.5L9 18.5\"/>",
  "  </symbol>",
  "",
  "  <symbol id=\"i-arrow\" viewBox=\"0 0 24 24\">",
  "    <path d=\"M4.5 12h14\"/>",
  "    <path d=\"m14 7.2 4.8 4.8-4.8 4.8\"/>",
  "  </symbol>",
  "",
  "  <symbol id=\"i-bolt\" viewBox=\"0 0 24 24\">",
  "    <path d=\"m13.2 2.4-7.1 11.9H12l-1 7.3 7-11.8h-5.8Z\" fill=\"currentColor\" opacity=\".12\" stroke=\"none\"/>",
  "    <path d=\"m13.2 2.4-7.1 11.9H12l-1 7.3 7-11.8h-5.8Z\"/>",
  "  </symbol>",
  "",
  "  <symbol id=\"i-shield\" viewBox=\"0 0 24 24\">",
  "    <path d=\"M12 3.2 19 6v5.1c0 4.6-2.8 7.9-7 9.9-4.2-2-7-5.3-7-9.9V6Z\" fill=\"currentColor\" opacity=\".08\" stroke=\"none\"/>",
  "    <path d=\"M12 3.2 19 6v5.1c0 4.6-2.8 7.9-7 9.9-4.2-2-7-5.3-7-9.9V6Z\"/>",
  "    <path d=\"m9 12.1 2 2 4.2-4.4\"/>",
  "  </symbol>",
  "</defs>",
  "</svg>",
  "",
  "",
  "<div class=\"viewport\">",
  "  <div class=\"app\">",
  "    <aside class=\"sidebar\">",
  "      <div class=\"brand brand-exact\" aria-label=\"DreamWorker MCP Control Plane\">",
  "        <div class=\"brand-mark-shell\">",
  "          <img class=\"brand-mark-img\" src=\"data:image/png;base64,",
].join("\n") +
  DW_CONSOLE_LOGO_B64 +
  [
  "\" alt=\"\">",
  "        </div>",
  "        <div class=\"brand-wordmark\">DreamWorker</div>",
  "        <div class=\"brand-subtitle\">MCP Control Plane</div>",
  "      </div>",
  "",
  "      <nav class=\"nav\">",
  "        <a class=\"nav-item active\" data-nav=\"overview\"><span class=\"ni\"><svg class=\"icon\"><use href=\"#i-home\"/></svg></span>Overview</a>",
  "        <a class=\"nav-item\" data-nav=\"providers\"><span class=\"ni\"><svg class=\"icon\"><use href=\"#i-db\"/></svg></span>Providers</a>",
  "        <a class=\"nav-item\" data-nav=\"models\"><span class=\"ni\"><svg class=\"icon\"><use href=\"#i-cube\"/></svg></span>Models</a>",
  "        <a class=\"nav-item\" data-nav=\"mcp-tools\"><span class=\"ni\"><svg class=\"icon\"><use href=\"#i-nodes\"/></svg></span>MCP Tools</a>",
  "        <a class=\"nav-item\" data-nav=\"routing\"><span class=\"ni\"><svg class=\"icon\"><use href=\"#i-route\"/></svg></span>Routing</a>",
  "        <a class=\"nav-item\" data-nav=\"health\"><span class=\"ni\"><svg class=\"icon\"><use href=\"#i-heart\"/></svg></span>Health</a>",
  "        <a class=\"nav-item\" data-nav=\"usage\"><span class=\"ni\"><svg class=\"icon\"><use href=\"#i-bars\"/></svg></span>Usage</a>",
  "        <a class=\"nav-item\" data-nav=\"audit\"><span class=\"ni\"><svg class=\"icon\"><use href=\"#i-doc\"/></svg></span>Audit Log</a>",
  "        <a class=\"nav-item\" data-nav=\"settings\"><span class=\"ni\"><svg class=\"icon\"><use href=\"#i-gear\"/></svg></span>Settings</a>",
  "      </nav>",
  "",
  "      <div class=\"side-foot\">",
  "        <b>DreamWorker</b>",
  "        <span>The future is created today.</span>",
  "        <span class=\"version\">v1.8.0</span>",
  "      </div>",
  "    </aside>",
  "",
  "    <header class=\"header\">",
  "      <label class=\"search\">",
  "        <span class=\"si\"><svg class=\"icon\"><use href=\"#i-search\"/></svg></span>",
  "        <input id=\"dashboard-search\" placeholder=\"Search providers, models, tools...\">",
  "        <span class=\"kbd\">Ctrl K</span>",
  "      </label>",
  "",
  "      <div class=\"head-right\">",
  "        <div class=\"prod\"><span class=\"pc\"><svg class=\"icon\"><use href=\"#i-check\"/></svg></span>Production",
  "          <span style=\"width:13px;height:13px\"><svg class=\"icon\"><path d=\"m8 10 4 4 4-4\"/></svg></span>",
  "        </div>",
  "        <div class=\"hicon\"><span class=\"hi\"><svg class=\"icon\"><use href=\"#i-sun\"/></svg></span></div>",
  "        <div class=\"hicon\"><span class=\"hi\"><svg class=\"icon\"><use href=\"#i-bell\"/></svg></span><span class=\"badge\">3</span></div>",
  "        <div class=\"headuser\">",
  "          <div class=\"avatar\">A</div>",
  "          <div><b>Admin</b><small>admin@dreamworker.ai</small></div>",
  "          <span class=\"chev\"><svg class=\"icon\"><path d=\"m8 10 4 4 4-4\"/></svg></span>",
  "        </div>",
  "      </div>",
  "    </header>",
  "",
  "    ",
  "<main class=\"main providers-page\">",
  "  <section class=\"providers-hero\">",
  "    <div class=\"providers-eyebrow\">Providers</div>",
  "    <h1>Providers</h1>",
  "    <p>Manage AI providers and review their status, performance, and availability.</p>",
  "",
  "    <svg class=\"providers-hero-wave\" viewBox=\"0 0 560 130\" preserveAspectRatio=\"none\" aria-hidden=\"true\">",
  "      <defs>",
  "        <linearGradient id=\"phb1\" x1=\"0\" x2=\"1\"><stop stop-color=\"#dceeff\" stop-opacity=\".03\"/><stop offset=\".48\" stop-color=\"#479df3\" stop-opacity=\".52\"/><stop offset=\"1\" stop-color=\"#98e8d7\" stop-opacity=\".08\"/></linearGradient>",
  "        <linearGradient id=\"phm1\" x1=\"0\" x2=\"1\"><stop stop-color=\"#effffb\" stop-opacity=\".02\"/><stop offset=\".52\" stop-color=\"#37d0b2\" stop-opacity=\".44\"/><stop offset=\"1\" stop-color=\"#6fd7ea\" stop-opacity=\".06\"/></linearGradient>",
  "      </defs>",
  "      <path d=\"M0 108C78 104 126 68 168 72c48 4 63 54 106 20 48-38 75-82 119-55 40 24 52 70 91 52 35-17 48-37 76-39v80H0Z\" fill=\"url(#phb1)\"/>",
  "      <path d=\"M72 128c64-12 103-55 140-66 42-12 67 8 99 39 34 32 63 30 93 2 35-32 69-39 156-4v31H72Z\" fill=\"url(#phm1)\"/>",
  "      <path d=\"M55 115c65-9 99-53 141-59 47-7 67 48 107 17 44-34 67-68 107-44 42 26 53 66 91 47 22-11 35-17 59-18\" fill=\"none\" stroke=\"#2c99ec\" stroke-width=\"1.5\"/>",
  "      <path d=\"M121 127c59-15 92-50 129-65 39-16 61-1 92 29 31 30 58 28 89 2 30-26 61-32 121 1\" fill=\"none\" stroke=\"#2ac6a4\" stroke-width=\"1.4\"/>",
  "    </svg>",
  "",
  "    <div class=\"providers-quote\">",
  "      <span class=\"quote-dot\">\u25cf</span>",
  "      <div>A more capable<br>tomorrow, built with<br>open tools.</div>",
  "      <span class=\"quote-line\"></span>",
  "      <strong>DreamWorker</strong>",
  "    </div>",
  "  </section>",
  "",
  "  <section class=\"provider-metrics\">",
  "    <article class=\"provider-metric card\">",
  "      <div class=\"pm-icon blue\"><svg class=\"icon\"><use href=\"#i-db\"/></svg></div>",
  "      <div class=\"pm-copy\"><span>Total Providers</span><strong>6</strong><small>Active and configured</small></div>",
  "      <div class=\"pm-trend good\">\u2191 0</div>",
  "    </article>",
  "    <article class=\"provider-metric card\">",
  "      <div class=\"pm-icon green\"><svg class=\"icon\"><use href=\"#i-cube\"/></svg></div>",
  "      <div class=\"pm-copy\"><span>Available Models</span><strong>12</strong><small>Across all providers</small></div>",
  "      <div class=\"pm-trend good\">\u2191 2</div>",
  "    </article>",
  "    <article class=\"provider-metric card\">",
  "      <div class=\"pm-icon blue\"><svg class=\"icon\"><use href=\"#i-bolt\"/></svg></div>",
  "      <div class=\"pm-copy\"><span>Avg Latency</span><strong>412 ms</strong><small>Last 24 hours</small></div>",
  "      <div class=\"pm-trend good\">\u2193 8%</div>",
  "    </article>",
  "    <article class=\"provider-metric card\">",
  "      <div class=\"pm-icon blue\"><svg class=\"icon\"><use href=\"#i-bars\"/></svg></div>",
  "      <div class=\"pm-copy\"><span>Uptime (Avg)</span><strong>99.8%</strong><small>Across all providers</small></div>",
  "      <div class=\"pm-trend good\">\u2191 0.2%</div>",
  "    </article>",
  "  </section>",
  "",
  "  <section class=\"providers-workspace card\">",
  "    <div class=\"provider-toolbar\">",
  "      <label class=\"provider-search\">",
  "        <svg class=\"icon\"><use href=\"#i-search\"/></svg>",
  "        <input id=\"provider-search-input\" placeholder=\"Search providers...\" autocomplete=\"off\">",
  "      </label>",
  "",
  "      <div class=\"provider-toolbar-right\">",
  "        <button class=\"toolbar-select\" data-provider-filter=\"status\">All Status",
  "          <svg class=\"icon\"><path d=\"m8 10 4 4 4-4\"/></svg>",
  "        </button>",
  "        <button class=\"toolbar-select\" data-provider-filter=\"sort\">Sort by: Name",
  "          <svg class=\"icon\"><path d=\"m8 10 4 4 4-4\"/></svg>",
  "        </button>",
  "        <div class=\"view-toggle\">",
  "          <button class=\"view-toggle-btn active\" data-view=\"list\" aria-label=\"List view\">",
  "            <svg class=\"icon\"><path d=\"M8 7h11M8 12h11M8 17h11\"/><circle cx=\"4.5\" cy=\"7\" r=\".8\"/><circle cx=\"4.5\" cy=\"12\" r=\".8\"/><circle cx=\"4.5\" cy=\"17\" r=\".8\"/></svg>",
  "          </button>",
  "          <button class=\"view-toggle-btn\" data-view=\"grid\" aria-label=\"Grid view\">",
  "            <svg class=\"icon\"><rect x=\"4\" y=\"4\" width=\"6\" height=\"6\" rx=\"1\"/><rect x=\"14\" y=\"4\" width=\"6\" height=\"6\" rx=\"1\"/><rect x=\"4\" y=\"14\" width=\"6\" height=\"6\" rx=\"1\"/><rect x=\"14\" y=\"14\" width=\"6\" height=\"6\" rx=\"1\"/></svg>",
  "          </button>",
  "        </div>",
  "        <button id=\"add-provider-btn\" class=\"add-provider-btn\">",
  "          <svg class=\"icon\"><path d=\"M12 5v14M5 12h14\"/></svg>",
  "          Add Provider",
  "        </button>",
  "      </div>",
  "    </div>",
  "",
  "    <div class=\"provider-table-shell\">",
  "      <div class=\"provider-table-head\">",
  "        <div>Provider</div><div>Status</div><div>Models</div><div>Avg Latency</div><div>Uptime</div><div>Trend (24h)</div><div>Last Check</div><div>Actions</div>",
  "      </div>",
  "",
  "      <div id=\"provider-table-body\" class=\"provider-table-body\">",
  "        <div class=\"provider-row\" data-provider-name=\"Google AI Studio\" data-provider-status=\"healthy\">",
  "          <div class=\"provider-cell provider-ident\">",
  "            <div class=\"provider-logo google\">",
  "              <svg viewBox=\"0 0 24 24\"><path fill=\"#4285F4\" d=\"M21.6 12.2c0-.7-.1-1.4-.2-2H12v3.8h5.4a4.6 4.6 0 0 1-2 3l3.2 2.5c1.9-1.7 3-4.3 3-7.3Z\"/><path fill=\"#34A853\" d=\"M12 22c2.7 0 5-.9 6.6-2.4l-3.2-2.5c-.9.6-2 .9-3.4.9-2.6 0-4.8-1.7-5.6-4l-3.3 2.5A10 10 0 0 0 12 22Z\"/><path fill=\"#FBBC05\" d=\"M6.4 14a6 6 0 0 1 0-4L3.1 7.5a10 10 0 0 0 0 9L6.4 14Z\"/><path fill=\"#EA4335\" d=\"M12 6c1.5 0 2.8.5 3.8 1.5l2.8-2.8A9.4 9.4 0 0 0 3.1 7.5L6.4 10C7.2 7.7 9.4 6 12 6Z\"/></svg>",
  "            </div>",
  "            <div><strong>Google AI Studio</strong><small>google</small></div>",
  "          </div>",
  "          <div class=\"provider-cell\"><span class=\"status-pill healthy\"><i></i>Healthy</span></div>",
  "          <div class=\"provider-cell muted-cell\">4 models</div>",
  "          <div class=\"provider-cell strong-cell\">320 ms</div>",
  "          <div class=\"provider-cell strong-cell\">99.9%</div>",
  "          <div class=\"provider-cell trend-cell\">",
  "            <svg viewBox=\"0 0 120 32\"><defs><linearGradient id=\"tg\" x1=\"0\" y1=\"0\" x2=\"0\" y2=\"1\"><stop stop-color=\"#14b873\" stop-opacity=\".16\"/><stop offset=\"1\" stop-color=\"#14b873\" stop-opacity=\"0\"/></linearGradient></defs><path d=\"M0 22 10 18 20 20 30 17 40 20 50 15 60 14 70 8 80 11 90 10 100 8 110 13 120 14\" fill=\"none\" stroke=\"#10ad68\" stroke-width=\"1.6\"/><path d=\"M0 22 10 18 20 20 30 17 40 20 50 15 60 14 70 8 80 11 90 10 100 8 110 13 120 14V32H0Z\" fill=\"url(#tg)\"/></svg>",
  "          </div>",
  "          <div class=\"provider-cell last-check\"><i></i>2m ago</div>",
  "          <div class=\"provider-cell\"><button class=\"row-action\" aria-label=\"Provider actions\">\u2022\u2022\u2022</button></div>",
  "        </div>",
  "",
  "        <div class=\"provider-row\" data-provider-name=\"Anthropic\" data-provider-status=\"healthy\">",
  "          <div class=\"provider-cell provider-ident\">",
  "            <div class=\"provider-logo anthropic\">AI</div>",
  "            <div><strong>Anthropic</strong><small>anthropic</small></div>",
  "          </div>",
  "          <div class=\"provider-cell\"><span class=\"status-pill healthy\"><i></i>Healthy</span></div>",
  "          <div class=\"provider-cell muted-cell\">2 models</div>",
  "          <div class=\"provider-cell strong-cell\">365 ms</div>",
  "          <div class=\"provider-cell strong-cell\">99.9%</div>",
  "          <div class=\"provider-cell trend-cell\"><svg viewBox=\"0 0 120 32\"><path d=\"M0 20 10 17 20 20 30 19 40 14 50 16 60 13 70 16 80 12 90 7 100 10 110 10 120 12\" fill=\"none\" stroke=\"#10ad68\" stroke-width=\"1.6\"/></svg></div>",
  "          <div class=\"provider-cell last-check\"><i></i>3m ago</div>",
  "          <div class=\"provider-cell\"><button class=\"row-action\">\u2022\u2022\u2022</button></div>",
  "        </div>",
  "",
  "        <div class=\"provider-row\" data-provider-name=\"OpenAI\" data-provider-status=\"healthy\">",
  "          <div class=\"provider-cell provider-ident\">",
  "            <div class=\"provider-logo openai\">",
  "              <svg viewBox=\"0 0 36 36\"><path d=\"M18 3.6a7 7 0 0 1 6.7 5 7 7 0 0 1 4 11.7 7 7 0 0 1-10.7 8.4 7 7 0 0 1-6.7-5 7 7 0 0 1-4-11.7A7 7 0 0 1 18 3.6Z\" fill=\"none\" stroke=\"#08123e\" stroke-width=\"2\"/><path d=\"m11.5 14.5 6.5-3.8 6.5 3.8v7.4L18 25.7l-6.5-3.8v-7.4Z\" fill=\"none\" stroke=\"#08123e\" stroke-width=\"1.7\"/></svg>",
  "            </div>",
  "            <div><strong>OpenAI</strong><small>openai</small></div>",
  "          </div>",
  "          <div class=\"provider-cell\"><span class=\"status-pill healthy\"><i></i>Healthy</span></div>",
  "          <div class=\"provider-cell muted-cell\">1 model</div>",
  "          <div class=\"provider-cell strong-cell\">410 ms</div>",
  "          <div class=\"provider-cell strong-cell\">99.8%</div>",
  "          <div class=\"provider-cell trend-cell\"><svg viewBox=\"0 0 120 32\"><path d=\"M0 23 10 18 20 19 30 17 40 21 50 15 60 14 70 12 80 7 90 10 100 9 110 12 120 12\" fill=\"none\" stroke=\"#10ad68\" stroke-width=\"1.6\"/></svg></div>",
  "          <div class=\"provider-cell last-check\"><i></i>2m ago</div>",
  "          <div class=\"provider-cell\"><button class=\"row-action\">\u2022\u2022\u2022</button></div>",
  "        </div>",
  "",
  "        <div class=\"provider-row\" data-provider-name=\"Azure OpenAI\" data-provider-status=\"degraded\">",
  "          <div class=\"provider-cell provider-ident\">",
  "            <div class=\"provider-logo azure\"><span>A</span></div>",
  "            <div><strong>Azure OpenAI</strong><small>azure</small></div>",
  "          </div>",
  "          <div class=\"provider-cell\"><span class=\"status-pill degraded\"><i></i>Degraded</span></div>",
  "          <div class=\"provider-cell muted-cell\">3 models</div>",
  "          <div class=\"provider-cell strong-cell\">620 ms</div>",
  "          <div class=\"provider-cell strong-cell\">98.7%</div>",
  "          <div class=\"provider-cell trend-cell\"><svg viewBox=\"0 0 120 32\"><path d=\"M0 24 10 14 20 10 30 16 40 13 50 20 60 19 70 23 80 19 90 21 100 18 110 21 120 21\" fill=\"none\" stroke=\"#287af0\" stroke-width=\"1.6\"/></svg></div>",
  "          <div class=\"provider-cell last-check\"><i></i>5m ago</div>",
  "          <div class=\"provider-cell\"><button class=\"row-action\">\u2022\u2022\u2022</button></div>",
  "        </div>",
  "",
  "        <div class=\"provider-row\" data-provider-name=\"Mistral AI\" data-provider-status=\"healthy\">",
  "          <div class=\"provider-cell provider-ident\">",
  "            <div class=\"provider-logo mistral\">M</div>",
  "            <div><strong>Mistral AI</strong><small>mistral</small></div>",
  "          </div>",
  "          <div class=\"provider-cell\"><span class=\"status-pill healthy\"><i></i>Healthy</span></div>",
  "          <div class=\"provider-cell muted-cell\">2 models</div>",
  "          <div class=\"provider-cell strong-cell\">380 ms</div>",
  "          <div class=\"provider-cell strong-cell\">99.6%</div>",
  "          <div class=\"provider-cell trend-cell\"><svg viewBox=\"0 0 120 32\"><path d=\"M0 23 10 17 20 18 30 13 40 17 50 15 60 10 70 5 80 10 90 12 100 10 110 15 120 16\" fill=\"none\" stroke=\"#10ad68\" stroke-width=\"1.6\"/></svg></div>",
  "          <div class=\"provider-cell last-check\"><i></i>4m ago</div>",
  "          <div class=\"provider-cell\"><button class=\"row-action\">\u2022\u2022\u2022</button></div>",
  "        </div>",
  "",
  "        <div class=\"provider-row disabled-row\" data-provider-name=\"Cohere\" data-provider-status=\"disabled\">",
  "          <div class=\"provider-cell provider-ident\">",
  "            <div class=\"provider-logo cohere\"><span></span><span></span><span></span></div>",
  "            <div><strong>Cohere</strong><small>cohere</small></div>",
  "          </div>",
  "          <div class=\"provider-cell\"><span class=\"status-pill disabled\"><i></i>Disabled</span></div>",
  "          <div class=\"provider-cell muted-cell\">0 models</div>",
  "          <div class=\"provider-cell muted-cell\">\u2014</div>",
  "          <div class=\"provider-cell muted-cell\">\u2014</div>",
  "          <div class=\"provider-cell trend-cell\"><svg viewBox=\"0 0 120 32\"><path d=\"M0 20h120\" fill=\"none\" stroke=\"#a7b4c8\" stroke-width=\"1.4\"/></svg></div>",
  "          <div class=\"provider-cell muted-cell\">\u2014</div>",
  "          <div class=\"provider-cell\"><button class=\"row-action\">\u2022\u2022\u2022</button></div>",
  "        </div>",
  "      </div>",
  "    </div>",
  "",
  "    <div class=\"provider-footer\">",
  "      <div id=\"provider-count\">Showing 1 to 6 of 6 providers</div>",
  "      <div class=\"provider-pagination\">",
  "        <button class=\"page-btn\" disabled><svg class=\"icon\"><path d=\"m15 6-6 6 6 6\"/></svg></button>",
  "        <button class=\"page-btn active\">1</button>",
  "        <button class=\"page-btn\" disabled><svg class=\"icon\"><path d=\"m9 6 6 6-6 6\"/></svg></button>",
  "      </div>",
  "    </div>",
  "  </section>",
  "",
  "  <div id=\"toast\" class=\"toast\" role=\"status\" aria-live=\"polite\">Preview action</div>",
  "</main>",
  "",
  "  </div>",
  "</div>",
  "",
  "<script>",
  "",
  "(function(){",
  "  const toast=document.getElementById('toast');",
  "  const search=document.getElementById('provider-search-input');",
  "  const rows=[...document.querySelectorAll('.provider-row')];",
  "  const count=document.getElementById('provider-count');",
  "  const addBtn=document.getElementById('add-provider-btn');",
  "",
  "  function emit(name,detail){window.dispatchEvent(new CustomEvent(name,{detail}));}",
  "  function showToast(message,type='info',title='Providers'){",
  "    toast.innerHTML='<strong>'+title+'</strong>'+message;",
  "    toast.className='toast show '+type;",
  "    clearTimeout(window.__providerToast);",
  "    window.__providerToast=setTimeout(()=>toast.className='toast',1700);",
  "  }",
  "  function applySearch(){",
  "    const q=search.value.trim().toLowerCase();",
  "    let visible=0;",
  "    rows.forEach(row=>{",
  "      const match=row.dataset.providerName.toLowerCase().includes(q);",
  "      row.style.display=match?'grid':'none';",
  "      if(match)visible++;",
  "    });",
  "    count.textContent=q?('Showing '+visible+' matching providers'):('Showing 1 to '+rows.length+' of '+rows.length+' providers');",
  "  }",
  "",
  "  search.addEventListener('input',applySearch);",
  "",
  "  document.querySelectorAll('[data-provider-filter]').forEach(btn=>{",
  "    btn.addEventListener('click',()=>{",
  "      showToast('Filter control is ready for the Admin data adapter.','info','Provider Filter');",
  "      emit('dreamworker:providers-filter',{filter:btn.dataset.providerFilter});",
  "    });",
  "  });",
  "",
  "  document.querySelectorAll('[data-view]').forEach(btn=>{",
  "    btn.addEventListener('click',()=>{",
  "      document.querySelectorAll('[data-view]').forEach(b=>b.classList.remove('active'));",
  "      btn.classList.add('active');",
  "      showToast((btn.dataset.view==='list'?'List':'Grid')+' view selected in preview mode.','info','View');",
  "      emit('dreamworker:providers-view',{view:btn.dataset.view});",
  "    });",
  "  });",
  "",
  "  addBtn.addEventListener('click',()=>{",
  "    addBtn.animate&&addBtn.animate([{transform:'translateY(0)'},{transform:'translateY(-1px)'},{transform:'translateY(0)'}],{duration:180});",
  "    showToast('Add Provider hook is ready. No provider is created in preview mode.','success','Add Provider');",
  "    emit('dreamworker:providers-add-request',{});",
  "  });",
  "",
  "  document.querySelectorAll('.row-action').forEach((btn,index)=>{",
  "    btn.addEventListener('click',e=>{",
  "      e.stopPropagation();",
  "      const row=btn.closest('.provider-row');",
  "      showToast(row.dataset.providerName+' actions are ready for integration.','info','Provider Actions');",
  "      emit('dreamworker:providers-row-action',{provider:row.dataset.providerName,index});",
  "    });",
  "  });",
  "",
  "  rows.forEach(row=>{",
  "    row.setAttribute('tabindex','0');",
  "    const activate=()=>{",
  "      showToast(row.dataset.providerName+' selected.','info','Provider');",
  "      emit('dreamworker:provider-select',{provider:row.dataset.providerName,status:row.dataset.providerStatus});",
  "    };",
  "    row.addEventListener('click',activate);",
  "    row.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate();}});",
  "  });",
  "",
  "  document.querySelectorAll('[data-nav]').forEach(el=>{",
  "    el.addEventListener('click',e=>{",
  "      e.preventDefault();",
  "      document.querySelectorAll('[data-nav]').forEach(n=>n.classList.remove('active'));",
  "      el.classList.add('active');",
  "      emit('dreamworker:dashboard-navigate',{target:el.dataset.nav});",
  "      showToast('Preview navigation: '+el.textContent.trim()+'.','info','Navigation');",
  "    });",
  "  });",
  "",
  "  // Providers nav should be active on this page.",
  "  document.querySelectorAll('[data-nav]').forEach(n=>n.classList.toggle('active',n.dataset.nav==='providers'));",
  "",
  "  window.DreamWorkerProvidersUI={",
  "    showToast,",
  "    refresh(){",
  "      showToast('Preview refresh complete \u2014 no network request was sent.','success','Providers');",
  "      emit('dreamworker:providers-refresh',{preview:true});",
  "    },",
  "    setRows(html){",
  "      document.getElementById('provider-table-body').innerHTML=html;",
  "    },",
  "    setCount(text){count.textContent=text;},",
  "    focusSearch(){search.focus();}",
  "  };",
  "",
  "  emit('dreamworker:providers-ready',{viewport:'1368x753',mode:'display-only'});",
  "})();",
  "",
  "</script>",
  "</body>",
  "</html>",
  "",
].join("\n");
