export const AUDIT_FIDELITY_CSS = String.raw`
/* Audit fidelity: evidence ledger + persistent safe inspector, backed only by /admin/api/logs rows. */
#page-logs{padding:17px 24px 18px}
#page-logs .hero{height:83px}
.audit-lineage-fidelity{height:65px;margin-top:10px;border:1px solid #dfe9f4;border-radius:11px;background:#fff;box-shadow:var(--shadow);display:grid;grid-template-columns:150px 1fr auto;align-items:center;padding:0 12px;gap:12px;overflow:hidden}
.audit-lineage-title span{display:block;font-size:6.7px;letter-spacing:.09em;color:#8295b6;font-weight:800}.audit-lineage-title b{display:block;margin-top:4px;font-size:10px;color:#193f78}.audit-lineage-title small{display:block;margin-top:2px;font-size:6.3px;color:#8999b7}.audit-lineage-flow{display:grid;grid-template-columns:1fr 18px 1fr 18px 1fr 18px 1fr;align-items:center}.audit-lineage-node{min-width:0}.audit-lineage-node span{display:block;font-size:5.8px;color:#8798b5;text-transform:uppercase;letter-spacing:.06em}.audit-lineage-node b{display:block;margin-top:3px;font-size:7px;color:#315583;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.audit-lineage-link{height:1px;background:linear-gradient(90deg,#cbd9e7,#72b7df,#66ceb3)}.audit-window{height:28px;padding:0 9px;border-radius:14px;border:1px solid #dce7f3;background:#f8fbff;display:flex;align-items:center;gap:6px;color:#58719d;font-size:6.5px;white-space:nowrap}.audit-window i{width:6px;height:6px;border-radius:50%;background:#2b7fe1}
.audit-fidelity-workbench{height:calc(100% - 168px);margin-top:10px;display:grid;grid-template-columns:minmax(0,1.7fr) minmax(300px,.8fr);gap:10px}
.audit-ledger-fidelity,.audit-evidence-inspector{height:100%;border:1px solid #dfe9f4;border-radius:12px;background:#fff;box-shadow:var(--shadow);overflow:hidden}
.audit-ledger-head{height:44px;border-bottom:1px solid #e5edf6;display:flex;align-items:center;padding:0 11px;gap:8px}.audit-ledger-title{min-width:130px}.audit-ledger-title b{display:block;font-size:10px;color:#173d76}.audit-ledger-title span{display:block;margin-top:2px;font-size:6.8px;color:#8596b6}.audit-ledger-head .searchbox{height:29px;min-width:230px}.audit-ledger-head #logs-summary{margin-left:auto;font-size:7px;color:#8193b4}
.audit-evidence-strip{height:45px;border-bottom:1px solid #e9eff6;background:linear-gradient(180deg,#fbfdff,#f8fbff);padding:8px 10px;position:relative}.audit-evidence-strip-head{display:flex;justify-content:space-between;font-size:5.8px;color:#8a9ab7}.audit-evidence-strip-head b{color:#5b729d}.audit-evidence-track{position:absolute;left:14px;right:14px;bottom:10px;height:1px;background:#d9e4ee}.audit-evidence-dots{position:absolute;left:14px;right:14px;bottom:7px;height:7px;display:flex;align-items:center;gap:4px;overflow:hidden}.audit-evidence-dot{width:6px;height:6px;border-radius:50%;background:#6fa5d6;flex:none}.audit-evidence-dot.provider{background:#2e86df}.audit-evidence-dot.model{background:#5a78d8}.audit-evidence-dot.health{background:#2ab38a}.audit-evidence-dot.auth{background:#9c7ed4}
.audit-ledger-table{height:calc(100% - 89px);overflow:auto}.audit-ledger-table .data-table th{height:30px}.audit-ledger-table .data-table td{height:42px}.audit-ledger-table tbody tr{cursor:pointer;transition:.14s}.audit-ledger-table tbody tr.audit-selected{background:linear-gradient(90deg,#f1f7ff,#fbfdff);box-shadow:inset 3px 0 0 #267fe4}.audit-ledger-table tbody tr.audit-hidden{display:none}
.audit-evidence-inspector{display:flex;flex-direction:column}.audit-inspector-head{height:58px;border-bottom:1px solid #e5edf6;padding:9px 11px;display:flex;align-items:center;gap:9px}.audit-inspector-icon{width:32px;height:32px;border-radius:9px;background:#eef5ff;color:#2c73ce;display:grid;place-items:center;flex:none}.audit-inspector-icon svg{width:16px;height:16px}.audit-inspector-copy{min-width:0}.audit-inspector-copy span{display:block;font-size:6.5px;letter-spacing:.08em;text-transform:uppercase;color:#8999b7;font-weight:800}.audit-inspector-copy b{display:block;margin-top:2px;font-size:9.3px;color:#173d76;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.audit-inspector-badge{margin-left:auto}
.audit-inspector-body{flex:1;min-height:0;overflow:auto;padding:10px}.audit-inspector-section{margin-bottom:10px}.audit-inspector-section>span{display:block;margin-bottom:5px;font-size:6.4px;letter-spacing:.08em;text-transform:uppercase;color:#8596b5;font-weight:800}.audit-inspector-facts{display:grid;grid-template-columns:1fr 1fr;gap:5px}.audit-inspector-fact{min-height:38px;border:1px solid #e4ebf3;border-radius:8px;background:#fbfdff;padding:7px}.audit-inspector-fact small{display:block;font-size:5.9px;color:#8a99b5}.audit-inspector-fact b{display:block;margin-top:3px;font-size:7px;color:#315483;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.audit-detail-evidence{border:1px solid #dfe8f2;border-radius:8px;background:#f8fbff;padding:8px;font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:6.5px;line-height:1.5;color:#45658f;word-break:break-word;white-space:pre-wrap}.audit-safe-note{border:1px solid #dbe8f2;border-radius:8px;background:#f5fbf9;padding:8px;display:flex;gap:7px;color:#49775f;font-size:6.4px;line-height:1.4}.audit-safe-note svg{width:14px;height:14px;flex:none;color:#16a56a}
.audit-inspector-actions{height:43px;border-top:1px solid #e5edf6;padding:6px 9px;display:flex;gap:7px}.audit-inspector-actions .btn{height:29px}.audit-inspector-actions .btn:first-child{flex:1}
@media(max-width:1000px){.audit-fidelity-workbench{grid-template-columns:1fr}.audit-evidence-inspector{display:none}.audit-lineage-fidelity{grid-template-columns:150px 1fr}.audit-window{display:none}}
`;

export const AUDIT_FIDELITY_SECTION = String.raw`
    <section id="page-logs" class="page audit-fidelity-page">
      <section class="hero"><div class="eyebrow">Audit Log</div><h1>Audit Trail & Evidence</h1><p>Persisted administrative actions as an evidence ledger — what happened, what target was affected, and what safe detail was recorded.</p><div class="hero-actions"><button class="btn" data-action="refresh-logs"><svg><use href="#i-refresh"/></svg>Refresh</button></div><svg class="hero-wave" viewBox="0 0 360 75" preserveAspectRatio="none"><path d="M0 53 C80 6 145 75 220 35S310 26 360 43" fill="none" stroke="#35aee3"/><path d="M0 66 C95 33 154 70 238 52S320 49 360 61" fill="none" stroke="#50cdb7"/></svg></section>
      <section class="audit-lineage-fidelity"><div class="audit-lineage-title"><span>EVENT LINEAGE</span><b>D1-backed evidence</b><small>Persisted, never inferred</small></div><div class="audit-lineage-flow"><div class="audit-lineage-node"><span>Action</span><b>Admin mutation / check</b></div><div class="audit-lineage-link"></div><div class="audit-lineage-node"><span>Recorder</span><b>Audit persistence</b></div><div class="audit-lineage-link"></div><div class="audit-lineage-node"><span>Read API</span><b>/admin/api/logs</b></div><div class="audit-lineage-link"></div><div class="audit-lineage-node"><span>Surface</span><b>Evidence Inspector</b></div></div><div class="audit-window"><i></i><span id="audit-window-count">Loading events…</span></div></section>
      <section class="audit-fidelity-workbench">
        <article class="audit-ledger-fidelity"><div class="audit-ledger-head"><div class="audit-ledger-title"><b>Administrative activity</b><span>Current authenticated evidence window</span></div><div class="searchbox"><svg><use href="#i-search"/></svg><input id="audit-search" placeholder="Search action, target or detail"></div><span id="logs-summary">Loading…</span></div><div class="audit-evidence-strip"><div class="audit-evidence-strip-head"><span>Older</span><b>LOADED EVIDENCE ORDER</b><span>Recent</span></div><div class="audit-evidence-track"></div><div id="audit-evidence-dots" class="audit-evidence-dots"></div></div><div class="audit-ledger-table"><table class="data-table"><thead><tr><th style="width:21%">Timestamp</th><th style="width:25%">Action</th><th style="width:22%">Target</th><th style="width:32%">Safe detail / context</th></tr></thead><tbody id="logs-body"></tbody></table></div></article>
        <aside class="audit-evidence-inspector" aria-label="Audit evidence inspector"><div class="audit-inspector-head"><div class="audit-inspector-icon"><svg class="icon"><use href="#i-doc"/></svg></div><div class="audit-inspector-copy"><span>Evidence Inspector</span><b id="audit-inspector-action">Select an event</b></div><span id="audit-inspector-badge" class="state UNKNOWN">EVIDENCE</span></div><div class="audit-inspector-body"><div class="audit-inspector-section"><span>Event facts</span><div class="audit-inspector-facts"><div class="audit-inspector-fact"><small>Recorded</small><b id="audit-inspector-time">—</b></div><div class="audit-inspector-fact"><small>Target</small><b id="audit-inspector-target">—</b></div><div class="audit-inspector-fact"><small>Actor</small><b id="audit-inspector-actor">Not exposed in current table</b></div><div class="audit-inspector-fact"><small>Source</small><b>/admin/api/logs</b></div></div></div><div class="audit-inspector-section"><span>Persisted safe detail</span><div id="audit-inspector-detail" class="audit-detail-evidence">Select an event row to inspect the safe detail already rendered by the authenticated Admin API.</div></div><div class="audit-inspector-section"><span>Evidence boundary</span><div class="audit-safe-note"><svg class="icon"><use href="#i-shield"/></svg><span>Only evidence already returned to the Admin surface is shown here. Secret values are never requested, reconstructed or exposed.</span></div></div></div><div class="audit-inspector-actions"><button id="audit-copy-evidence" class="btn" disabled><svg><use href="#i-copy"/></svg>Copy safe evidence</button><button class="btn" disabled title="Audit history is read-only in the current Admin contract">Read only</button></div></aside>
      </section>
    </section>
`;

export const AUDIT_FIDELITY_SCRIPT = String.raw`(function(){
'use strict';
var selected=null,scheduled=false;
function text(el){return el?el.textContent.trim():'';}
function rows(){return Array.prototype.slice.call(document.querySelectorAll('#logs-body tr')).filter(function(r){return r.querySelectorAll('td').length>=4;});}
function eventFromRow(row){var c=row.querySelectorAll('td');if(c.length<4)return null;return{time:text(c[0]),action:text(c[1].querySelector('.cell-title'))||text(c[1]),target:text(c[2]),detail:text(c[3]),row:row};}
function family(action){action=String(action||'').toLowerCase();if(action.indexOf('provider')>=0)return'provider';if(action.indexOf('model')>=0)return'model';if(action.indexOf('health')>=0)return'health';if(action.indexOf('login')>=0||action.indexOf('auth')>=0)return'auth';return'other';}
function events(){return rows().map(eventFromRow).filter(Boolean);}
function drawDots(list){var host=document.getElementById('audit-evidence-dots');host.innerHTML='';list.slice(0,48).forEach(function(e){var d=document.createElement('span');d.className='audit-evidence-dot '+family(e.action);d.title=e.action+' · '+e.time;host.appendChild(d);});document.getElementById('audit-window-count').textContent=list.length+' persisted event'+(list.length===1?'':'s')+' loaded';}
function select(index){var list=events(),e=list[index];if(!e&&list.length)e=list[0],index=0;if(!e)return;selected=e;list.forEach(function(x,i){x.row.classList.toggle('audit-selected',i===index);});document.getElementById('audit-inspector-action').textContent=e.action||'event';document.getElementById('audit-inspector-time').textContent=e.time||'—';document.getElementById('audit-inspector-target').textContent=e.target||'—';document.getElementById('audit-inspector-detail').textContent=e.detail&&e.detail!=='—'?e.detail:'No additional persisted detail was returned for this event.';var badge=document.getElementById('audit-inspector-badge');badge.className='state CONFIGURED';badge.textContent=family(e.action).toUpperCase();var copy=document.getElementById('audit-copy-evidence');copy.disabled=false;}
function filter(){var q=(document.getElementById('audit-search').value||'').trim().toLowerCase();rows().forEach(function(row){var e=eventFromRow(row);row.classList.toggle('audit-hidden',!!q&&[e.time,e.action,e.target,e.detail].join(' ').toLowerCase().indexOf(q)<0);});}
function refresh(){scheduled=false;var list=events();drawDots(list);filter();if(!list.length)return;if(selected){var idx=list.findIndex(function(e){return e.time===selected.time&&e.action===selected.action&&e.target===selected.target;});select(idx>=0?idx:0);}else select(0);}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(refresh);}
var body=document.getElementById('logs-body');if(body){body.addEventListener('click',function(e){var row=e.target.closest('tr');if(!row)return;var list=rows(),idx=list.indexOf(row);if(idx>=0)select(idx);});new MutationObserver(schedule).observe(body,{childList:true,subtree:true,characterData:true});}
var search=document.getElementById('audit-search');if(search)search.addEventListener('input',filter);var copy=document.getElementById('audit-copy-evidence');if(copy)copy.addEventListener('click',async function(){if(!selected)return;var payload='Action: '+selected.action+'\nRecorded: '+selected.time+'\nTarget: '+selected.target+'\nDetail: '+selected.detail;try{await navigator.clipboard.writeText(payload);}catch(_e){return;}});schedule();
})();`;

export function applyAuditFidelity(html: string): string {
  const start = html.indexOf('<section id="page-logs"');
  const end = start >= 0 ? html.indexOf('<section id="page-settings"', start) : -1;
  if (start < 0 || end < 0) return html;
  let out = html.slice(0, start) + AUDIT_FIDELITY_SECTION + '\n\n    ' + html.slice(end);
  out = out.replace('</head>', '<style>' + AUDIT_FIDELITY_CSS + '</style></head>');
  out = out.replace('</body>', '<script>' + AUDIT_FIDELITY_SCRIPT + '</script></body>');
  return out;
}
