import { ICONS } from "./icons";
import { ADMIN_CSS } from "./styles";
import { CLIENT_SCRIPT } from "./client";

export function dashboardHtml(): string {
	return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>DreamWorker MCP Control Plane — Admin</title>
<style>${ADMIN_CSS}</style>
</head><body>
${ICONS}
<div class="viewport"><div class="app" id="app">
  <aside class="sidebar">
    <div class="brand"><div class="dw-mark"><svg viewBox="0 0 48 48" fill="none"><defs><linearGradient id="shell-logo" x1="4" y1="4" x2="44" y2="44"><stop stop-color="#2e91ff"/><stop offset=".55" stop-color="#20bce8"/><stop offset="1" stop-color="#29d5b4"/></linearGradient></defs><path d="M8 11.5 24 4l16 7.5v14.8c0 7.5-5.9 13.3-16 17.7C13.9 39.6 8 33.8 8 26.3Z" stroke="url(#shell-logo)" stroke-width="2.6"/><path d="M15 25.7 21.2 32 34 18.8" stroke="url(#shell-logo)" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div><div class="brand-wordmark">DreamWorker</div><div class="brand-subtitle">MCP Control Plane</div></div></div>
    <nav class="nav" aria-label="Admin sections">
      <a class="nav-item active" data-nav="overview"><span class="ni"><svg class="icon"><use href="#i-home"/></svg></span>Overview</a>
      <a class="nav-item" data-nav="providers"><span class="ni"><svg class="icon"><use href="#i-db"/></svg></span>Providers</a>
      <a class="nav-item" data-nav="models"><span class="ni"><svg class="icon"><use href="#i-cube"/></svg></span>Models</a>
      <a class="nav-item" data-nav="mcp-tools"><span class="ni"><svg class="icon"><use href="#i-nodes"/></svg></span>MCP Tools</a>
      <a class="nav-item" data-nav="routing"><span class="ni"><svg class="icon"><use href="#i-route"/></svg></span>Routing</a>
      <a class="nav-item" data-nav="health"><span class="ni"><svg class="icon"><use href="#i-heart"/></svg></span>Health</a>
      <a class="nav-item" data-nav="usage"><span class="ni"><svg class="icon"><use href="#i-bars"/></svg></span>Usage</a>
      <a class="nav-item" data-nav="logs"><span class="ni"><svg class="icon"><use href="#i-doc"/></svg></span>Audit Log</a>
      <a class="nav-item" data-nav="settings"><span class="ni"><svg class="icon"><use href="#i-gear"/></svg></span>Settings</a>
    </nav>
    <div class="side-foot"><b>DreamWorker</b><span>The future is created today.</span><span id="side-version" class="version">version loading…</span></div>
  </aside>

  <header class="header">
    <label class="global-search"><span class="si"><svg class="icon"><use href="#i-search"/></svg></span><input id="global-search" placeholder="Search providers, models, tools…" autocomplete="off"><span class="kbd">Ctrl K</span></label>
    <div class="head-right"><div class="environment"><span class="dot"></span><span id="environment-label">Production</span></div><button id="header-refresh" class="hicon" title="Refresh current data"><span class="hi"><svg class="icon"><use href="#i-refresh"/></svg></span></button><div class="headuser"><div class="avatar">A</div><div><b>Admin</b><small>Owner session</small></div></div></div>
  </header>

  <main class="main">
    <section id="page-overview" class="page active">
      <section class="hero"><div class="eyebrow">Overview</div><h1>Good evening, Admin</h1><p>Live control-plane state from D1, runtime routing, MCP registry and health records.</p><div class="hero-actions"><button class="btn" data-action="refresh-all"><svg><use href="#i-refresh"/></svg>Refresh</button></div><svg class="hero-wave" viewBox="0 0 360 75" preserveAspectRatio="none"><path d="M0 53 C80 6 145 75 220 35S310 26 360 43" fill="none" stroke="#35aee3"/><path d="M0 66 C95 33 154 70 238 52S320 49 360 61" fill="none" stroke="#50cdb7"/></svg></section>
      <section class="metrics"><div class="metric"><div class="metric-label">Providers enabled</div><div id="ov-providers" class="metric-value">—</div><div id="ov-providers-sub" class="metric-sub">Loading runtime state</div><div class="spark"><svg><use href="#i-db"/></svg></div></div><div class="metric"><div class="metric-label">Models callable</div><div id="ov-models" class="metric-value">—</div><div id="ov-models-sub" class="metric-sub">Loading registry</div><div class="spark"><svg><use href="#i-cube"/></svg></div></div><div class="metric"><div class="metric-label">Active aliases</div><div id="ov-routes" class="metric-value">—</div><div id="ov-routes-sub" class="metric-sub">Loading routing</div><div class="spark"><svg><use href="#i-route"/></svg></div></div><div class="metric"><div class="metric-label">MCP tools</div><div id="ov-tools" class="metric-value">—</div><div id="ov-tools-sub" class="metric-sub">Runtime catalog</div><div class="spark"><svg><use href="#i-nodes"/></svg></div></div></section>
      <section class="overview-grid"><div class="card overview-providers"><div class="card-head"><h2>Providers</h2><span id="overview-provider-caption" class="sub">Runtime-authoritative state</span><div class="right"><button class="link-btn" data-nav-jump="providers">View all</button></div></div><div id="overview-provider-list"><div class="loading-box"><div class="skeleton" style="width:180px"></div></div></div></div><div class="card"><div class="card-head"><h2>System Health</h2><div class="right"><button class="link-btn" data-nav-jump="health">Details</button></div></div><div id="overview-health" class="health-summary"><div class="loading-box"><div class="skeleton" style="width:120px"></div></div></div></div><div class="card"><div class="card-head"><h2>Quick Actions</h2></div><div class="quick-list"><button class="quick-action" data-action="test-providers"><span class="qaico"><svg><use href="#i-bolt"/></svg></span><span><b>Test Providers</b><span>Run supported backend health checks</span></span></button><button class="quick-action" data-action="verify-tools"><span class="qaico"><svg><use href="#i-shield"/></svg></span><span><b>Verify Tools</b><span>Reload the runtime-backed MCP catalog</span></span></button><button class="quick-action" data-nav-jump="logs"><span class="qaico"><svg><use href="#i-doc"/></svg></span><span><b>View Logs</b><span>Open recent control-plane events</span></span></button></div></div><div class="card overview-activity"><div class="card-head"><h2>Recent Activity</h2><span class="sub">Real audit events</span><div class="right"><button class="link-btn" data-nav-jump="logs">View all</button></div></div><div id="overview-activity-list" class="activity-list"><div class="loading-box"><div class="skeleton" style="width:170px"></div></div></div></div></section>
    </section>

    <section id="page-providers" class="page">
      <section class="hero"><div class="eyebrow">Providers</div><h1>Provider Runtime & Credentials</h1><p>Enablement, health, BYOK configuration and routing impact from the existing Admin backend.</p><div class="hero-actions"><button class="btn" disabled title="No create-provider backend contract exists">Add Provider</button><button class="btn" data-action="refresh-providers"><svg><use href="#i-refresh"/></svg>Refresh</button></div></section>
      <div class="providers-layout"><div class="provider-metrics"><div class="mini-metric"><b id="pr-total">—</b><span>Registered providers</span></div><div class="mini-metric"><b id="pr-enabled">—</b><span>Enabled</span></div><div class="mini-metric"><b id="pr-healthy">—</b><span>Healthy</span></div><div class="mini-metric"><b id="pr-configured">—</b><span>BYOK configured</span></div></div><section class="card provider-card"><div class="toolbar"><div class="searchbox"><svg><use href="#i-search"/></svg><input id="provider-search" placeholder="Search providers"></div><button id="provider-filter" class="btn tiny" data-filter="all">All status</button><span id="provider-summary" class="summary">Loading…</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th style="width:18%">Provider</th><th style="width:10%">Runtime</th><th style="width:12%">Health</th><th style="width:13%">Models</th><th style="width:16%">Routing</th><th style="width:10%">BYOK</th><th style="width:21%">Actions</th></tr></thead><tbody id="providers-body"><tr><td colspan="7"><div class="loading-box"><div class="skeleton" style="width:220px"></div></div></td></tr></tbody></table></div></section></div>
    </section>

    <section id="page-models" class="page">
      <section class="hero"><div class="eyebrow">Models</div><h1>Model Registry & Runtime</h1><p>Understand what is registered, what is enabled, and what is actually callable at runtime.</p><div class="hero-actions"><button class="btn" disabled title="No register-model backend contract exists">Register Model</button><button class="btn" data-action="refresh-models"><svg><use href="#i-refresh"/></svg>Refresh</button></div></section>
      <div class="models-layout"><div class="model-metrics"><div class="mini-metric"><b id="md-total">—</b><span>Registered models</span></div><div class="mini-metric"><b id="md-enabled">—</b><span>Enabled by model policy</span></div><div class="mini-metric"><b id="md-callable">—</b><span>Effectively callable</span></div><div class="mini-metric"><b id="md-blocked">—</b><span>Fail-closed / unavailable</span></div></div><section class="card model-card"><div class="toolbar"><div class="searchbox"><svg><use href="#i-search"/></svg><input id="model-search" placeholder="Search registered models"></div><button id="model-filter" class="btn tiny" data-filter="all">All states</button><span id="model-summary" class="summary">Loading…</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th style="width:23%">Model</th><th style="width:17%">Provider</th><th style="width:13%">Model policy</th><th style="width:15%">Effective runtime</th><th style="width:17%">Routing aliases</th><th style="width:15%">Actions</th></tr></thead><tbody id="models-body"><tr><td colspan="6"><div class="loading-box"><div class="skeleton" style="width:220px"></div></div></td></tr></tbody></table></div></section></div>
    </section>

    <section id="page-mcp-tools" class="page">
      <section class="hero"><div class="eyebrow">MCP Tools</div><h1>Tool Catalog & Execution Surface</h1><p>Inspect protocol metadata, safety annotations, input schemas, and runtime catalog readiness.</p><div class="hero-actions"><button class="btn" data-action="refresh-tools"><svg><use href="#i-refresh"/></svg>Reload catalog</button></div></section>
      <div class="tools-layout"><section id="tool-annotation-rail" class="protocol-rail card"><button class="protocol-pill active" data-tool-filter="all"><b>All tools</b><span id="tool-count-all">Runtime catalog</span></button><button class="protocol-pill" data-tool-filter="readonly"><b>Read only</b><span id="tool-count-readonly">—</span></button><button class="protocol-pill" data-tool-filter="destructive"><b>Destructive</b><span id="tool-count-destructive">—</span></button><button class="protocol-pill" data-tool-filter="openworld"><b>Open world</b><span id="tool-count-openworld">—</span></button></section><section class="tool-workbench card"><div class="tool-list"><div class="toolbar"><div class="searchbox"><svg><use href="#i-search"/></svg><input id="tools-search" placeholder="Search tools"></div><span id="tools-summary" class="summary">Loading…</span></div><div id="tools-body" class="tool-list-scroll"><div class="loading-box"><div class="skeleton" style="width:220px"></div></div></div></div><aside id="tool-detail" class="tool-detail"><div class="empty"><b>Select a tool</b><span>Schema and annotations will appear here.</span></div></aside></section></div>
    </section>

    <section id="page-routing" class="page">
      <section class="hero"><div class="eyebrow">Routing</div><h1>Routing Control Plane</h1><p>Alias resolution remains configured even when a target becomes unavailable; state is explicit and fail-closed.</p><div class="hero-actions"><button class="btn" data-action="refresh-routing"><svg><use href="#i-refresh"/></svg>Refresh</button></div></section>
      <div class="routing-layout"><section id="route-strip" class="route-strip card"><div class="loading-box" style="width:100%"><div class="skeleton" style="width:230px"></div></div></section><section class="route-table card"><div class="card-head"><h2>Alias resolution map</h2><span class="sub">D1 rules enriched with effective runtime state</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th style="width:18%">Alias</th><th style="width:29%">Target model</th><th style="width:22%">Provider</th><th style="width:16%">State</th><th style="width:15%">Updated</th></tr></thead><tbody id="routing-body"></tbody></table></div></section><aside id="route-inspector" class="route-inspector card"><div class="empty"><b>Select an alias</b><span>Inspect its real target and fail-closed state.</span></div></aside></div>
    </section>

    <section id="page-health" class="page">
      <section class="hero"><div class="eyebrow">Health</div><h1>Health & Diagnostics</h1><p>Provider health states and recorded checks from the production Admin backend.</p><div class="hero-actions"><button class="btn" data-action="test-providers"><svg><use href="#i-bolt"/></svg>Test providers</button><button class="btn" data-action="refresh-health"><svg><use href="#i-refresh"/></svg>Refresh</button></div></section>
      <div class="health-layout"><section class="health-signal card"><div class="taxonomy"><b>HEALTHY</b><span>Upstream request succeeded</span></div><div class="taxonomy"><b>RATE_LIMITED</b><span>Explicit upstream 429</span></div><div class="taxonomy"><b>AUTH_ERROR</b><span>Upstream 401 / 403</span></div><div class="taxonomy"><b>NOT_CONFIGURED</b><span>Required setup missing</span></div><div class="taxonomy"><b>UPSTREAM_ERROR</b><span>Other provider/fetch failure</span></div></section><section class="health-current card"><h2>Provider status</h2><div id="provider-health-list" class="provider-health-list"><div class="loading-box"><div class="skeleton" style="width:160px"></div></div></div></section><section class="health-history card"><div class="card-head"><h2>Health history</h2><span class="sub">Recorded checks</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th style="width:24%">Checked</th><th style="width:22%">Provider</th><th style="width:16%">State</th><th style="width:14%">Latency</th><th style="width:24%">Detail</th></tr></thead><tbody id="health-body"></tbody></table></div></section></div>
    </section>

    <section id="page-usage" class="page">
      <section class="hero"><div class="eyebrow">Usage</div><h1>Audit Activity & Observability</h1><p>The current backend exposes Admin audit activity, not request-token accounting; the UI labels that distinction explicitly.</p><div class="hero-actions"><button class="btn" data-action="refresh-usage"><svg><use href="#i-refresh"/></svg>Refresh</button></div></section>
      <div class="usage-layout"><div class="usage-grid"><div class="metric"><div class="metric-label">Audit events returned</div><div id="usage-total" class="metric-value">—</div><div class="metric-sub">/admin/api/usage</div></div><div class="metric"><div class="metric-label">Recent actions</div><div id="usage-recent" class="metric-value">—</div><div class="metric-sub">Latest activity sample</div></div><div class="metric"><div class="metric-label">Token / request usage</div><div class="metric-value" style="font-size:17px;margin-top:7px">Unavailable</div><div class="metric-sub">No current Admin usage contract</div></div></div><section class="usage-panel card"><div class="usage-note"><b style="color:#24497f">Source-of-truth boundary</b><br>This page does not infer or fabricate request counts, spend, token usage, or latency percentiles. The existing backend currently returns audit-event counts and recent Admin actions only.</div><div class="recent-actions" id="usage-actions"></div></section></div>
    </section>

    <section id="page-logs" class="page">
      <section class="hero"><div class="eyebrow">Audit Log</div><h1>Control-plane Activity</h1><p>Recent authenticated Admin mutations and health checks from the backend audit log.</p><div class="hero-actions"><button class="btn" data-action="refresh-logs"><svg><use href="#i-refresh"/></svg>Refresh</button></div></section>
      <div class="logs-layout"><section class="logs-card card"><div class="card-head"><h2>Recent events</h2><span id="logs-summary" class="sub">Loading…</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th style="width:22%">Time</th><th style="width:24%">Action</th><th style="width:22%">Target</th><th style="width:32%">Detail</th></tr></thead><tbody id="logs-body"></tbody></table></div></section></div>
    </section>

    <section id="page-settings" class="page">
      <section class="hero"><div class="eyebrow">Settings</div><h1>Runtime Metadata & Session</h1><p>Bound environment metadata only; secret values are intentionally never rendered.</p><div class="hero-actions"><button class="btn" data-action="refresh-settings"><svg><use href="#i-refresh"/></svg>Refresh</button></div></section>
      <div class="settings-layout"><section class="settings-grid"><div class="settings-card card"><h2>Runtime bindings</h2><div id="settings-runtime"><div class="loading-box"><div class="skeleton" style="width:160px"></div></div></div></div><div class="settings-card card"><h2>Security posture</h2><div id="settings-security"></div><div class="danger-zone"><b>Owner session</b><p>Signing out clears the Admin session cookie. No privileged token is stored in frontend state.</p><form method="POST" action="/admin/logout"><button class="btn danger" type="submit"><svg><use href="#i-lock"/></svg>Sign out</button></form></div></div></section></div>
    </section>
  </main>

  <div id="toast-stack" class="toast-stack"></div>
  <div id="command" class="command"><input id="command-input" placeholder="Search pages, providers, models and tools…"><div id="command-results" class="command-results"></div></div>
  <div id="modal-backdrop" class="modal-backdrop"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-head"><b id="modal-title">Provider credential</b><button id="modal-close" class="btn icon-only" style="margin-left:auto"><svg><use href="#i-x"/></svg></button></div><div class="modal-body"><p id="modal-copy"></p><label for="modal-value">Credential value</label><input id="modal-value" type="password" autocomplete="off" placeholder="Secret value"></div><div class="modal-actions"><button id="modal-cancel" class="btn">Cancel</button><button id="modal-submit" class="btn primary">Save credential</button></div></section></div>

  <section id="bootstrap" class="bootstrap"><div class="bootstrap-card"><div class="boot-brand"><div class="mark"><svg viewBox="0 0 48 48" fill="none"><defs><linearGradient id="boot-logo" x1="4" y1="4" x2="44" y2="44"><stop stop-color="#2b79ef"/><stop offset=".55" stop-color="#25bfe7"/><stop offset="1" stop-color="#3bd1b8"/></linearGradient></defs><path d="M8 11.5 24 4l16 7.5v14.8c0 7.5-5.9 13.3-16 17.7C13.9 39.6 8 33.8 8 26.3Z" stroke="url(#boot-logo)" stroke-width="2.6"/><path d="M15 25.7 21.2 32 34 18.8" stroke="url(#boot-logo)" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div><b>DreamWorker</b><span>MCP Control Plane</span></div></div><div class="spinner"></div><h1 id="boot-title">Preparing your control plane</h1><p id="boot-copy">Validating the session and loading authoritative runtime state.</p><div id="boot-grid" class="boot-grid"></div><div class="boot-actions"><button id="boot-retry" class="btn primary"><svg><use href="#i-refresh"/></svg>Retry failed loads</button><button id="boot-continue" class="btn">Continue degraded</button></div></div></section>
</div></div>
<script>${CLIENT_SCRIPT}</script>
</body></html>`;
}
