export const HEALTH_FIDELITY_CSS = String.raw`
/* Health fidelity: diagnostic radar backed by real provider state + persisted health evidence. */
#page-health{padding:17px 24px 18px}
#page-health .hero{height:83px}
.health-fidelity-main{height:263px;margin-top:10px;display:grid;grid-template-columns:240px minmax(0,1fr) 265px;gap:10px}
.health-radar-card,.health-provider-card,.health-diagnostic-card,.health-history-fidelity{border:1px solid #dfe9f4;border-radius:12px;background:#fff;box-shadow:var(--shadow);overflow:hidden}
.health-radar-card{position:relative;background:radial-gradient(150px 130px at 50% 48%,rgba(43,181,195,.075),transparent 72%),linear-gradient(180deg,#fbfdff,#f8fbff);padding:11px;text-align:center}
.health-card-label{font-size:6.8px;letter-spacing:.09em;color:#8295b6;font-weight:800;text-transform:uppercase}.health-radar-card h2{margin:3px 0 0;font-size:10px;color:#183e77}
.health-radar{position:relative;width:160px;height:160px;margin:9px auto 0;border-radius:50%;background:radial-gradient(circle at center,rgba(255,255,255,.98) 0 22%,rgba(236,248,251,.7) 22.5% 23%,transparent 23.5%);overflow:hidden}.health-radar .orbit{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);border-radius:50%;border:1px solid rgba(80,153,198,.15)}.health-radar .o1{width:66px;height:66px}.health-radar .o2{width:108px;height:108px}.health-radar .o3{width:150px;height:150px}.health-radar .sweep{position:absolute;left:50%;top:50%;width:75px;height:75px;transform-origin:0 0;background:linear-gradient(32deg,rgba(45,190,165,.12),transparent 65%);clip-path:polygon(0 0,100% 0,0 100%);animation:healthSweep 5s linear infinite}@keyframes healthSweep{to{transform:rotate(360deg)}}.health-radar-core{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:68px;height:68px;border-radius:50%;background:#fff;box-shadow:0 8px 21px rgba(42,87,124,.07),inset 0 0 0 1px #dfebf4;display:grid;place-items:center;z-index:3}.health-radar-core b{display:block;font-size:13px;color:#244c83}.health-radar-core span{display:block;margin-top:2px;font-size:5.8px;color:#8797b3}.health-radar-dot{position:absolute;width:7px;height:7px;border-radius:50%;transform:translate(-50%,-50%);box-shadow:0 0 0 4px rgba(122,151,182,.08);z-index:4}.health-radar-dot.HEALTHY{background:#12ad69;box-shadow:0 0 0 4px rgba(18,173,105,.09)}.health-radar-dot.RATE_LIMITED{background:#d79c2e;box-shadow:0 0 0 4px rgba(215,156,46,.09)}.health-radar-dot.AUTH_ERROR,.health-radar-dot.UPSTREAM_ERROR{background:#d45f6b;box-shadow:0 0 0 4px rgba(212,95,107,.09)}.health-radar-dot.NOT_CONFIGURED,.health-radar-dot.DISABLED{background:#94a5ba}.health-radar-caption{margin-top:4px;font-size:6.1px;line-height:1.35;color:#8294b4}
.health-provider-card{display:flex;flex-direction:column}.health-provider-head{height:43px;border-bottom:1px solid #e6edf5;padding:0 11px;display:flex;align-items:center}.health-provider-head h2{margin:0;font-size:10px;color:#183d76}.health-provider-head span{margin-left:auto;font-size:7px;color:#8295b7}.health-provider-card #provider-health-list{flex:1;min-height:0;overflow:auto;padding:6px 8px}.health-provider-card .provider-health{min-height:45px;border:1px solid #e5ecf4;border-radius:8px;background:#fbfdff;padding:7px 8px;margin-bottom:5px;display:grid;grid-template-columns:1fr auto;align-items:center;gap:7px;cursor:pointer;transition:.14s}.health-provider-card .provider-health:hover{border-color:#cadced;background:#fff}.health-provider-card .provider-health.health-selected{background:linear-gradient(90deg,#f2f8ff,#fbfdff);box-shadow:inset 3px 0 0 #2780e6}.health-provider-card .provider-health b{font-size:8px;color:#21477e}.health-provider-card .provider-health span{font-size:6.4px;color:#8294b4}.health-provider-card .provider-health .btn{height:23px;padding:0 6px;font-size:6.5px}
.health-diagnostic-card{display:flex;flex-direction:column}.health-diagnostic-head{height:43px;border-bottom:1px solid #e6edf5;padding:0 11px;display:flex;align-items:center}.health-diagnostic-head h2{margin:0;font-size:10px;color:#183d76}.health-diagnostic-body{flex:1;padding:9px 10px;overflow:auto}.health-diagnostic-state{height:51px;border:1px solid #e2eaf3;border-radius:9px;background:#f8fbff;display:flex;align-items:center;gap:9px;padding:9px}.health-diagnostic-state i{width:11px;height:11px;border-radius:50%;background:#9aaabd;box-shadow:0 0 0 4px rgba(154,170,189,.09)}.health-diagnostic-state.HEALTHY i{background:#12ad69;box-shadow:0 0 0 4px rgba(18,173,105,.09)}.health-diagnostic-state.RATE_LIMITED i{background:#d79c2e}.health-diagnostic-state.AUTH_ERROR i,.health-diagnostic-state.UPSTREAM_ERROR i{background:#d45f6b}.health-diagnostic-state b{display:block;font-size:8px;color:#274b7f}.health-diagnostic-state span{display:block;margin-top:3px;font-size:6.3px;color:#8293b1}.health-diagnostic-facts{margin-top:7px;display:grid;grid-template-columns:1fr 1fr;gap:5px}.health-diagnostic-fact{min-height:37px;border:1px solid #e5ebf3;border-radius:8px;background:#fbfdff;padding:7px}.health-diagnostic-fact small{display:block;font-size:5.9px;color:#8999b5}.health-diagnostic-fact b{display:block;margin-top:3px;font-size:7px;color:#315484;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.health-diagnostic-copy{margin-top:7px;border:1px solid #e2eaf3;border-radius:8px;background:#fff;padding:8px;font-size:6.5px;line-height:1.45;color:#6c83aa}.health-taxonomy{margin-top:7px;display:flex;flex-wrap:wrap;gap:4px}.health-taxonomy span{height:18px;padding:0 6px;border-radius:9px;border:1px solid #e0e8f1;background:#f6f9fc;display:flex;align-items:center;font-size:5.8px;color:#677c9f}
.health-history-fidelity{height:calc(100% - 366px);margin-top:10px}.health-history-head-fidelity{height:43px;border-bottom:1px solid #e6edf5;padding:0 11px;display:flex;align-items:center}.health-history-head-fidelity h2{margin:0;font-size:10px;color:#183d76}.health-history-head-fidelity span{margin-left:7px;font-size:7px;color:#8294b5}.health-history-head-fidelity .right{margin-left:auto;display:flex;gap:7px}.health-history-fidelity .table-wrap{height:calc(100% - 43px)}.health-history-fidelity .data-table th{height:30px}.health-history-fidelity .data-table td{height:39px}
@media(prefers-reduced-motion:reduce){.health-radar .sweep{animation:none}}
@media(max-width:1000px){.health-fidelity-main{grid-template-columns:220px 1fr}.health-diagnostic-card{display:none}}
`;

export const HEALTH_FIDELITY_SECTION = String.raw`
    <section id="page-health" class="page health-fidelity-page">
      <section class="hero"><div class="eyebrow">Health</div><h1>Health & Diagnostics</h1><p>Real provider state and persisted health evidence — configuration alone is never presented as healthy.</p><div class="hero-actions"><button class="btn" data-action="test-providers"><svg><use href="#i-bolt"/></svg>Test providers</button><button class="btn" data-action="refresh-health"><svg><use href="#i-refresh"/></svg>Refresh</button></div><svg class="hero-wave" viewBox="0 0 360 75" preserveAspectRatio="none"><path d="M0 53 C80 6 145 75 220 35S310 26 360 43" fill="none" stroke="#35aee3"/><path d="M0 66 C95 33 154 70 238 52S320 49 360 61" fill="none" stroke="#50cdb7"/></svg></section>
      <section class="health-fidelity-main">
        <article class="health-radar-card"><span class="health-card-label">DIAGNOSTIC RADAR</span><h2>Provider signal map</h2><div id="health-radar" class="health-radar"><div class="orbit o1"></div><div class="orbit o2"></div><div class="orbit o3"></div><div class="sweep"></div><div id="health-radar-points"></div><div class="health-radar-core"><div><b id="health-radar-count">—</b><span>healthy enabled</span></div></div></div><div class="health-radar-caption">Dots are real provider states. The rotating sweep is decorative and does not claim a live probe.</div></article>
        <article class="health-provider-card"><div class="health-provider-head"><h2>Provider status</h2><span id="health-provider-summary">Loading runtime posture…</span></div><div id="provider-health-list"><div class="loading-box"><div class="skeleton" style="width:160px"></div></div></div></article>
        <aside class="health-diagnostic-card"><div class="health-diagnostic-head"><h2>Diagnostic focus</h2></div><div class="health-diagnostic-body"><div id="health-focus-state" class="health-diagnostic-state"><i></i><div><b>No provider selected</b><span>Select a provider state to inspect its latest evidence.</span></div></div><div class="health-diagnostic-facts"><div class="health-diagnostic-fact"><small>Provider</small><b id="health-focus-provider">—</b></div><div class="health-diagnostic-fact"><small>Latest check</small><b id="health-focus-checked">—</b></div><div class="health-diagnostic-fact"><small>Latency</small><b id="health-focus-latency">—</b></div><div class="health-diagnostic-fact"><small>Classification</small><b id="health-focus-class">—</b></div></div><div id="health-focus-copy" class="health-diagnostic-copy">Health evidence is classified from backend state only. No inferred success.</div><div class="health-taxonomy"><span>HEALTHY</span><span>RATE_LIMITED</span><span>AUTH_ERROR</span><span>NOT_CONFIGURED</span><span>UPSTREAM_ERROR</span></div></div></aside>
      </section>
      <section class="health-history-fidelity"><div class="health-history-head-fidelity"><h2>Health history</h2><span>Persisted checks / evidence</span><div class="right"><button class="btn tiny" data-action="refresh-health"><svg><use href="#i-refresh"/></svg>Refresh evidence</button></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th style="width:20%">Checked</th><th style="width:20%">Provider</th><th style="width:16%">State</th><th style="width:14%">Latency</th><th style="width:30%">Diagnostic detail</th></tr></thead><tbody id="health-body"></tbody></table></div></section>
    </section>
`;

export const HEALTH_FIDELITY_SCRIPT = String.raw`(function(){
'use strict';
var selectedProvider=null,scheduled=false;
function text(el){return el?el.textContent.trim():'';}
function stateText(el){var s=el&&el.querySelector('.state');return text(s)||'UNKNOWN';}
function providerRows(){return Array.prototype.slice.call(document.querySelectorAll('#provider-health-list .provider-health')).map(function(row){var b=row.querySelector('button[data-provider-test]');var id=b?b.dataset.providerTest:'';var copy=row.querySelector('div:first-child');var name=text(copy&&copy.querySelector('b'))||id;var meta=text(copy&&copy.querySelector('span'));return{id:id,name:name,state:stateText(row),meta:meta,row:row};}).filter(function(x){return x.id;});}
function historyRows(){return Array.prototype.slice.call(document.querySelectorAll('#health-body tr')).map(function(row){var c=row.querySelectorAll('td');if(c.length<5)return null;return{checked:text(c[0]),provider:text(c[1].querySelector('.cell-title'))||text(c[1]),state:stateText(c[2]),latency:text(c[3]),detail:text(c[4])};}).filter(Boolean);}
function latest(id){var hs=historyRows();for(var i=0;i<hs.length;i++)if(hs[i].provider===id)return hs[i];return null;}
function classification(state){state=String(state||'UNKNOWN').toUpperCase();if(state==='HEALTHY')return['Healthy','Upstream request succeeded according to persisted health evidence.'];if(state==='RATE_LIMITED')return['Rate limit','Upstream was reached and returned an explicit rate-limit state.'];if(state==='AUTH_ERROR')return['Authentication','Provider authentication failed; enabled/configured state is not treated as healthy.'];if(state==='NOT_CONFIGURED')return['Configuration','Required provider configuration is missing.'];if(state==='UPSTREAM_ERROR')return['Upstream','Provider/fetch failed outside the explicit auth or rate-limit classes.'];if(state==='DISABLED')return['Policy','Provider is disabled by runtime policy; no health success is inferred.'];return['Unknown','No supported healthy classification is available for this state.'];}
function drawRadar(list){var host=document.getElementById('health-radar-points');host.innerHTML='';var coords=[[27,31],[72,27],[79,66],[31,73],[51,16],[18,53]];list.slice(0,6).forEach(function(p,i){var dot=document.createElement('span');dot.className='health-radar-dot '+String(p.state||'UNKNOWN').replaceAll(' ','_');dot.style.left=coords[i][0]+'%';dot.style.top=coords[i][1]+'%';dot.title=p.name+' · '+p.state;host.appendChild(dot);});var healthy=list.filter(function(p){return p.state==='HEALTHY';}).length;document.getElementById('health-radar-count').textContent=healthy+'/'+list.length;document.getElementById('health-provider-summary').textContent=healthy+' healthy · '+list.length+' providers loaded';}
function select(id){var list=providerRows();var p=list.find(function(x){return x.id===id;})||list[0];if(!p)return;selectedProvider=p.id;list.forEach(function(x){x.row.classList.toggle('health-selected',x.id===p.id);});var h=latest(p.id),state=h?h.state:p.state;var focus=document.getElementById('health-focus-state'),parts=classification(state);focus.className='health-diagnostic-state '+String(state||'UNKNOWN').replaceAll(' ','_');focus.querySelector('b').textContent=state||'UNKNOWN';focus.querySelector('span').textContent=parts[1];document.getElementById('health-focus-provider').textContent=p.id;document.getElementById('health-focus-checked').textContent=h?h.checked:'No persisted check';document.getElementById('health-focus-latency').textContent=h?h.latency:'—';document.getElementById('health-focus-class').textContent=parts[0];document.getElementById('health-focus-copy').textContent=h&&h.detail&&h.detail!=='—'?h.detail:parts[1];}
function refresh(){scheduled=false;var list=providerRows();drawRadar(list);if(!list.length)return;if(!selectedProvider||!list.some(function(x){return x.id===selectedProvider;}))selectedProvider=list[0].id;select(selectedProvider);}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(refresh);}
var plist=document.getElementById('provider-health-list');if(plist){plist.addEventListener('click',function(e){if(e.target.closest('button'))return;var row=e.target.closest('.provider-health');var b=row&&row.querySelector('[data-provider-test]');if(b)select(b.dataset.providerTest);});new MutationObserver(schedule).observe(plist,{childList:true,subtree:true,characterData:true});}
var history=document.getElementById('health-body');if(history)new MutationObserver(schedule).observe(history,{childList:true,subtree:true,characterData:true});schedule();
})();`;

export function applyHealthFidelity(html: string): string {
  const start = html.indexOf('<section id="page-health"');
  const end = start >= 0 ? html.indexOf('<section id="page-usage"', start) : -1;
  if (start < 0 || end < 0) return html;
  let out = html.slice(0, start) + HEALTH_FIDELITY_SECTION + '\n\n    ' + html.slice(end);
  out = out.replace('</head>', '<style>' + HEALTH_FIDELITY_CSS + '</style></head>');
  out = out.replace('</body>', '<script>' + HEALTH_FIDELITY_SCRIPT + '</script></body>');
  return out;
}
