export const LOADING_FIDELITY_CSS = String.raw`
/* Production bootstrap visual fidelity. Progress is driven by real Admin bootstrap state, never a timer. */
.bootstrap.bootstrap-fidelity{background:radial-gradient(520px 270px at 50% 28%,rgba(46,151,235,.10),transparent 70%),radial-gradient(460px 240px at 66% 58%,rgba(49,207,178,.07),transparent 72%),rgba(248,252,255,.985);backdrop-filter:blur(5px)}
.bootstrap.bootstrap-fidelity:before,.bootstrap.bootstrap-fidelity:after{content:"";position:absolute;left:-2%;right:-2%;height:150px;pointer-events:none;border-radius:50%;border-top:1px solid rgba(52,155,226,.27);transform:rotate(-3deg)}.bootstrap.bootstrap-fidelity:before{bottom:54px}.bootstrap.bootstrap-fidelity:after{bottom:29px;border-top-color:rgba(45,199,166,.26);transform:rotate(2deg)}
.bootstrap-fidelity-card{position:relative;width:650px;min-height:506px;border:1px solid #dce8f3;border-radius:18px;background:linear-gradient(145deg,rgba(255,255,255,.985),rgba(250,253,255,.94));box-shadow:0 28px 78px rgba(35,70,110,.15),inset 0 1px 0 rgba(255,255,255,.9);padding:28px 34px 25px;text-align:center;overflow:hidden}
.bootstrap-fidelity-card:before{content:"";position:absolute;left:50%;top:-100px;width:420px;height:210px;transform:translateX(-50%);border-radius:50%;background:radial-gradient(circle,rgba(43,133,238,.10),transparent 68%);pointer-events:none}
.boot-brand-fidelity{position:relative;display:inline-flex;align-items:center;gap:9px;margin-bottom:9px}.boot-brand-fidelity .mark{width:40px;height:40px}.boot-brand-fidelity .mark svg{width:100%;height:100%}.boot-brand-fidelity b{display:block;text-align:left;font-size:14px;color:#0d2e68;letter-spacing:-.25px}.boot-brand-fidelity span{display:block;margin-top:2px;text-align:left;font-size:7.5px;color:#8192b4}
.boot-orbit{position:relative;width:92px;height:92px;margin:4px auto 12px}.boot-orbit-ring{position:absolute;inset:0;border-radius:50%;background:conic-gradient(#2b79ef var(--boot-progress,0%),#e5edf5 0);transition:background .28s ease;box-shadow:0 10px 28px rgba(45,115,178,.12)}.boot-orbit-ring:before{content:"";position:absolute;inset:7px;border-radius:50%;background:#fbfdff;box-shadow:inset 0 0 0 1px #e1eaf3}.boot-orbit-ring:after{content:"";position:absolute;inset:18px;border-radius:50%;border:1px solid #dbe6f0}.boot-orbit-core{position:absolute;inset:0;display:grid;place-items:center;z-index:1}.boot-orbit-core strong{display:block;font-size:17px;color:#173f78;line-height:1}.boot-orbit-core span{display:block;margin-top:3px;font-size:6.5px;color:#8194b6;text-transform:uppercase;letter-spacing:.08em}.bootstrap-fidelity-card h1{margin:0;font-size:20px;color:#0f2b62;letter-spacing:-.45px}.bootstrap-fidelity-card>p{margin:6px auto 0;max-width:500px;font-size:8.5px;line-height:1.55;color:#6f83ad}
.boot-progress-shell{margin:17px 3px 0}.boot-progress-line{height:4px;border-radius:999px;background:#e6edf5;overflow:hidden}.boot-progress-fill{height:100%;width:0;border-radius:999px;background:linear-gradient(90deg,#2b79ef,#2fb5df,#39cdaa);transition:width .28s ease;box-shadow:0 0 12px rgba(42,179,211,.22)}.boot-progress-meta{margin-top:6px;display:flex;justify-content:space-between;font-size:6.7px;color:#8396b8}.boot-progress-meta b{color:#315b93;font-weight:750}
.boot-phase-row{margin-top:13px;display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.boot-phase{min-height:43px;border:1px solid #e0e9f2;border-radius:9px;background:#fbfdff;padding:7px;text-align:left;display:flex;align-items:flex-start;gap:7px}.boot-phase i{width:14px;height:14px;border-radius:50%;background:#edf2f7;border:1px solid #d8e3ee;position:relative;flex:none;margin-top:1px}.boot-phase i:after{content:"";position:absolute;inset:4px;border-radius:50%;background:#a7b5c6}.boot-phase b{display:block;font-size:7px;color:#315181}.boot-phase span{display:block;margin-top:2px;font-size:5.9px;line-height:1.35;color:#8b9ab7}.boot-phase.done{border-color:#cfe8dc;background:#f8fcfa}.boot-phase.done i{background:#eaf9f2;border-color:#bfe7d5}.boot-phase.done i:after{background:#12ad6b}.boot-phase.active{border-color:#bdd9f4;background:#f5faff;box-shadow:0 5px 14px rgba(48,110,173,.06)}.boot-phase.active i:after{background:#2b79ef}.boot-phase.error{border-color:#efcdd3;background:#fff8f9}.boot-phase.error i:after{background:#d45c69}
.boot-grid.boot-grid-fidelity{margin-top:12px;display:grid;grid-template-columns:repeat(3,1fr);gap:5px;max-height:118px;overflow:auto;padding-right:2px}.boot-grid-fidelity .boot-step{min-height:34px;border-radius:8px;padding:6px 7px;text-align:left}.boot-grid-fidelity .boot-step b{font-size:6.8px}.boot-grid-fidelity .boot-step span{font-size:5.8px;margin-top:2px}
.bootstrap-fidelity .boot-actions{margin-top:13px;justify-content:center}.bootstrap-fidelity .boot-actions .btn{height:29px}.bootstrap-fidelity:not(.degraded) #boot-continue{display:none}.bootstrap-fidelity:not(.degraded) #boot-retry{display:none}.bootstrap-fidelity.degraded #boot-retry,.bootstrap-fidelity.degraded #boot-continue{display:inline-flex}
.boot-security{margin:11px auto 0;width:430px;min-height:38px;border:1px solid #e0e9f2;border-radius:9px;background:rgba(248,251,255,.82);display:flex;align-items:center;justify-content:center;gap:8px;color:#6f84ad;font-size:6.8px}.boot-security svg{width:14px;height:14px;color:#2a77d6}.boot-security b{color:#315889}
.bootstrap-fidelity.degraded .boot-orbit-ring{background:conic-gradient(#d39a2d var(--boot-progress,100%),#e8edf3 0)}
`;

export const LOADING_FIDELITY_SECTION = String.raw`
  <section id="bootstrap" class="bootstrap bootstrap-fidelity">
    <div class="bootstrap-fidelity-card">
      <div class="boot-brand-fidelity"><div class="mark"><svg viewBox="0 0 48 48" fill="none"><defs><linearGradient id="boot-fidelity-logo" x1="4" y1="4" x2="44" y2="44"><stop stop-color="#2b79ef"/><stop offset=".55" stop-color="#25bfe7"/><stop offset="1" stop-color="#3bd1b8"/></linearGradient></defs><path d="M8 11.5 24 4l16 7.5v14.8c0 7.5-5.9 13.3-16 17.7C13.9 39.6 8 33.8 8 26.3Z" stroke="url(#boot-fidelity-logo)" stroke-width="2.6"/><path d="M15 25.7 21.2 32 34 18.8" stroke="url(#boot-fidelity-logo)" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div><b>DreamWorker</b><span>MCP Control Plane</span></div></div>
      <div class="boot-orbit"><div id="boot-orbit-ring" class="boot-orbit-ring"></div><div class="boot-orbit-core"><div><strong id="boot-percent">0%</strong><span>bootstrap</span></div></div></div>
      <h1 id="boot-title">Preparing your control plane</h1>
      <p id="boot-copy">Validating the session and loading authoritative runtime state.</p>
      <div class="boot-progress-shell"><div class="boot-progress-line"><div id="boot-progress-fill" class="boot-progress-fill"></div></div><div class="boot-progress-meta"><span id="boot-progress-caption">Waiting for Admin sources…</span><b id="boot-progress-count">0 / 9 settled</b></div></div>
      <div class="boot-phase-row"><div id="boot-phase-session" class="boot-phase done"><i></i><div><b>Session</b><span>Authenticated Admin shell served</span></div></div><div id="boot-phase-registry" class="boot-phase"><i></i><div><b>Registry</b><span>Providers · models · routing · tools</span></div></div><div id="boot-phase-evidence" class="boot-phase"><i></i><div><b>Evidence</b><span>Health · usage · audit · settings</span></div></div><div id="boot-phase-ready" class="boot-phase"><i></i><div><b>Readiness</b><span>All sources settled honestly</span></div></div></div>
      <div id="boot-grid" class="boot-grid boot-grid-fidelity"></div>
      <div class="boot-actions"><button id="boot-retry" class="btn primary"><svg><use href="#i-refresh"/></svg>Retry failed loads</button><button id="boot-continue" class="btn">Continue degraded</button></div>
      <div class="boot-security"><svg class="icon"><use href="#i-shield"/></svg><span><b>No synthetic readiness.</b> Progress reflects actual Admin bootstrap sources; degraded data stays degraded.</span></div>
    </div>
  </section>
`;

export const LOADING_FIDELITY_SCRIPT = String.raw`(function(){
'use strict';
var boot=document.getElementById('bootstrap'),grid=document.getElementById('boot-grid');if(!boot||!grid)return;
var total=9;
function counts(){var rows=Array.prototype.slice.call(grid.querySelectorAll('.boot-step'));var settled=rows.filter(function(r){return r.classList.contains('ok')||r.classList.contains('error');}).length;var ok=rows.filter(function(r){return r.classList.contains('ok');}).length;var failed=rows.filter(function(r){return r.classList.contains('error');}).length;return{rows:rows,settled:settled,ok:ok,failed:failed};}
function setPhase(id,state){var el=document.getElementById(id);if(!el)return;el.className='boot-phase '+state;}
function update(){var c=counts(),pct=Math.round(c.settled/total*100);var fill=document.getElementById('boot-progress-fill'),percent=document.getElementById('boot-percent'),caption=document.getElementById('boot-progress-caption'),count=document.getElementById('boot-progress-count'),ring=document.getElementById('boot-orbit-ring');if(fill)fill.style.width=pct+'%';if(percent)percent.textContent=pct+'%';if(count)count.textContent=c.settled+' / '+total+' settled';if(ring)ring.style.setProperty('--boot-progress',pct+'%');var registryKeys=['Providers','Models','Routing','MCP Tools'];var evidenceKeys=['Health','Usage','Audit Log','Settings'];function group(keys){var list=c.rows.filter(function(r){var b=r.querySelector('b');return b&&keys.indexOf(b.textContent.trim())>=0;});if(!list.length)return'';if(list.some(function(r){return r.classList.contains('error');}))return'error';if(list.every(function(r){return r.classList.contains('ok');}))return'done';return'active';}setPhase('boot-phase-session','done');setPhase('boot-phase-registry',group(registryKeys)||'active');setPhase('boot-phase-evidence',group(evidenceKeys)||'');if(c.settled===total)setPhase('boot-phase-ready',c.failed?'error':'done');else setPhase('boot-phase-ready','');if(c.settled===0)caption.textContent='Waiting for authoritative Admin sources…';else if(c.settled<total)caption.textContent='Loading backend contracts — '+c.ok+' successful so far';else if(c.failed)caption.textContent='Bootstrap complete with '+c.failed+' unavailable source'+(c.failed===1?'':'s');else caption.textContent='All Admin sources loaded successfully';}
new MutationObserver(update).observe(grid,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['class']});new MutationObserver(update).observe(boot,{attributes:true,attributeFilter:['class']});update();
})();`;

export function applyLoadingFidelity(html: string): string {
  const start = html.indexOf('<section id="bootstrap"');
  const end = start >= 0 ? html.indexOf('</section>', start) : -1;
  if (start < 0 || end < 0) return html;
  const after = end + '</section>'.length;
  let out = html.slice(0, start) + LOADING_FIDELITY_SECTION + html.slice(after);
  out = out.replace('</head>', '<style>' + LOADING_FIDELITY_CSS + '</style></head>');
  out = out.replace('</body>', '<script>' + LOADING_FIDELITY_SCRIPT + '</script></body>');
  return out;
}
