export const MODELS_FIDELITY_CSS = String.raw`
/* Models V2 fidelity layer: page-specific architecture, shared shell remains authoritative. */
#page-models{padding:17px 24px 18px}
#page-models .hero{height:83px}
.model-fidelity-posture{height:140px;margin-top:10px;display:grid;grid-template-columns:1.02fr 1.08fr 1.2fr;gap:10px}
.model-fidelity-card{border:1px solid #dfe9f4;border-radius:12px;background:#fff;box-shadow:var(--shadow);overflow:hidden;min-width:0}
.model-fidelity-card-head{height:39px;padding:0 12px;display:flex;align-items:center;border-bottom:1px solid #e7eef6;background:linear-gradient(180deg,#fff,#fbfdff)}
.model-fidelity-card-head>div{min-width:0}.model-fidelity-kicker{display:block;font-size:7.2px;letter-spacing:.09em;color:#7086b2;font-weight:800}.model-fidelity-card-head h2{margin:2px 0 0;font-size:10.5px;color:#173c78;letter-spacing:-.08px}
.model-fidelity-pill{margin-left:auto;height:20px;padding:0 7px;border-radius:999px;border:1px solid #dce7f3;background:#f5f9fd;color:#5e78a9;display:flex;align-items:center;font-size:7.4px;font-weight:750;white-space:nowrap}.model-fidelity-pill.good{color:#0c8a5e;background:#edf9f4;border-color:#c9eadc}.model-fidelity-pill.shield{color:#2d67b7;background:#eef6ff;border-color:#cfe0f5}
.model-registry-body{height:101px;display:grid;grid-template-columns:105px 1fr;align-items:center;padding:9px 12px}.model-registry-ring{width:78px;height:78px;border-radius:50%;background:conic-gradient(#1dbb7b 0 0%,#e8eef5 0 100%);display:grid;place-items:center;position:relative;box-shadow:inset 0 0 0 1px #dbe6f0}.model-registry-ring:after{content:"";position:absolute;inset:9px;border-radius:50%;background:#fff;box-shadow:0 0 0 1px #e5edf5}.model-registry-core{position:relative;z-index:1;text-align:center}.model-registry-core b{display:block;font-size:18px;color:#123a75;line-height:1}.model-registry-core span{display:block;margin-top:3px;font-size:6.8px;color:#7990b8}
.model-registry-legend{display:grid;gap:6px}.model-registry-legend div{display:grid;grid-template-columns:8px 1fr auto;align-items:center;gap:5px;font-size:7.8px;color:#7186ad}.model-registry-legend i{width:6px;height:6px;border-radius:50%;background:#9cacbf}.model-registry-legend i.callable{background:#13ad6b}.model-registry-legend i.blocked{background:#d99a2d}.model-registry-legend i.registered{background:#4385dc}.model-registry-legend strong{font-size:8.5px;color:#254c84}
.model-alias-stack{height:101px;padding:8px 10px;display:grid;gap:5px;overflow:hidden}.model-alias-route{height:25px;border:1px solid #e0e9f3;border-radius:7px;background:#fbfdff;display:grid;grid-template-columns:60px 12px 1fr auto;align-items:center;gap:4px;padding:0 8px;color:#31588f;font-size:7.6px;text-align:left;min-width:0}.model-alias-route:hover{background:#f4f9ff;border-color:#cfe0f1}.model-alias-route b{font-size:7.9px;color:#16447e}.model-alias-route span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.model-alias-route em{font-style:normal;font-size:6.4px;font-weight:800}.model-alias-route em.ACTIVE{color:#0b8b5c}.model-alias-route em.MODEL_DISABLED,.model-alias-route em.PROVIDER_DISABLED{color:#a56c10}.model-alias-route em.BROKEN{color:#b93c53}.model-alias-empty{height:100%;display:grid;place-items:center;color:#8295b8;font-size:7.4px}
.model-chain{height:101px;padding:8px 11px;display:grid;grid-template-columns:1fr 12px 1fr 12px 1fr 12px 1fr;align-items:center}.model-chain-step{min-width:0;text-align:center}.model-chain-step i{width:24px;height:24px;border-radius:8px;background:#f2f6fb;border:1px solid #dce6f0;display:grid;place-items:center;margin:0 auto 5px;color:#7285a4;font-style:normal;font-size:8px;font-weight:800}.model-chain-step strong{display:block;font-size:7.2px;color:#284b7f;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.model-chain-step small{display:block;margin-top:2px;font-size:6.1px;color:#8496b6;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.model-chain-step.good i{background:#ecfaf4;border-color:#bfe8d7;color:#0b9463}.model-chain-step.warn i{background:#fff8ea;border-color:#efdcae;color:#a46d0d}.model-chain-step.bad i{background:#fff2f4;border-color:#f0c5cd;color:#b53850}.model-chain-link{height:1px;background:linear-gradient(90deg,#dbe5ef,#bdd0e3)}
.model-fidelity-workbench{height:calc(100% - 243px);margin-top:10px;display:grid;grid-template-columns:minmax(0,1.68fr) minmax(286px,.82fr);gap:10px}
.model-catalog-card,.model-inspector-card{height:100%}
.model-catalog-toolbar{height:43px;border-bottom:1px solid #e5edf6;display:flex;align-items:center;padding:0 11px;gap:8px}.model-catalog-title{min-width:112px}.model-catalog-title b{display:block;font-size:10px;color:#183f78}.model-catalog-title span{display:block;margin-top:2px;font-size:7px;color:#8496b7}.model-catalog-toolbar .searchbox{height:29px;min-width:205px}.model-catalog-toolbar .summary{margin-left:auto}
.model-catalog-table{height:calc(100% - 43px);overflow:auto}.model-catalog-table .data-table th{height:30px}.model-catalog-table .data-table td{height:45px}.model-catalog-table tbody tr{cursor:pointer;transition:.14s}.model-catalog-table tbody tr.model-selected{background:linear-gradient(90deg,#f0f7ff,#fbfdff);box-shadow:inset 3px 0 0 #2580e8}.model-catalog-table tbody tr.model-selected .cell-title{color:#1259a8}.model-catalog-table .row-actions{position:relative;z-index:2}
.model-inspector-card{display:flex;flex-direction:column}.model-inspector-head{height:53px;border-bottom:1px solid #e5edf6;padding:9px 12px;display:flex;align-items:center;gap:9px}.model-inspector-icon{width:30px;height:30px;border-radius:9px;background:linear-gradient(145deg,#edf6ff,#eefcf8);color:#2479dc;display:grid;place-items:center;flex:none}.model-inspector-icon svg{width:16px;height:16px}.model-inspector-head-copy{min-width:0}.model-inspector-head-copy span{display:block;font-size:6.6px;color:#8495b3;text-transform:uppercase;letter-spacing:.08em;font-weight:800}.model-inspector-head-copy b{display:block;margin-top:2px;font-size:9.5px;color:#173d77;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.model-inspector-status{margin-left:auto}
.model-inspector-body{flex:1;min-height:0;overflow:auto;padding:10px 11px}.model-inspector-section{margin-bottom:10px}.model-inspector-section>span{display:block;margin-bottom:5px;font-size:6.6px;color:#8395b3;text-transform:uppercase;letter-spacing:.08em;font-weight:800}.model-inspector-facts{display:grid;grid-template-columns:1fr 1fr;gap:5px}.model-inspector-fact{min-height:39px;border:1px solid #e4ebf3;border-radius:8px;background:#fbfdff;padding:7px}.model-inspector-fact small{display:block;font-size:6.3px;color:#8798b7}.model-inspector-fact b{display:block;margin-top:3px;font-size:7.7px;color:#244c83;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.model-inspector-aliases{display:flex;gap:4px;flex-wrap:wrap}.model-inspector-aliases .chip{max-width:none}.model-consequence{border:1px solid #dce7f2;border-radius:8px;background:#f7fbff;padding:8px 9px;font-size:7.2px;line-height:1.45;color:#617aa7}.model-consequence.good{border-color:#ccebdd;background:#f4fbf8;color:#29735b}.model-consequence.warn{border-color:#eeddb8;background:#fffaf1;color:#8a681f}.model-consequence.bad{border-color:#efcbd1;background:#fff7f8;color:#9b4a5a}
.model-inspector-actions{height:43px;border-top:1px solid #e5edf6;padding:6px 10px;display:flex;gap:7px}.model-inspector-actions .btn{height:29px}.model-inspector-actions .btn:first-child{flex:1}.model-inspector-actions .btn[disabled]{opacity:.5}
@media(max-width:1000px){.model-fidelity-posture{grid-template-columns:1fr 1fr}.model-fidelity-posture .model-fidelity-card:last-child{display:none}.model-fidelity-workbench{grid-template-columns:1fr}.model-inspector-card{display:none}}
`;

export const MODELS_FIDELITY_SECTION = String.raw`
    <section id="page-models" class="page models-fidelity-page">
      <section class="hero"><div class="eyebrow">Models</div><h1>Model Registry & Runtime</h1><p>Registry posture, alias dependencies and effective runtime — without confusing enabled with callable.</p><div class="hero-actions"><button class="btn" disabled title="No register-model backend contract exists">Register Model</button><button class="btn" data-action="refresh-models"><svg><use href="#i-refresh"/></svg>Refresh</button></div><svg class="hero-wave" viewBox="0 0 360 75" preserveAspectRatio="none"><path d="M0 53 C80 6 145 75 220 35S310 26 360 43" fill="none" stroke="#35aee3"/><path d="M0 66 C95 33 154 70 238 52S320 49 360 61" fill="none" stroke="#50cdb7"/></svg></section>

      <section class="model-fidelity-posture" aria-label="Model registry posture">
        <article class="model-fidelity-card">
          <div class="model-fidelity-card-head"><div><span class="model-fidelity-kicker">MODEL REGISTRY</span><h2>Registry posture</h2></div><span id="model-posture-pill" class="model-fidelity-pill">Loading</span></div>
          <div class="model-registry-body"><div id="model-registry-ring" class="model-registry-ring"><div class="model-registry-core"><b id="md-callable">—</b><span>callable</span></div></div><div class="model-registry-legend"><div><i class="callable"></i><span>Enabled</span><strong id="md-enabled">—</strong></div><div><i class="blocked"></i><span>Unavailable / blocked</span><strong id="md-blocked">—</strong></div><div><i class="registered"></i><span>Registered</span><strong id="md-total">—</strong></div></div></div>
        </article>

        <article class="model-fidelity-card">
          <div class="model-fidelity-card-head"><div><span class="model-fidelity-kicker">ROUTING ALIASES</span><h2>Alias → model resolution</h2></div><span id="model-alias-pill" class="model-fidelity-pill good">Runtime</span></div>
          <div id="model-alias-stack" class="model-alias-stack"><div class="model-alias-empty">Waiting for routing state…</div></div>
        </article>

        <article class="model-fidelity-card">
          <div class="model-fidelity-card-head"><div><span class="model-fidelity-kicker">AVAILABILITY CHAIN</span><h2>Why selected model is or is not callable</h2></div><span class="model-fidelity-pill shield">Fail-closed</span></div>
          <div class="model-chain"><div id="chain-model" class="model-chain-step"><i>1</i><strong>Model policy</strong><small>Awaiting selection</small></div><div class="model-chain-link"></div><div id="chain-provider" class="model-chain-step"><i>2</i><strong>Provider state</strong><small>Awaiting selection</small></div><div class="model-chain-link"></div><div id="chain-config" class="model-chain-step"><i>3</i><strong>Configuration</strong><small>Backend evidence</small></div><div class="model-chain-link"></div><div id="chain-effective" class="model-chain-step"><i>4</i><strong>Effective runtime</strong><small>Awaiting selection</small></div></div>
        </article>
      </section>

      <section class="model-fidelity-workbench">
        <article class="model-fidelity-card model-catalog-card">
          <div class="model-catalog-toolbar"><div class="model-catalog-title"><b>Model Catalog</b><span>Authoritative registry</span></div><div class="searchbox"><svg><use href="#i-search"/></svg><input id="model-search" placeholder="Search registered models"></div><button id="model-filter" class="btn tiny" data-filter="all">All states</button><span id="model-summary" class="summary">Loading…</span></div>
          <div class="model-catalog-table"><table class="data-table"><thead><tr><th style="width:27%">Model</th><th style="width:19%">Provider</th><th style="width:14%">Model policy</th><th style="width:17%">Effective runtime</th><th style="width:23%">Aliases & actions</th></tr></thead><tbody id="models-body"><tr><td colspan="5"><div class="loading-box"><div class="skeleton" style="width:220px"></div></div></td></tr></tbody></table></div>
        </article>

        <aside class="model-fidelity-card model-inspector-card" aria-label="Selected model inspector">
          <div class="model-inspector-head"><div class="model-inspector-icon"><svg class="icon"><use href="#i-cube"/></svg></div><div class="model-inspector-head-copy"><span>Selected Model Inspector</span><b id="model-inspector-title">Select a model</b></div><span id="model-inspector-status" class="state UNKNOWN">UNKNOWN</span></div>
          <div class="model-inspector-body"><div class="model-inspector-section"><span>Runtime facts</span><div class="model-inspector-facts"><div class="model-inspector-fact"><small>Provider</small><b id="model-inspector-provider">—</b></div><div class="model-inspector-fact"><small>Model policy</small><b id="model-inspector-policy">—</b></div><div class="model-inspector-fact"><small>Provider policy</small><b id="model-inspector-provider-policy">—</b></div><div class="model-inspector-fact"><small>Configuration</small><b id="model-inspector-config">—</b></div><div class="model-inspector-fact"><small>Effective availability</small><b id="model-inspector-effective">—</b></div><div class="model-inspector-fact"><small>Source</small><b>D1 / Admin API</b></div></div></div><div class="model-inspector-section"><span>Routing aliases</span><div id="model-inspector-aliases" class="model-inspector-aliases"><span class="chip">none selected</span></div></div><div class="model-inspector-section"><span>Operational consequence</span><div id="model-inspector-consequence" class="model-consequence">Select a registry row to inspect the effective chain. Configuration is shown only when a safe backend-derived provider signal is available.</div></div></div>
          <div class="model-inspector-actions"><button id="model-inspector-toggle" class="btn" disabled>No model selected</button><button class="btn" disabled title="No Admin model-invocation test endpoint exists">Test invocation unavailable</button></div>
        </aside>
      </section>
    </section>
`;

export const MODELS_FIDELITY_SCRIPT = String.raw`(function(){
'use strict';
var selectedId=null,scheduled=false;
function text(el){return el?el.textContent.trim():'';}
function stateText(cell){var s=cell&&cell.querySelector('.state');return text(s)||text(cell)||'UNKNOWN';}
function providerConfig(providerId){var rows=Array.prototype.slice.call(document.querySelectorAll('#providers-body tr'));for(var i=0;i<rows.length;i++){var cells=rows[i].querySelectorAll('td');if(cells.length<6)continue;var id=text(cells[0].querySelector('.cell-sub'));if(id===providerId){var v=stateText(cells[5]);return v||'UNKNOWN';}}return 'NOT EXPOSED';}
function modelRows(){return Array.prototype.slice.call(document.querySelectorAll('#models-body tr')).filter(function(r){return r.querySelectorAll('td').length>=5;});}
function modelFromRow(row){var cells=row.querySelectorAll('td');if(cells.length<5)return null;var id=text(cells[0].querySelector('.cell-title'));if(!id)return null;var provider=text(cells[1].querySelector('.cell-title'))||text(cells[1]).split('provider ')[0].trim();var providerPolicy=text(cells[1].querySelector('.cell-sub'))||'unknown';var policy=stateText(cells[2]);var effective=stateText(cells[3]);var aliases=Array.prototype.slice.call(cells[4].querySelectorAll('.chip')).map(text).filter(function(v){return v&&v.charAt(0)!=='+';});var toggle=row.querySelector('[data-model-toggle]');return{id:id,provider:provider,providerPolicy:providerPolicy,policy:policy,effective:effective,aliases:aliases,toggle:toggle,row:row};}
function models(){return modelRows().map(modelFromRow).filter(Boolean);}
function routingRows(){return Array.prototype.slice.call(document.querySelectorAll('#routing-body tr')).map(function(row){var c=row.querySelectorAll('td');if(c.length<4)return null;return{alias:text(c[0].querySelector('.cell-title'))||text(c[0]),model:text(c[1].querySelector('.cell-title'))||text(c[1]),provider:text(c[2]),state:stateText(c[3])};}).filter(Boolean);}
function clsFor(v){v=String(v||'').toUpperCase();if(v==='ACTIVE'||v==='AVAILABLE'||v==='CALLABLE'||v==='CONFIGURED'||v.indexOf('ENABLED')>=0)return 'good';if(v==='DISABLED'||v==='MODEL_DISABLED'||v==='PROVIDER_DISABLED'||v==='RATE_LIMITED'||v==='NOT_CONFIGURED')return 'warn';if(v==='BROKEN'||v==='AUTH_ERROR'||v==='UPSTREAM_ERROR'||v==='ERROR')return 'bad';return '';}
function setChain(id,value,detail){var el=document.getElementById(id);if(!el)return;el.className='model-chain-step '+clsFor(value);var small=el.querySelector('small');if(small)small.textContent=detail||value||'Unknown';}
function consequence(m){var e=String(m.effective||'').toUpperCase();if(e==='AVAILABLE'||e==='CALLABLE')return{kind:'good',text:'Callable now. Aliases targeting this model can resolve operationally when their route state is ACTIVE.'};if(e==='MODEL_DISABLED')return{kind:'warn',text:'Model exists in the registry but model policy blocks invocation. Configured aliases remain visible and fail closed.'};if(e==='PROVIDER_DISABLED')return{kind:'warn',text:'Model policy allows use, but the provider is disabled. Aliases remain configured while runtime invocation is blocked.'};if(e==='BROKEN')return{kind:'bad',text:'The effective runtime relationship is broken. Treat dependent aliases as unavailable until backend state is repaired.'};return{kind:'warn',text:'Effective runtime is not callable according to the current authoritative Admin state.'};}
function select(id){var list=models();var m=list.find(function(x){return x.id===id;})||list[0];if(!m)return;selectedId=m.id;list.forEach(function(x){x.row.classList.toggle('model-selected',x.id===m.id);});document.getElementById('model-inspector-title').textContent=m.id;document.getElementById('model-inspector-provider').textContent=m.provider||'—';document.getElementById('model-inspector-policy').textContent=m.policy||'UNKNOWN';document.getElementById('model-inspector-provider-policy').textContent=m.providerPolicy||'unknown';var config=providerConfig(m.provider);document.getElementById('model-inspector-config').textContent=config;document.getElementById('model-inspector-effective').textContent=m.effective||'UNKNOWN';var status=document.getElementById('model-inspector-status');status.className='state '+String(m.effective||'UNKNOWN').replaceAll(' ','_');status.textContent=m.effective||'UNKNOWN';var aliases=document.getElementById('model-inspector-aliases');aliases.innerHTML='';if(m.aliases.length){m.aliases.forEach(function(a){var chip=document.createElement('span');chip.className='chip';chip.textContent=a;aliases.appendChild(chip);});}else{var chip=document.createElement('span');chip.className='chip';chip.textContent='no aliases';aliases.appendChild(chip);}var c=consequence(m),box=document.getElementById('model-inspector-consequence');box.className='model-consequence '+c.kind;box.textContent=c.text;setChain('chain-model',m.policy,m.policy==='ACTIVE'?'Enabled by model policy':m.policy);setChain('chain-provider',m.providerPolicy,m.providerPolicy);setChain('chain-config',config,config==='NOT EXPOSED'?'Not exposed by current model contract':config);setChain('chain-effective',m.effective,m.effective);var toggle=document.getElementById('model-inspector-toggle');if(m.toggle){toggle.disabled=false;toggle.textContent=text(m.toggle)||'Change model policy';toggle.dataset.selectedModel=m.id;}else{toggle.disabled=true;toggle.textContent='Action unavailable';}}
function updatePosture(){var total=parseInt(text(document.getElementById('md-total')),10),callable=parseInt(text(document.getElementById('md-callable')),10);var ring=document.getElementById('model-registry-ring');var pill=document.getElementById('model-posture-pill');if(Number.isFinite(total)&&Number.isFinite(callable)){var pct=total?Math.max(0,Math.min(100,callable/total*100)):0;ring.style.background='conic-gradient(#1dbb7b 0 '+pct+'%,#e8eef5 '+pct+'% 100%)';pill.textContent=total+' registered';}else{ring.style.background='conic-gradient(#e8eef5 0 100%)';pill.textContent='Unavailable';}}
function updateAliases(){var routes=routingRows();var stack=document.getElementById('model-alias-stack'),pill=document.getElementById('model-alias-pill');if(!stack)return;stack.innerHTML='';if(!routes.length){stack.innerHTML='<div class="model-alias-empty">No routing state returned.</div>';pill.textContent='0 aliases';return;}routes.slice(0,3).forEach(function(r){var b=document.createElement('button');b.type='button';b.className='model-alias-route';b.dataset.aliasTarget=r.model;var n=document.createElement('b');n.textContent=r.alias;var arrow=document.createElement('span');arrow.textContent='→';var target=document.createElement('span');target.textContent=r.model;var state=document.createElement('em');state.className=String(r.state||'UNKNOWN').replaceAll(' ','_');state.textContent=r.state||'UNKNOWN';b.append(n,arrow,target,state);stack.appendChild(b);});pill.textContent=routes.length+' configured';}
function refresh(){scheduled=false;updatePosture();updateAliases();var list=models();if(!list.length)return;if(!selectedId||!list.some(function(m){return m.id===selectedId;}))selectedId=list[0].id;select(selectedId);}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(refresh);}
var body=document.getElementById('models-body');if(body){body.addEventListener('click',function(e){if(e.target.closest('button'))return;var row=e.target.closest('tr');var m=row&&modelFromRow(row);if(m)select(m.id);});new MutationObserver(schedule).observe(body,{childList:true,subtree:true,characterData:true});}
var routing=document.getElementById('routing-body');if(routing)new MutationObserver(schedule).observe(routing,{childList:true,subtree:true,characterData:true});
var providers=document.getElementById('providers-body');if(providers)new MutationObserver(schedule).observe(providers,{childList:true,subtree:true,characterData:true});
['md-total','md-enabled','md-callable','md-blocked'].forEach(function(id){var el=document.getElementById(id);if(el)new MutationObserver(schedule).observe(el,{childList:true,subtree:true,characterData:true});});
document.getElementById('model-alias-stack').addEventListener('click',function(e){var b=e.target.closest('[data-alias-target]');if(!b)return;var target=b.dataset.aliasTarget;var search=document.getElementById('model-search');if(search){search.value=target;search.dispatchEvent(new Event('input',{bubbles:true}));setTimeout(function(){select(target);},0);}});
document.getElementById('model-inspector-toggle').addEventListener('click',function(){var list=models();var m=list.find(function(x){return x.id===selectedId;});if(m&&m.toggle)m.toggle.click();});
var filter=document.getElementById('model-filter');if(filter)filter.addEventListener('click',function(){setTimeout(schedule,0);});
var search=document.getElementById('model-search');if(search)search.addEventListener('input',function(){setTimeout(schedule,0);});
schedule();
})();`;

export function applyModelsFidelity(html: string): string {
  const start = html.indexOf('<section id="page-models"');
  const end = start >= 0 ? html.indexOf('<section id="page-mcp-tools"', start) : -1;
  if (start < 0 || end < 0) return html;
  let out = html.slice(0, start) + MODELS_FIDELITY_SECTION + '\n\n    ' + html.slice(end);
  out = out.replace('</head>', '<style>' + MODELS_FIDELITY_CSS + '</style></head>');
  out = out.replace('</body>', '<script>' + MODELS_FIDELITY_SCRIPT + '</script></body>');
  return out;
}
