export const OVERVIEW_FIDELITY_CSS = String.raw`
/* Overview fidelity: compact operational summary with substantial lower composition. */
#page-overview{padding:17px 24px 18px}
#page-overview .hero{height:83px}
#page-overview .hero .overview-live-note{position:absolute;right:16px;bottom:12px;height:24px;padding:0 8px;border:1px solid #d7e5f1;border-radius:12px;background:rgba(255,255,255,.82);display:flex;align-items:center;gap:6px;color:#58729d;font-size:6.2px}.overview-live-note i{width:6px;height:6px;border-radius:50%;background:#2c83df}
#page-overview .metrics{height:83px;margin-top:10px}
.overview-fidelity-grid{height:calc(100% - 186px);margin-top:10px;display:grid;grid-template-columns:1.28fr .86fr .86fr;grid-template-rows:1fr 1fr;gap:10px}.overview-fidelity-card{border:1px solid #dfe9f4;border-radius:12px;background:#fff;box-shadow:var(--shadow);overflow:hidden}.overview-fidelity-card.providers{grid-column:1;grid-row:1}.overview-fidelity-card.health{grid-column:2;grid-row:1}.overview-fidelity-card.runtime{grid-column:3;grid-row:1}.overview-fidelity-card.activity{grid-column:1 / span 2;grid-row:2}.overview-fidelity-card.actions{grid-column:3;grid-row:2}.overview-fidelity-head{height:40px;border-bottom:1px solid #e6edf5;padding:0 11px;display:flex;align-items:center}.overview-fidelity-head h2{margin:0;font-size:9.5px;color:#173d76}.overview-fidelity-head span{margin-left:7px;font-size:6.1px;color:#8395b6}.overview-fidelity-head .right{margin-left:auto}.overview-fidelity-head .link-btn{font-size:6.5px}
.overview-fidelity-card #overview-provider-list{height:calc(100% - 40px);overflow:auto;padding:6px 8px}.overview-fidelity-card .provider-mini{min-height:39px;border:1px solid #e6edf4;border-radius:8px;background:#fbfdff;padding:6px 8px;margin-bottom:5px}.overview-fidelity-card .provider-mini .name{font-size:7px!important;color:#254d83!important}.overview-fidelity-card .provider-mini .meta{font-size:5.8px!important;color:#8797b5!important}.overview-fidelity-card #overview-health{height:calc(100% - 40px);padding:8px 10px;overflow:auto}.overview-fidelity-card #overview-health .health-big{font-size:25px!important;color:#153e76!important}.overview-fidelity-card #overview-health .health-caption{font-size:6.2px!important;color:#8797b5!important}.overview-fidelity-card #overview-health .health-lines{margin-top:8px!important}.overview-fidelity-card #overview-health .health-line{min-height:25px!important;border-top:1px solid #e8eef4!important;font-size:6.2px!important}.overview-fidelity-card #overview-health .health-line b{color:#315381!important}.overview-runtime-body{height:calc(100% - 40px);padding:8px}.overview-runtime-row{min-height:36px;border:1px solid #e5ecf4;border-radius:8px;background:#fbfdff;margin-bottom:5px;padding:7px;display:grid;grid-template-columns:24px 1fr auto;gap:7px;align-items:center}.overview-runtime-row .ico{width:24px;height:24px;border-radius:7px;background:#eef6ff;color:#2979d8;display:grid;place-items:center}.overview-runtime-row .ico svg{width:12px;height:12px}.overview-runtime-row b{display:block;font-size:6.7px;color:#315382}.overview-runtime-row span{display:block;margin-top:2px;font-size:5.7px;color:#8999b6}.overview-runtime-row em{font-style:normal;font-size:6.2px;font-weight:800;color:#6079a2}.overview-runtime-row em.good{color:#0b8b5d}.overview-runtime-row em.warn{color:#a46c10}
.overview-fidelity-card #overview-activity-list{height:calc(100% - 40px);overflow:auto;padding:5px 8px}.overview-fidelity-card .activity-row{min-height:35px!important;border-bottom:1px solid #edf2f7!important;padding:6px 2px!important}.overview-fidelity-card .activity-row b{font-size:6.7px!important;color:#315382!important}.overview-fidelity-card .activity-row span,.overview-fidelity-card .activity-row time{font-size:5.7px!important;color:#8999b6!important}.overview-quick-list{height:calc(100% - 40px);padding:7px;display:grid;gap:5px}.overview-quick-action{border:1px solid #e4ebf3;border-radius:8px;background:#fbfdff;display:grid;grid-template-columns:27px 1fr;align-items:center;gap:7px;padding:0 7px;text-align:left;color:#315382}.overview-quick-action:hover{background:#f4f9ff;border-color:#cbddec}.overview-quick-action .ico{width:27px;height:27px;border-radius:7px;background:#eef6ff;color:#2779d8;display:grid;place-items:center}.overview-quick-action .ico svg{width:13px;height:13px}.overview-quick-action b{display:block;font-size:6.7px}.overview-quick-action span{display:block;margin-top:2px;font-size:5.7px;color:#8798b6}.overview-quick-action.warn .ico{background:#fff7e9;color:#a56b0b}
@media(max-width:1000px){.overview-fidelity-grid{grid-template-columns:1fr 1fr}.overview-fidelity-card.providers{grid-column:1}.overview-fidelity-card.health{grid-column:2}.overview-fidelity-card.runtime{display:none}.overview-fidelity-card.activity{grid-column:1}.overview-fidelity-card.actions{grid-column:2}}
`;

export const OVERVIEW_FIDELITY_SECTION = String.raw`
    <section id="page-overview" class="page active overview-fidelity-page">
      <section class="hero"><div class="eyebrow">Overview</div><h1>Operational Overview</h1><p>Live control-plane posture from D1, provider/model runtime state, routing, MCP registry and persisted evidence.</p><div class="hero-actions"><button class="btn" data-action="refresh-all"><svg><use href="#i-refresh"/></svg>Refresh</button></div><div class="overview-live-note"><i></i>Backend/runtime state is authoritative</div><svg class="hero-wave" viewBox="0 0 360 75" preserveAspectRatio="none"><path d="M0 53 C80 6 145 75 220 35S310 26 360 43" fill="none" stroke="#35aee3"/><path d="M0 66 C95 33 154 70 238 52S320 49 360 61" fill="none" stroke="#50cdb7"/></svg></section>
      <section class="metrics"><div class="metric"><div class="metric-label">Providers enabled</div><div id="ov-providers" class="metric-value">—</div><div id="ov-providers-sub" class="metric-sub">Loading runtime state</div><div class="spark"><svg><use href="#i-db"/></svg></div></div><div class="metric"><div class="metric-label">Models callable</div><div id="ov-models" class="metric-value">—</div><div id="ov-models-sub" class="metric-sub">Loading registry</div><div class="spark"><svg><use href="#i-cube"/></svg></div></div><div class="metric"><div class="metric-label">Active aliases</div><div id="ov-routes" class="metric-value">—</div><div id="ov-routes-sub" class="metric-sub">Loading routing</div><div class="spark"><svg><use href="#i-route"/></svg></div></div><div class="metric"><div class="metric-label">MCP tools</div><div id="ov-tools" class="metric-value">—</div><div id="ov-tools-sub" class="metric-sub">Runtime catalog</div><div class="spark"><svg><use href="#i-nodes"/></svg></div></div></section>
      <section class="overview-fidelity-grid"><article class="overview-fidelity-card providers"><div class="overview-fidelity-head"><h2>Providers</h2><span id="overview-provider-caption">Runtime-authoritative state</span><div class="right"><button class="link-btn" data-nav-jump="providers">View all</button></div></div><div id="overview-provider-list"><div class="loading-box"><div class="skeleton" style="width:180px"></div></div></div></article><article class="overview-fidelity-card health"><div class="overview-fidelity-head"><h2>System Health</h2><span>Persisted evidence</span><div class="right"><button class="link-btn" data-nav-jump="health">Details</button></div></div><div id="overview-health"><div class="loading-box"><div class="skeleton" style="width:120px"></div></div></div></article><article class="overview-fidelity-card runtime"><div class="overview-fidelity-head"><h2>Runtime Snapshot</h2><span>Cross-control-plane</span></div><div id="overview-runtime-body" class="overview-runtime-body"><div class="loading-box"><div class="skeleton" style="width:100px"></div></div></div></article><article class="overview-fidelity-card activity"><div class="overview-fidelity-head"><h2>Recent Activity</h2><span>Real audit events</span><div class="right"><button class="link-btn" data-nav-jump="logs">View evidence</button></div></div><div id="overview-activity-list"><div class="loading-box"><div class="skeleton" style="width:170px"></div></div></div></article><article class="overview-fidelity-card actions"><div class="overview-fidelity-head"><h2>Quick Actions</h2><span>Supported backend operations</span></div><div class="overview-quick-list"><button class="overview-quick-action" data-action="test-providers"><span class="ico"><svg class="icon"><use href="#i-bolt"/></svg></span><span><b>Test Providers</b><span>Run real provider health checks</span></span></button><button class="overview-quick-action" data-action="verify-tools"><span class="ico"><svg class="icon"><use href="#i-shield"/></svg></span><span><b>Verify Tool Catalog</b><span>Reload runtime-backed metadata</span></span></button><button class="overview-quick-action" data-nav-jump="logs"><span class="ico"><svg class="icon"><use href="#i-doc"/></svg></span><span><b>Open Evidence</b><span>Inspect persisted Admin activity</span></span></button></div></article></section>
    </section>
`;

export const OVERVIEW_FIDELITY_SCRIPT = String.raw`(function(){
'use strict';
var scheduled=false;
function text(el){return el?el.textContent.trim():'';}
function row(icon,title,sub,value,kind){return '<div class="overview-runtime-row"><span class="ico"><svg class="icon"><use href="#'+icon+'"/></svg></span><div><b>'+title+'</b><span>'+sub+'</span></div><em class="'+(kind||'')+'">'+value+'</em></div>';}
function refresh(){scheduled=false;var routes=text(document.getElementById('ov-routes')),routeSub=text(document.getElementById('ov-routes-sub')),tools=text(document.getElementById('ov-tools')),models=text(document.getElementById('ov-models')),providers=text(document.getElementById('ov-providers'));var unavailable=/^(\d+)/.exec(routeSub);var u=unavailable?unavailable[1]:'—';var body=document.getElementById('overview-runtime-body');body.innerHTML=row('i-route','Routing',routeSub||'effective alias state',routes,routeSub.indexOf('0 unavailable')>=0?'good':'warn')+row('i-nodes','MCP catalog','runtime-backed tools/list metadata',tools,'good')+row('i-cube','Model / provider posture',providers+' enabled providers',models,'');}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(refresh);}
['ov-routes','ov-routes-sub','ov-tools','ov-models','ov-providers'].forEach(function(id){var el=document.getElementById(id);if(el)new MutationObserver(schedule).observe(el,{childList:true,subtree:true,characterData:true});});schedule();
})();`;

export function applyOverviewFidelity(html: string): string {
  const start = html.indexOf('<section id="page-overview"');
  const end = start >= 0 ? html.indexOf('<section id="page-providers"', start) : -1;
  if (start < 0 || end < 0) return html;
  let out = html.slice(0, start) + OVERVIEW_FIDELITY_SECTION + '\n\n    ' + html.slice(end);
  out = out.replace('</head>', '<style>' + OVERVIEW_FIDELITY_CSS + '</style></head>');
  out = out.replace('</body>', '<script>' + OVERVIEW_FIDELITY_SCRIPT + '</script></body>');
  return out;
}
