export const PROVIDERS_FIDELITY_CSS = String.raw`
/* Providers fidelity layer: provider operational posture, fleet table, diagnostic inspector. */
#page-providers{padding:17px 24px 18px}
#page-providers .hero{height:83px}
.provider-fidelity-summary{height:72px;margin-top:10px;display:grid;grid-template-columns:1.25fr repeat(4,1fr);gap:9px}
.provider-fleet-lead,.provider-posture-stat{border:1px solid #dfe9f4;border-radius:11px;background:#fff;box-shadow:var(--shadow);overflow:hidden}
.provider-fleet-lead{padding:10px 12px;background:radial-gradient(130px 65px at 95% 15%,rgba(38,188,222,.10),transparent 70%),#fff}.provider-fleet-lead span{display:block;font-size:7.1px;letter-spacing:.08em;text-transform:uppercase;color:#7288b3;font-weight:800}.provider-fleet-lead b{display:block;margin-top:4px;font-size:13px;color:#173f7b;letter-spacing:-.2px}.provider-fleet-lead small{display:block;margin-top:3px;font-size:7px;color:#8395b6}
.provider-posture-stat{padding:10px 11px;position:relative}.provider-posture-stat span{display:block;font-size:7px;color:#7c8fb5;font-weight:700}.provider-posture-stat b{display:block;margin-top:3px;font-size:17px;color:#153b73;line-height:1}.provider-posture-stat small{display:block;margin-top:3px;font-size:6.4px;color:#8b9ab8}.provider-posture-stat i{position:absolute;right:9px;top:10px;width:23px;height:23px;border-radius:7px;background:#eef6ff;color:#247bdc;display:grid;place-items:center}.provider-posture-stat i svg{width:13px;height:13px}.provider-posture-stat.good i{background:#ecfaf4;color:#0b9764}.provider-posture-stat.warn i{background:#fff8e9;color:#a56b0b}
.provider-fidelity-workbench{height:calc(100% - 175px);margin-top:10px;display:grid;grid-template-columns:minmax(0,1.78fr) minmax(285px,.72fr);gap:10px}
.provider-fleet-card,.provider-ops-inspector{height:100%;border:1px solid #dfe9f4;border-radius:12px;background:#fff;box-shadow:var(--shadow);overflow:hidden}
.provider-fleet-toolbar{height:43px;border-bottom:1px solid #e5edf6;display:flex;align-items:center;padding:0 11px;gap:8px}.provider-fleet-title{min-width:118px}.provider-fleet-title b{display:block;font-size:10px;color:#173e77}.provider-fleet-title span{display:block;margin-top:2px;font-size:7px;color:#8596b7}.provider-fleet-toolbar .searchbox{min-width:205px;height:29px}.provider-fleet-toolbar .summary{margin-left:auto}.provider-fleet-toolbar .btn[disabled]{opacity:.45}
.provider-fleet-table{height:calc(100% - 43px);overflow:auto}.provider-fleet-table .data-table th{height:30px}.provider-fleet-table .data-table td{height:46px}.provider-fleet-table tbody tr{cursor:pointer;transition:.14s}.provider-fleet-table tbody tr.provider-selected{background:linear-gradient(90deg,#f0f7ff,#fbfdff);box-shadow:inset 3px 0 0 #2580e8}.provider-fleet-table .row-actions{position:relative;z-index:2}.provider-fleet-table .data-table td:nth-child(7) .row-actions{display:flex;gap:4px;flex-wrap:nowrap}.provider-fleet-table .data-table td:nth-child(7) .btn{height:24px;padding:0 6px;font-size:7.2px}
.provider-ops-inspector{display:flex;flex-direction:column}.provider-ops-head{height:58px;border-bottom:1px solid #e5edf6;padding:9px 11px;display:flex;align-items:center;gap:9px;background:linear-gradient(180deg,#fff,#fbfdff)}.provider-ops-icon{width:32px;height:32px;border-radius:9px;background:linear-gradient(145deg,#edf6ff,#eefcf8);color:#2279dd;display:grid;place-items:center;flex:none}.provider-ops-icon svg{width:16px;height:16px}.provider-ops-copy{min-width:0}.provider-ops-copy span{display:block;font-size:6.5px;text-transform:uppercase;letter-spacing:.08em;color:#8797b5;font-weight:800}.provider-ops-copy b{display:block;margin-top:2px;font-size:9.8px;color:#173d77;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.provider-ops-state{margin-left:auto}
.provider-ops-body{flex:1;min-height:0;overflow:auto;padding:9px 10px}.provider-ops-section{margin-bottom:9px}.provider-ops-section>span{display:block;margin-bottom:5px;font-size:6.5px;text-transform:uppercase;letter-spacing:.08em;color:#8395b5;font-weight:800}.provider-ops-grid{display:grid;grid-template-columns:1fr 1fr;gap:5px}.provider-ops-fact{min-height:38px;border:1px solid #e3ebf3;border-radius:8px;background:#fbfdff;padding:7px}.provider-ops-fact small{display:block;font-size:6.2px;color:#8a9abb}.provider-ops-fact b{display:block;margin-top:3px;font-size:7.7px;color:#244d85;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.provider-route-impact{display:flex;gap:4px;flex-wrap:wrap}.provider-route-impact .chip{max-width:118px}.provider-diag-box{border:1px solid #dce7f2;border-radius:8px;background:#f7fbff;padding:8px}.provider-diag-head{display:flex;align-items:center;gap:6px}.provider-diag-head i{width:7px;height:7px;border-radius:50%;background:#91a2bb}.provider-diag-head b{font-size:7.6px;color:#315384}.provider-diag-box.HEALTHY .provider-diag-head i{background:#11ad69}.provider-diag-box.RATE_LIMITED .provider-diag-head i{background:#d39b2e}.provider-diag-box.AUTH_ERROR .provider-diag-head i,.provider-diag-box.UPSTREAM_ERROR .provider-diag-head i{background:#d65b69}.provider-diag-box small{display:block;margin-top:5px;font-size:6.8px;line-height:1.45;color:#7287ad}.provider-diag-meta{margin-top:6px;display:grid;grid-template-columns:1fr 1fr;gap:5px}.provider-diag-meta div{border-top:1px solid #e6edf4;padding-top:5px}.provider-diag-meta span{display:block;font-size:5.9px;color:#8c9bb7}.provider-diag-meta b{display:block;margin-top:2px;font-size:7px;color:#355984}
.provider-ops-actions{height:72px;border-top:1px solid #e5edf6;padding:7px 9px;display:grid;grid-template-columns:1fr 1fr;gap:6px}.provider-ops-actions .btn{height:27px;justify-content:center}.provider-ops-actions .btn[disabled]{opacity:.46}
@media(max-width:1000px){.provider-fidelity-summary{grid-template-columns:1.25fr repeat(3,1fr)}.provider-fidelity-summary .provider-posture-stat:last-child{display:none}.provider-fidelity-workbench{grid-template-columns:1fr}.provider-ops-inspector{display:none}}
`;

export const PROVIDERS_FIDELITY_SECTION = String.raw`
    <section id="page-providers" class="page providers-fidelity-page">
      <section class="hero"><div class="eyebrow">Providers</div><h1>Provider Runtime & Credentials</h1><p>Operational posture across enablement, health, BYOK configuration, owned models and routing impact.</p><div class="hero-actions"><button class="btn" disabled title="No create-provider backend contract exists">Add Provider</button><button class="btn" data-action="refresh-providers"><svg><use href="#i-refresh"/></svg>Refresh</button></div><svg class="hero-wave" viewBox="0 0 360 75" preserveAspectRatio="none"><path d="M0 53 C80 6 145 75 220 35S310 26 360 43" fill="none" stroke="#35aee3"/><path d="M0 66 C95 33 154 70 238 52S320 49 360 61" fill="none" stroke="#50cdb7"/></svg></section>

      <section class="provider-fidelity-summary" aria-label="Provider fleet posture">
        <article class="provider-fleet-lead"><span>PROVIDER FLEET</span><b>Operational posture</b><small>Enabled ≠ healthy. Configured ≠ reachable.</small></article>
        <article class="provider-posture-stat"><span>Registered</span><b id="pr-total">—</b><small>Provider registry</small><i><svg class="icon"><use href="#i-db"/></svg></i></article>
        <article class="provider-posture-stat"><span>Enabled</span><b id="pr-enabled">—</b><small>Runtime policy</small><i><svg class="icon"><use href="#i-bolt"/></svg></i></article>
        <article class="provider-posture-stat good"><span>Healthy</span><b id="pr-healthy">—</b><small>Persisted state</small><i><svg class="icon"><use href="#i-heart"/></svg></i></article>
        <article class="provider-posture-stat"><span>BYOK configured</span><b id="pr-configured">—</b><small>Safe binding signal</small><i><svg class="icon"><use href="#i-key"/></svg></i></article>
      </section>

      <section class="provider-fidelity-workbench">
        <article class="provider-fleet-card">
          <div class="provider-fleet-toolbar"><div class="provider-fleet-title"><b>Provider Fleet</b><span>Runtime-authoritative registry</span></div><div class="searchbox"><svg><use href="#i-search"/></svg><input id="provider-search" placeholder="Search providers"></div><button id="provider-filter" class="btn tiny" data-filter="all">All status</button><span id="provider-summary" class="summary">Loading…</span></div>
          <div class="provider-fleet-table"><table class="data-table"><thead><tr><th style="width:18%">Provider</th><th style="width:10%">Runtime</th><th style="width:12%">Health</th><th style="width:13%">Models</th><th style="width:14%">Routing</th><th style="width:11%">BYOK</th><th style="width:22%">Operational actions</th></tr></thead><tbody id="providers-body"><tr><td colspan="7"><div class="loading-box"><div class="skeleton" style="width:220px"></div></div></td></tr></tbody></table></div>
        </article>

        <aside class="provider-ops-inspector" aria-label="Selected provider operational inspector">
          <div class="provider-ops-head"><div class="provider-ops-icon"><svg class="icon"><use href="#i-db"/></svg></div><div class="provider-ops-copy"><span>Operational Inspector</span><b id="provider-ops-title">Select a provider</b></div><span id="provider-ops-state" class="state UNKNOWN">UNKNOWN</span></div>
          <div class="provider-ops-body"><div class="provider-ops-section"><span>Provider posture</span><div class="provider-ops-grid"><div class="provider-ops-fact"><small>Provider ID</small><b id="provider-ops-id">—</b></div><div class="provider-ops-fact"><small>Runtime policy</small><b id="provider-ops-runtime">—</b></div><div class="provider-ops-fact"><small>Health</small><b id="provider-ops-health">—</b></div><div class="provider-ops-fact"><small>Owned / enabled models</small><b id="provider-ops-models">—</b></div><div class="provider-ops-fact"><small>BYOK</small><b id="provider-ops-byok">—</b></div><div class="provider-ops-fact"><small>Authority</small><b>D1 / Admin API</b></div></div></div><div class="provider-ops-section"><span>Routing impact</span><div id="provider-ops-routes" class="provider-route-impact"><span class="chip">none selected</span></div></div><div class="provider-ops-section"><span>Latest diagnostic evidence</span><div id="provider-ops-diagnostic" class="provider-diag-box"><div class="provider-diag-head"><i></i><b>No provider selected</b></div><small>Health evidence is sourced from the existing Admin health history. No synthetic latency or uptime is generated.</small><div class="provider-diag-meta"><div><span>Latency</span><b id="provider-ops-latency">—</b></div><div><span>Checked</span><b id="provider-ops-checked">—</b></div></div></div></div></div>
          <div class="provider-ops-actions"><button id="provider-ops-toggle" class="btn" disabled>Enable / disable</button><button id="provider-ops-test" class="btn" disabled>Health test</button><button id="provider-ops-credential" class="btn" disabled>Set / rotate credential</button><button id="provider-ops-remove" class="btn danger" disabled>Remove credential</button></div>
        </aside>
      </section>
    </section>
`;

export const PROVIDERS_FIDELITY_SCRIPT = String.raw`(function(){
'use strict';
var selectedId=null,scheduled=false;
function text(el){return el?el.textContent.trim():'';}
function stateText(cell){var s=cell&&cell.querySelector('.state');return text(s)||text(cell)||'UNKNOWN';}
function rows(){return Array.prototype.slice.call(document.querySelectorAll('#providers-body tr')).filter(function(r){return r.querySelectorAll('td').length>=7;});}
function providerFromRow(row){var c=row.querySelectorAll('td');if(c.length<7)return null;var name=text(c[0].querySelector('.cell-title'));var id=text(c[0].querySelector('.cell-sub'));if(!id)return null;var routes=Array.prototype.slice.call(c[4].querySelectorAll('.chip')).map(text).filter(function(v){return v&&v.charAt(0)!=='+';});return{id:id,name:name||id,runtime:stateText(c[1]),health:stateText(c[2]),models:text(c[3].querySelector('.cell-title'))||text(c[3]),routes:routes,byok:stateText(c[5]),toggle:c[6].querySelector('[data-provider-toggle]'),test:c[6].querySelector('[data-provider-test]'),credential:c[6].querySelector('[data-provider-credential]'),remove:c[6].querySelector('[data-provider-credential-remove]'),row:row};}
function providers(){return rows().map(providerFromRow).filter(Boolean);}
function latestHealth(providerId){var list=Array.prototype.slice.call(document.querySelectorAll('#health-body tr'));for(var i=0;i<list.length;i++){var c=list[i].querySelectorAll('td');if(c.length<5)continue;var provider=text(c[1].querySelector('.cell-title'))||text(c[1]);if(provider!==providerId)continue;return{checked:text(c[0]),state:stateText(c[2]),latency:text(c[3]),detail:text(c[4])};}return null;}
function chips(target,values){target.innerHTML='';if(values&&values.length){values.forEach(function(v){var s=document.createElement('span');s.className='chip';s.textContent=v;target.appendChild(s);});}else{var s=document.createElement('span');s.className='chip';s.textContent='no routing aliases';target.appendChild(s);}}
function bindAction(id,source,label){var b=document.getElementById(id);if(!b)return;if(source){b.disabled=false;b.textContent=label||text(source);b.dataset.delegate='1';}else{b.disabled=true;b.textContent=label||'Unavailable';delete b.dataset.delegate;}}
function select(id){var list=providers();var p=list.find(function(x){return x.id===id;})||list[0];if(!p)return;selectedId=p.id;list.forEach(function(x){x.row.classList.toggle('provider-selected',x.id===p.id);});document.getElementById('provider-ops-title').textContent=p.name;document.getElementById('provider-ops-id').textContent=p.id;document.getElementById('provider-ops-runtime').textContent=p.runtime;document.getElementById('provider-ops-health').textContent=p.health;document.getElementById('provider-ops-models').textContent=p.models;document.getElementById('provider-ops-byok').textContent=p.byok;var st=document.getElementById('provider-ops-state');st.className='state '+String(p.health||'UNKNOWN').replaceAll(' ','_');st.textContent=p.health||'UNKNOWN';chips(document.getElementById('provider-ops-routes'),p.routes);var h=latestHealth(p.id),diag=document.getElementById('provider-ops-diagnostic');if(h){diag.className='provider-diag-box '+String(h.state||'UNKNOWN').replaceAll(' ','_');diag.querySelector('.provider-diag-head b').textContent=h.state||'UNKNOWN';diag.querySelector('small').textContent=h.detail||'Latest persisted provider health evidence.';document.getElementById('provider-ops-latency').textContent=h.latency||'—';document.getElementById('provider-ops-checked').textContent=h.checked||'—';}else{diag.className='provider-diag-box';diag.querySelector('.provider-diag-head b').textContent='No persisted check loaded';diag.querySelector('small').textContent='Run the supported provider health test to create real diagnostic evidence. No latency is inferred.';document.getElementById('provider-ops-latency').textContent='—';document.getElementById('provider-ops-checked').textContent='—';}bindAction('provider-ops-toggle',p.toggle,text(p.toggle)||'Enable / disable');bindAction('provider-ops-test',p.test,'Run health test');bindAction('provider-ops-credential',p.credential,p.byok==='CONFIGURED'?'Rotate credential':'Set credential');bindAction('provider-ops-remove',p.remove,'Remove credential');}
function refresh(){scheduled=false;var list=providers();if(!list.length)return;if(!selectedId||!list.some(function(p){return p.id===selectedId;}))selectedId=list[0].id;select(selectedId);}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(refresh);}
var body=document.getElementById('providers-body');if(body){body.addEventListener('click',function(e){if(e.target.closest('button'))return;var row=e.target.closest('tr');var p=row&&providerFromRow(row);if(p)select(p.id);});new MutationObserver(schedule).observe(body,{childList:true,subtree:true,characterData:true});}
var health=document.getElementById('health-body');if(health)new MutationObserver(schedule).observe(health,{childList:true,subtree:true,characterData:true});
['provider-ops-toggle','provider-ops-test','provider-ops-credential','provider-ops-remove'].forEach(function(id){var b=document.getElementById(id);if(!b)return;b.addEventListener('click',function(){var p=providers().find(function(x){return x.id===selectedId;});if(!p)return;var map={'provider-ops-toggle':'toggle','provider-ops-test':'test','provider-ops-credential':'credential','provider-ops-remove':'remove'};var source=p[map[id]];if(source)source.click();});});
var search=document.getElementById('provider-search');if(search)search.addEventListener('input',function(){setTimeout(schedule,0);});var filter=document.getElementById('provider-filter');if(filter)filter.addEventListener('click',function(){setTimeout(schedule,0);});
schedule();
})();`;

export function applyProvidersFidelity(html: string): string {
  const start = html.indexOf('<section id="page-providers"');
  const end = start >= 0 ? html.indexOf('<section id="page-models"', start) : -1;
  if (start < 0 || end < 0) return html;
  let out = html.slice(0, start) + PROVIDERS_FIDELITY_SECTION + '\n\n    ' + html.slice(end);
  out = out.replace('</head>', '<style>' + PROVIDERS_FIDELITY_CSS + '</style></head>');
  out = out.replace('</body>', '<script>' + PROVIDERS_FIDELITY_SCRIPT + '</script></body>');
  return out;
}
