export const ROUTING_FIDELITY_CSS = String.raw`
/* Routing fidelity: configured graph + effective runtime inspector, real routing rows only. */
#page-routing{padding:17px 24px 18px}
#page-routing .hero{height:83px}
.routing-contract-fidelity{height:61px;margin-top:10px;border:1px solid #dfe9f4;border-radius:11px;background:#fff;box-shadow:var(--shadow);display:grid;grid-template-columns:130px 1fr auto;align-items:center;gap:10px;padding:0 12px}.routing-contract-title span{display:block;font-size:6.4px;letter-spacing:.09em;color:#8295b6;font-weight:800}.routing-contract-title b{display:block;margin-top:3px;font-size:9px;color:#173d76}.routing-contract-flow{display:grid;grid-template-columns:1fr 18px 1fr 18px 1fr 18px 1fr;align-items:center}.routing-contract-node{text-align:center}.routing-contract-node i{width:22px;height:22px;border-radius:7px;background:#eef6ff;color:#2779d9;display:grid;place-items:center;margin:0 auto 3px}.routing-contract-node i svg{width:12px;height:12px}.routing-contract-node b{display:block;font-size:6.3px;color:#315382}.routing-contract-node span{display:block;margin-top:1px;font-size:5.5px;color:#8999b7}.routing-contract-link{height:1px;background:linear-gradient(90deg,#cbd9e7,#66b8df,#61ccb4)}.routing-contract-badge{height:25px;padding:0 8px;border-radius:13px;border:1px solid #dce7f3;background:#f8fbff;display:flex;align-items:center;gap:6px;font-size:6.1px;color:#5f769d}.routing-contract-badge i{width:6px;height:6px;border-radius:50%;background:#2b82df}
.routing-fidelity-workspace{height:calc(100% - 164px);margin-top:10px;display:grid;grid-template-columns:minmax(0,1.65fr) minmax(285px,.75fr);grid-template-rows:minmax(0,1fr) 108px;gap:10px}
.routing-topology-card,.routing-inspector-wrap,.routing-rules-wrap{border:1px solid #dfe9f4;border-radius:12px;background:#fff;box-shadow:var(--shadow);overflow:hidden}.routing-topology-card{grid-column:1;grid-row:1}.routing-inspector-wrap{grid-column:2;grid-row:1 / span 2}.routing-rules-wrap{grid-column:1;grid-row:2}
.routing-topology-head{height:41px;border-bottom:1px solid #e6edf5;padding:0 11px;display:flex;align-items:center}.routing-topology-head h2{margin:0;font-size:9.5px;color:#173d76}.routing-topology-head span{margin-left:7px;font-size:6.2px;color:#8395b6}.routing-topology-legend{margin-left:auto;display:flex;gap:8px}.routing-topology-legend span{display:flex;align-items:center;gap:4px;font-size:5.8px;color:#778bad}.routing-topology-legend i{width:6px;height:6px;border-radius:50%;background:#12ad69}.routing-topology-legend span:nth-child(2) i{background:#d39b2e}.routing-topology-legend span:nth-child(3) i{background:#d45f6b}
.routing-topology{height:calc(100% - 41px);position:relative;background:radial-gradient(180px 100px at 52% 48%,rgba(40,151,213,.08),transparent 70%),linear-gradient(180deg,#fbfdff,#f8fbff);overflow:hidden}.routing-topology-lines{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}.routing-topology-lines path{fill:none;stroke:#bdd3e5;stroke-width:1.2}.routing-topology-lines path.ACTIVE{stroke:#58bfa3}.routing-topology-lines path.MODEL_DISABLED,.routing-topology-lines path.PROVIDER_DISABLED{stroke:#d9af67;stroke-dasharray:4 3}.routing-topology-lines path.BROKEN{stroke:#d88b97;stroke-dasharray:3 3}.routing-column-label{position:absolute;top:9px;font-size:5.7px;letter-spacing:.08em;color:#8a9ab8;font-weight:800}.routing-column-label.alias{left:15px}.routing-column-label.target{right:82px}.routing-node{position:absolute;height:37px;border:1px solid #dfe8f2;border-radius:9px;background:#fff;box-shadow:0 5px 15px rgba(45,80,117,.05);display:flex;align-items:center;gap:7px;padding:0 8px;text-align:left;min-width:0;cursor:pointer}.routing-node:hover{border-color:#bfd5e9;box-shadow:0 7px 18px rgba(45,80,117,.08)}.routing-node.alias{left:15px;width:145px}.routing-node.target{right:15px;width:190px}.routing-node .ico{width:25px;height:25px;border-radius:7px;background:#eef6ff;color:#2779d9;display:grid;place-items:center;flex:none}.routing-node .ico svg{width:13px;height:13px}.routing-node b{display:block;font-size:6.9px;color:#254d83;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.routing-node span{display:block;margin-top:2px;font-size:5.6px;color:#8697b6;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.routing-node em{margin-left:auto;font-style:normal;width:7px;height:7px;border-radius:50%;background:#9eacbc;flex:none}.routing-node.ACTIVE em{background:#12ad69}.routing-node.MODEL_DISABLED em,.routing-node.PROVIDER_DISABLED em{background:#d39b2e}.routing-node.BROKEN em{background:#d45f6b}.routing-resolver{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:94px;height:68px;border:1px solid #cfe1ef;border-radius:13px;background:linear-gradient(145deg,#fff,#f3f9ff);box-shadow:0 10px 26px rgba(37,92,140,.09);display:grid;place-items:center;text-align:center;z-index:2}.routing-resolver:before{content:"";position:absolute;inset:-13px;border:1px solid rgba(70,153,204,.11);border-radius:19px}.routing-resolver svg{width:18px;height:18px;color:#2879d8}.routing-resolver b{display:block;margin-top:3px;font-size:6.7px;color:#2c4f80}.routing-resolver span{display:block;margin-top:2px;font-size:5.4px;color:#8798b5}
.routing-inspector-wrap #route-inspector{height:100%;border:0!important;border-radius:0!important;box-shadow:none!important;padding:12px!important;overflow:auto}.routing-inspector-wrap #route-inspector h2{font-size:14px!important;color:#173e77!important;margin:4px 0!important}.routing-inspector-wrap #route-inspector p{font-size:6.6px!important;color:#778cad!important}.routing-inspector-wrap #route-inspector .facts{display:grid!important;grid-template-columns:1fr 1fr!important;gap:6px!important;margin-top:10px!important}.routing-inspector-wrap #route-inspector .fact{min-height:43px!important;border:1px solid #e3eaf2!important;border-radius:8px!important;background:#fbfdff!important;padding:7px!important}.routing-inspector-wrap #route-inspector .fact span{font-size:5.8px!important;color:#8999b6!important}.routing-inspector-wrap #route-inspector .fact b{display:block!important;margin-top:4px!important;font-size:6.7px!important;color:#315382!important;overflow:hidden!important;text-overflow:ellipsis!important}.routing-inspector-wrap #route-inspector .policy{margin-top:9px!important;border:1px solid #dce7f2!important;border-radius:8px!important;background:#f6fbff!important;padding:8px!important;font-size:6.3px!important;line-height:1.45!important;color:#667fa8!important}
.routing-rules-head{height:36px;border-bottom:1px solid #e7edf4;padding:0 10px;display:flex;align-items:center}.routing-rules-head h2{margin:0;font-size:8.7px;color:#173d76}.routing-rules-head span{margin-left:auto;font-size:6px;color:#8596b5}.routing-rules-wrap #route-strip{height:71px;border:0!important;border-radius:0!important;box-shadow:none!important;display:flex!important;align-items:center!important;gap:6px!important;padding:7px 9px!important;overflow:auto!important}.routing-rules-wrap .route-pill{height:53px!important;min-width:145px!important;border:1px solid #e1e9f2!important;border-radius:8px!important;background:#fbfdff!important;padding:7px 8px!important;text-align:left!important}.routing-rules-wrap .route-pill b{font-size:6.8px!important;color:#274e83!important}.routing-rules-wrap .route-pill span{font-size:5.6px!important;line-height:1.35!important;color:#8294b4!important}.routing-raw-table{display:none}
@media(max-width:1000px){.routing-fidelity-workspace{grid-template-columns:1fr;grid-template-rows:1fr 108px}.routing-inspector-wrap{display:none}.routing-topology-card,.routing-rules-wrap{grid-column:1}.routing-topology-card{grid-row:1}.routing-rules-wrap{grid-row:2}}
`;

export const ROUTING_FIDELITY_SECTION = String.raw`
    <section id="page-routing" class="page routing-fidelity-page">
      <section class="hero"><div class="eyebrow">Routing</div><h1>Routing Control Plane</h1><p>Configured aliases stay distinct from operational runtime state: Alias → Target Model → Provider → Effective State.</p><div class="hero-actions"><button class="btn" data-action="refresh-routing"><svg><use href="#i-refresh"/></svg>Refresh</button></div><svg class="hero-wave" viewBox="0 0 360 75" preserveAspectRatio="none"><path d="M0 53 C80 6 145 75 220 35S310 26 360 43" fill="none" stroke="#35aee3"/><path d="M0 66 C95 33 154 70 238 52S320 49 360 61" fill="none" stroke="#50cdb7"/></svg></section>
      <section class="routing-contract-fidelity"><div class="routing-contract-title"><span>ROUTING CONTRACT</span><b>Fail-closed resolution</b></div><div class="routing-contract-flow"><div class="routing-contract-node"><i><svg class="icon"><use href="#i-route"/></svg></i><b>Alias</b><span>configured rule</span></div><div class="routing-contract-link"></div><div class="routing-contract-node"><i><svg class="icon"><use href="#i-cube"/></svg></i><b>Model</b><span>model policy</span></div><div class="routing-contract-link"></div><div class="routing-contract-node"><i><svg class="icon"><use href="#i-db"/></svg></i><b>Provider</b><span>provider policy</span></div><div class="routing-contract-link"></div><div class="routing-contract-node"><i><svg class="icon"><use href="#i-shield"/></svg></i><b>Runtime</b><span>effective state</span></div></div><div class="routing-contract-badge"><i></i><span>D1 authoritative</span></div></section>
      <section class="routing-fidelity-workspace"><article class="routing-topology-card"><div class="routing-topology-head"><h2>Alias resolution map</h2><span>real configured routes</span><div class="routing-topology-legend"><span><i></i>ACTIVE</span><span><i></i>BLOCKED</span><span><i></i>BROKEN</span></div></div><div id="routing-topology" class="routing-topology"><span class="routing-column-label alias">PUBLIC ALIASES</span><span class="routing-column-label target">EFFECTIVE TARGETS</span><svg id="routing-topology-lines" class="routing-topology-lines"></svg><div class="routing-resolver"><div><svg class="icon"><use href="#i-route"/></svg><b>D1 Resolver</b><span>configured ≠ callable</span></div></div><div id="routing-topology-nodes"></div></div></article><aside class="routing-inspector-wrap"><div id="route-inspector" class="route-inspector"><div class="empty"><b>Select an alias</b><span>Inspect the real target and fail-closed state.</span></div></div></aside><article class="routing-rules-wrap"><div class="routing-rules-head"><h2>Configured routing rules</h2><span>click a rule to inspect</span></div><section id="route-strip" class="route-strip"><div class="loading-box" style="width:100%"><div class="skeleton" style="width:230px"></div></div></section><div class="routing-raw-table"><table><tbody id="routing-body"></tbody></table></div></article></section>
    </section>
`;

export const ROUTING_FIDELITY_SCRIPT = String.raw`(function(){
'use strict';
var scheduled=false;
function text(el){return el?el.textContent.trim():'';}
function stateText(cell){var s=cell&&cell.querySelector('.state');return text(s)||text(cell)||'UNKNOWN';}
function routes(){return Array.prototype.slice.call(document.querySelectorAll('#routing-body tr')).map(function(row){var c=row.querySelectorAll('td');if(c.length<4)return null;return{alias:text(c[0].querySelector('.cell-title'))||text(c[0]),model:text(c[1].querySelector('.cell-title'))||text(c[1]),provider:text(c[2]),state:stateText(c[3])};}).filter(Boolean);}
function node(tag,cls,top,title,sub,state,alias){var b=document.createElement('button');b.type='button';b.className='routing-node '+cls+' '+String(state||'UNKNOWN').replaceAll(' ','_');b.style.top=top+'px';if(alias)b.dataset.routingAlias=alias;var ico=document.createElement('span');ico.className='ico';ico.innerHTML='<svg class="icon"><use href="#'+(cls==='alias'?'i-route':'i-cube')+'"/></svg>';var copy=document.createElement('div');copy.style.minWidth='0';var strong=document.createElement('b');strong.textContent=title;var small=document.createElement('span');small.textContent=sub;copy.append(strong,small);var dot=document.createElement('em');b.append(ico,copy,dot);return b;}
function draw(){scheduled=false;var list=routes(),host=document.getElementById('routing-topology-nodes'),svg=document.getElementById('routing-topology-lines'),canvas=document.getElementById('routing-topology');host.innerHTML='';svg.innerHTML='';if(!list.length)return;var height=canvas.clientHeight||255,shown=list.slice(0,4),aliasYs=[],targetMap=new Map();shown.forEach(function(r,i){var y=35+i*Math.max(42,(height-75)/Math.max(1,shown.length-1));aliasYs.push(y);host.appendChild(node('button','alias',y,r.alias,r.state,r.state,r.alias));if(!targetMap.has(r.model))targetMap.set(r.model,{model:r.model,provider:r.provider,states:[]});targetMap.get(r.model).states.push(r.state);});var targets=Array.from(targetMap.values()).slice(0,4),targetYs=[];targets.forEach(function(t,i){var y=47+i*Math.max(48,(height-96)/Math.max(1,targets.length-1));targetYs.push(y);var state=t.states.every(function(s){return s==='ACTIVE';})?'ACTIVE':t.states[0];host.appendChild(node('button','target',y,t.model,t.provider,state,null));});var w=canvas.clientWidth||700;shown.forEach(function(r,i){var ti=targets.findIndex(function(t){return t.model===r.model;}),ay=aliasYs[i]+18,ty=(targetYs[Math.max(0,ti)]||47)+18;var p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d','M160 '+ay+' C '+(w*.38)+' '+ay+', '+(w*.62)+' '+ty+', '+(w-205)+' '+ty);p.setAttribute('class',String(r.state||'UNKNOWN').replaceAll(' ','_'));svg.appendChild(p);});}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(draw);}
var body=document.getElementById('routing-body');if(body)new MutationObserver(schedule).observe(body,{childList:true,subtree:true,characterData:true});var host=document.getElementById('routing-topology-nodes');host.addEventListener('click',function(e){var b=e.target.closest('[data-routing-alias]');if(!b)return;var alias=b.dataset.routingAlias;var pill=Array.prototype.slice.call(document.querySelectorAll('#route-strip [data-route-select]')).find(function(x){return x.dataset.routeSelect===alias;});if(pill)pill.click();});window.addEventListener('resize',schedule);schedule();
})();`;

export function applyRoutingFidelity(html: string): string {
  const start = html.indexOf('<section id="page-routing"');
  const end = start >= 0 ? html.indexOf('<section id="page-health"', start) : -1;
  if (start < 0 || end < 0) return html;
  let out = html.slice(0, start) + ROUTING_FIDELITY_SECTION + '\n\n    ' + html.slice(end);
  out = out.replace('</head>', '<style>' + ROUTING_FIDELITY_CSS + '</style></head>');
  out = out.replace('</body>', '<script>' + ROUTING_FIDELITY_SCRIPT + '</script></body>');
  return out;
}
