export const SETTINGS_FIDELITY_CSS = String.raw`
/* Settings fidelity: index + security + session + data boundary + readiness, safe metadata only. */
#page-settings{padding:17px 24px 18px}
#page-settings .hero{height:83px}
.settings-blueprint{height:68px;margin-top:10px;border:1px solid #dfe9f4;border-radius:11px;background:radial-gradient(180px 70px at 83% 0,rgba(45,188,218,.08),transparent 70%),#fff;box-shadow:var(--shadow);display:grid;grid-template-columns:130px 1fr auto;align-items:center;gap:10px;padding:0 12px;overflow:hidden}
.settings-blueprint-title span{display:block;font-size:6.5px;letter-spacing:.09em;color:#8294b5;font-weight:800}.settings-blueprint-title b{display:block;margin-top:4px;font-size:9.5px;color:#1b4179}.settings-blueprint-title small{display:block;margin-top:2px;font-size:6.1px;color:#8a9ab7}
.settings-blueprint-flow{display:grid;grid-template-columns:1fr 18px 1fr 18px 1fr 18px 1fr;align-items:center}.settings-blueprint-node{text-align:center;min-width:0}.settings-blueprint-node i{width:24px;height:24px;margin:0 auto 4px;border-radius:8px;background:#eef6ff;color:#2679d9;display:grid;place-items:center}.settings-blueprint-node i svg{width:13px;height:13px}.settings-blueprint-node b{display:block;font-size:6.7px;color:#315382}.settings-blueprint-node span{display:block;margin-top:2px;font-size:5.7px;color:#8899b7;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.settings-blueprint-link{height:1px;background:linear-gradient(90deg,#cbd9e7,#65b9df,#62cbb3)}.settings-backend-badge{height:27px;padding:0 9px;border:1px solid #dce7f3;border-radius:14px;background:#f8fbff;display:flex;align-items:center;gap:6px;font-size:6.5px;color:#5c739c;white-space:nowrap}.settings-backend-badge i{width:6px;height:6px;border-radius:50%;background:#7998bc}
.settings-fidelity-workspace{height:calc(100% - 171px);margin-top:10px;display:grid;grid-template-columns:190px minmax(0,1fr) 245px;gap:10px}
.settings-index-fidelity,.settings-detail-fidelity,.settings-readiness-fidelity{height:100%;border:1px solid #dfe9f4;border-radius:12px;background:#fff;box-shadow:var(--shadow);overflow:hidden}
.settings-index-fidelity{padding:9px}.settings-index-head{padding:3px 6px 8px;border-bottom:1px solid #e8eef5}.settings-index-head span{display:block;font-size:6.3px;letter-spacing:.09em;color:#8697b6;font-weight:800}.settings-index-head b{display:block;margin-top:3px;font-size:9px;color:#244a80}.settings-index-items{display:grid;gap:4px;margin-top:8px}.settings-index-btn{height:36px;border:1px solid transparent;border-radius:8px;background:transparent;color:#55709d;display:grid;grid-template-columns:25px 1fr auto;align-items:center;gap:7px;padding:0 8px;text-align:left;font-size:7.3px}.settings-index-btn:hover{background:#f6faff}.settings-index-btn.active{background:linear-gradient(90deg,#edf6ff,#f8fbff);border-color:#d5e4f2;color:#1f5fa9}.settings-index-btn .ico{width:25px;height:25px;border-radius:7px;background:#f0f5fb;color:#4b70a6;display:grid;place-items:center}.settings-index-btn.active .ico{background:#e6f2ff;color:#2178d8}.settings-index-btn svg{width:13px;height:13px}.settings-index-btn small{font-size:5.6px;color:#92a0b9}.settings-index-note{margin-top:9px;border:1px solid #e1e9f2;border-radius:8px;background:#fbfdff;padding:8px;font-size:6.2px;line-height:1.42;color:#7489ad}.settings-index-note b{display:block;color:#315987;margin-bottom:3px}
.settings-detail-fidelity{display:flex;flex-direction:column}.settings-detail-head{height:48px;border-bottom:1px solid #e6edf5;padding:0 12px;display:flex;align-items:center}.settings-detail-head span{display:block;font-size:6.3px;letter-spacing:.08em;color:#8596b5;font-weight:800}.settings-detail-head b{display:block;margin-top:3px;font-size:10px;color:#173e77}.settings-detail-source{margin-left:auto;height:22px;padding:0 7px;border:1px solid #dce6f1;border-radius:11px;background:#f8fbff;display:flex;align-items:center;font-size:6px;color:#687fa7}.settings-detail-body{flex:1;min-height:0;overflow:auto;padding:10px}.settings-view{display:none}.settings-view.active{display:block}
.settings-view-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.settings-panel{min-height:91px;border:1px solid #e3ebf3;border-radius:9px;background:#fbfdff;padding:9px}.settings-panel-head{display:flex;align-items:center;gap:7px}.settings-panel-icon{width:27px;height:27px;border-radius:8px;background:#edf6ff;color:#2679d9;display:grid;place-items:center}.settings-panel-icon svg{width:14px;height:14px}.settings-panel-head b{font-size:7.8px;color:#244b82}.settings-panel-head span{display:block;margin-top:2px;font-size:5.9px;color:#8a9ab7}.settings-panel-copy{margin-top:8px;font-size:6.4px;line-height:1.48;color:#7186aa}.settings-panel-copy strong{color:#315785}.settings-authoritative-slot{margin-top:2px}.settings-authoritative-slot .setting-row{min-height:31px;border-bottom:1px solid #ebf0f5;display:flex;align-items:center;gap:8px;font-size:6.7px}.settings-authoritative-slot .setting-row:last-child{border-bottom:0}.settings-authoritative-slot .setting-row span{color:#7d90b2}.settings-authoritative-slot .setting-row b{margin-left:auto;color:#315582;text-align:right;max-width:60%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.security-architecture{display:grid;grid-template-columns:150px 1fr;gap:9px}.security-core{height:150px;border:1px solid #e2eaf3;border-radius:10px;background:radial-gradient(circle at center,rgba(38,176,206,.08),transparent 64%),#fbfdff;display:grid;place-items:center;position:relative}.security-core:before,.security-core:after{content:"";position:absolute;border:1px solid rgba(68,140,191,.17);border-radius:50%}.security-core:before{width:96px;height:96px}.security-core:after{width:132px;height:132px}.security-core-inner{width:66px;height:66px;border-radius:50%;background:#fff;box-shadow:0 8px 22px rgba(46,83,122,.08),inset 0 0 0 1px #dfe9f2;display:grid;place-items:center;text-align:center;z-index:2}.security-core-inner svg{width:18px;height:18px;color:#2378d8}.security-core-inner b{display:block;font-size:6.5px;color:#315581;margin-top:3px}.security-slot{border:1px solid #e2eaf3;border-radius:9px;background:#fbfdff;padding:9px}.security-slot .setting-row{min-height:31px;border-bottom:1px solid #ebf0f5;display:flex;align-items:center;font-size:6.6px}.security-slot .setting-row span{color:#7f91b1}.security-slot .setting-row b{margin-left:auto;color:#315581}.security-slot .setting-row:last-child{border-bottom:0}.secret-boundary{margin-top:7px;border:1px solid #cae8da;border-radius:8px;background:#f5fbf8;padding:8px;display:flex;gap:7px;color:#46765e;font-size:6.3px;line-height:1.45}.secret-boundary svg{width:14px;height:14px;color:#14a569;flex:none}
.session-card-large{border:1px solid #e2eaf3;border-radius:10px;background:#fbfdff;padding:10px}.session-chain{display:grid;grid-template-columns:1fr 15px 1fr 15px 1fr;align-items:center;margin-bottom:10px}.session-node{text-align:center;border:1px solid #e2eaf3;border-radius:8px;background:#fff;padding:8px}.session-node b{display:block;font-size:7px;color:#315381}.session-node span{display:block;margin-top:3px;font-size:5.8px;color:#8999b6}.session-link{height:1px;background:#bcd3e5}.session-facts{display:grid;grid-template-columns:repeat(2,1fr);gap:6px}.session-fact{min-height:42px;border:1px solid #e5ebf3;border-radius:8px;background:#fff;padding:7px}.session-fact small{display:block;font-size:5.9px;color:#8a99b6}.session-fact b{display:block;margin-top:3px;font-size:6.9px;color:#315484}.session-signout{margin-top:9px;border-top:1px solid #e8eef5;padding-top:8px;display:flex;align-items:center;gap:8px}.session-signout p{margin:0;flex:1;font-size:6.2px;color:#7489ac;line-height:1.4}
.boundary-map{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.boundary-column{border:1px solid #e1e9f2;border-radius:9px;background:#fbfdff;padding:9px}.boundary-column h3{margin:0;font-size:7.6px;color:#244c82}.boundary-column p{margin:5px 0 0;font-size:6.1px;line-height:1.5;color:#7689aa}.boundary-column .boundary-tag{display:inline-flex;margin-top:7px;height:18px;align-items:center;padding:0 6px;border-radius:9px;background:#edf6ff;color:#2869b5;font-size:5.8px;font-weight:800}.boundary-column.server .boundary-tag{background:#ecfaf4;color:#0b8a5d}.boundary-column.frontend .boundary-tag{background:#fff7e9;color:#9a6a18}
.settings-readiness-fidelity{display:flex;flex-direction:column}.readiness-head{height:48px;border-bottom:1px solid #e6edf5;padding:0 10px;display:flex;align-items:center}.readiness-head div span{display:block;font-size:6.2px;letter-spacing:.08em;color:#8697b5;font-weight:800}.readiness-head div b{display:block;margin-top:3px;font-size:9.5px;color:#173d77}.readiness-score{margin-left:auto;width:37px;height:37px;border-radius:50%;background:conic-gradient(#1dbb7b 0 var(--readiness,0%),#e7edf4 0);display:grid;place-items:center;position:relative}.readiness-score:after{content:"";position:absolute;inset:5px;border-radius:50%;background:#fff}.readiness-score b{position:relative;z-index:1;font-size:7px;color:#245180}.readiness-list{padding:8px;display:grid;gap:5px}.readiness-row{min-height:37px;border:1px solid #e3eaf2;border-radius:8px;background:#fbfdff;display:grid;grid-template-columns:8px 1fr auto;align-items:center;gap:6px;padding:0 8px}.readiness-row i{width:7px;height:7px;border-radius:50%;background:#9eacbd}.readiness-row.ready i{background:#12ad69}.readiness-row.missing i{background:#d39b2e}.readiness-row b{font-size:6.8px;color:#315382}.readiness-row span{font-size:5.8px;color:#8394b3}.readiness-row em{font-style:normal;font-size:5.8px;color:#7185a7}.readiness-footer{margin-top:auto;border-top:1px solid #e7edf4;padding:8px;font-size:6px;line-height:1.45;color:#7a8dab}
@media(max-width:1000px){.settings-fidelity-workspace{grid-template-columns:170px 1fr}.settings-readiness-fidelity{display:none}.settings-blueprint{grid-template-columns:120px 1fr}.settings-backend-badge{display:none}}
`;

export const SETTINGS_FIDELITY_SECTION = String.raw`
    <section id="page-settings" class="page settings-fidelity-page">
      <section class="hero"><div class="eyebrow">Settings</div><h1>Configuration & Security</h1><p>Safe runtime metadata, session posture and data boundaries. Raw secret values never cross into the frontend.</p><div class="hero-actions"><button class="btn" data-action="refresh-settings"><svg><use href="#i-refresh"/></svg>Refresh</button></div><svg class="hero-wave" viewBox="0 0 360 75" preserveAspectRatio="none"><path d="M0 53 C80 6 145 75 220 35S310 26 360 43" fill="none" stroke="#35aee3"/><path d="M0 66 C95 33 154 70 238 52S320 49 360 61" fill="none" stroke="#50cdb7"/></svg></section>
      <section class="settings-blueprint"><div class="settings-blueprint-title"><span>CONFIGURATION BLUEPRINT</span><b>Authority stays server-side</b><small>Frontend renders safe state only</small></div><div class="settings-blueprint-flow"><div class="settings-blueprint-node"><i><svg class="icon"><use href="#i-gear"/></svg></i><b>Runtime</b><span>Worker bindings</span></div><div class="settings-blueprint-link"></div><div class="settings-blueprint-node"><i><svg class="icon"><use href="#i-route"/></svg></i><b>Gateway</b><span>Safe identity</span></div><div class="settings-blueprint-link"></div><div class="settings-blueprint-node"><i><svg class="icon"><use href="#i-db"/></svg></i><b>D1</b><span>Authoritative state</span></div><div class="settings-blueprint-link"></div><div class="settings-blueprint-node"><i><svg class="icon"><use href="#i-shield"/></svg></i><b>Owner auth</b><span>Signed session</span></div></div><div class="settings-backend-badge"><i></i><span>/admin/api/settings</span></div></section>
      <section class="settings-fidelity-workspace">
        <aside class="settings-index-fidelity"><div class="settings-index-head"><span>SETTINGS INDEX</span><b>Configuration domains</b></div><div class="settings-index-items"><button class="settings-index-btn active" data-settings-view="environment"><span class="ico"><svg class="icon"><use href="#i-gear"/></svg></span><span>Environment</span><small>runtime</small></button><button class="settings-index-btn" data-settings-view="security"><span class="ico"><svg class="icon"><use href="#i-shield"/></svg></span><span>Security</span><small>bindings</small></button><button class="settings-index-btn" data-settings-view="session"><span class="ico"><svg class="icon"><use href="#i-lock"/></svg></span><span>Session</span><small>owner auth</small></button><button class="settings-index-btn" data-settings-view="boundary"><span class="ico"><svg class="icon"><use href="#i-db"/></svg></span><span>Data Boundary</span><small>authority</small></button></div><div class="settings-index-note"><b>No secret editor</b>This surface deliberately has no raw-token fields. Existing provider credential operations remain in Providers and submit directly to server-side endpoints.</div></aside>

        <article class="settings-detail-fidelity"><div class="settings-detail-head"><div><span id="settings-detail-kicker">ENVIRONMENT</span><b id="settings-detail-title">Runtime identity</b></div><span id="settings-detail-source" class="settings-detail-source">Safe backend metadata</span></div><div class="settings-detail-body">
          <section class="settings-view active" data-settings-panel="environment"><div class="settings-view-grid"><div class="settings-panel"><div class="settings-panel-head"><span class="settings-panel-icon"><svg class="icon"><use href="#i-route"/></svg></span><div><b>Runtime bindings</b><span>Authoritative safe metadata</span></div></div><div id="settings-runtime" class="settings-authoritative-slot"><div class="loading-box"><div class="skeleton" style="width:130px"></div></div></div></div><div class="settings-panel"><div class="settings-panel-head"><span class="settings-panel-icon"><svg class="icon"><use href="#i-info"/></svg></span><div><b>Interpretation</b><span>What this surface can safely say</span></div></div><div class="settings-panel-copy"><strong>Configured</strong> means a safe backend presence/identity signal exists. It does not expose the bound secret and does not itself prove upstream health.</div></div></div></section>

          <section class="settings-view" data-settings-panel="security"><div class="security-architecture"><div class="security-core"><div class="security-core-inner"><div><svg class="icon"><use href="#i-shield"/></svg><b>Secret boundary</b></div></div></div><div><div id="settings-security" class="security-slot"><div class="loading-box"><div class="skeleton" style="width:120px"></div></div></div><div class="secret-boundary"><svg class="icon"><use href="#i-shield"/></svg><span>Only configured/not-configured presence is rendered. Raw Cloudflare, Gateway and owner-auth secrets remain server-side.</span></div></div></div></section>

          <section class="settings-view" data-settings-panel="session"><div class="session-card-large"><div class="session-chain"><div class="session-node"><b>MCP_AUTH_TOKEN</b><span>owner trust root</span></div><div class="session-link"></div><div class="session-node"><b>HMAC session</b><span>browser-safe flow</span></div><div class="session-link"></div><div class="session-node"><b>/admin</b><span>authenticated shell</span></div></div><div class="session-facts"><div class="session-fact"><small>Session lifetime</small><b>12 hours</b></div><div class="session-fact"><small>Cookie protection</small><b>HttpOnly · Secure · SameSite=Strict</b></div><div class="session-fact"><small>Cookie path</small><b>/admin</b></div><div class="session-fact"><small>Owner secret in frontend</small><b>Never returned after login</b></div></div><div class="session-signout"><p>Sign out uses the existing server route and clears the signed Admin session cookie.</p><form method="POST" action="/admin/logout"><button class="btn danger" type="submit"><svg><use href="#i-lock"/></svg>Sign out</button></form></div></div></section>

          <section class="settings-view" data-settings-panel="boundary"><div class="boundary-map"><div class="boundary-column server"><h3>D1 / runtime state</h3><p>Provider/model policy, routing and persisted operational state remain authoritative outside the browser.</p><span class="boundary-tag">AUTHORITATIVE</span></div><div class="boundary-column server"><h3>Cloudflare secrets</h3><p>Secret values live in Worker bindings / server-side credential storage and are never rendered by Settings.</p><span class="boundary-tag">SERVER ONLY</span></div><div class="boundary-column frontend"><h3>Frontend</h3><p>The UI is presentation and control intent only. It cannot elevate missing, disabled or unknown backend state to healthy.</p><span class="boundary-tag">NON-AUTHORITY</span></div></div></section>
        </div></article>

        <aside class="settings-readiness-fidelity"><div class="readiness-head"><div><span>READINESS</span><b>Configuration posture</b></div><div id="settings-readiness-score" class="readiness-score"><b>0/5</b></div></div><div class="readiness-list"><div id="readiness-account" class="readiness-row"><i></i><div><b>Cloudflare account</b><span>safe identity</span></div><em>Waiting</em></div><div id="readiness-d1" class="readiness-row"><i></i><div><b>D1 binding</b><span>control state</span></div><em>Waiting</em></div><div id="readiness-cf" class="readiness-row"><i></i><div><b>CF token</b><span>presence only</span></div><em>Waiting</em></div><div id="readiness-gateway" class="readiness-row"><i></i><div><b>Gateway auth</b><span>presence only</span></div><em>Waiting</em></div><div id="readiness-owner" class="readiness-row"><i></i><div><b>Owner auth</b><span>presence only</span></div><em>Waiting</em></div></div><div class="readiness-footer">This score is configuration readiness only. It is not provider health, callability, or end-to-end verification.</div></aside>
      </section>
    </section>
`;

export const SETTINGS_FIDELITY_SCRIPT = String.raw`(function(){
'use strict';
var scheduled=false;
function text(el){return el?el.textContent.trim():'';}
function rows(root){return Array.prototype.slice.call(root.querySelectorAll('.setting-row')).map(function(r){return{label:text(r.querySelector('span')).toLowerCase(),value:text(r.querySelector('b')).toLowerCase()};});}
function findValue(list,needle){var r=list.find(function(x){return x.label.indexOf(needle)>=0;});return r?r.value:'';}
function ready(id,value){var el=document.getElementById(id);if(!el)return;var ok=!!value&&value!=='—'&&value.indexOf('not configured')<0&&value.indexOf('unavailable')<0&&value.indexOf('missing')<0;el.className='readiness-row '+(ok?'ready':'missing');el.querySelector('em').textContent=ok?'Ready':'Missing';return ok;}
function refresh(){scheduled=false;var runtime=document.getElementById('settings-runtime'),security=document.getElementById('settings-security');if(!runtime||!security)return;var rr=rows(runtime),sr=rows(security);var account=findValue(rr,'cloudflare account'),d1=findValue(rr,'d1 binding'),cf=findValue(sr,'cloudflare api token'),gateway=findValue(sr,'gateway auth'),owner=findValue(sr,'owner / mcp auth');var states=[ready('readiness-account',account),ready('readiness-d1',d1),ready('readiness-cf',cf),ready('readiness-gateway',gateway),ready('readiness-owner',owner)];var count=states.filter(Boolean).length,score=document.getElementById('settings-readiness-score');score.style.setProperty('--readiness',(count/5*100)+'%');score.querySelector('b').textContent=count+'/5';}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(refresh);}
['settings-runtime','settings-security'].forEach(function(id){var el=document.getElementById(id);if(el)new MutationObserver(schedule).observe(el,{childList:true,subtree:true,characterData:true});});
var meta={environment:['ENVIRONMENT','Runtime identity','Safe backend metadata'],security:['SECURITY','Security bindings','Presence only'],session:['SESSION','Owner session','Auth source contract'],boundary:['DATA BOUNDARY','Authority map','No secret exposure']};document.querySelectorAll('[data-settings-view]').forEach(function(btn){btn.addEventListener('click',function(){var v=btn.dataset.settingsView;document.querySelectorAll('[data-settings-view]').forEach(function(x){x.classList.toggle('active',x===btn);});document.querySelectorAll('[data-settings-panel]').forEach(function(p){p.classList.toggle('active',p.dataset.settingsPanel===v);});var m=meta[v];document.getElementById('settings-detail-kicker').textContent=m[0];document.getElementById('settings-detail-title').textContent=m[1];document.getElementById('settings-detail-source').textContent=m[2];});});schedule();
})();`;

export function applySettingsFidelity(html: string): string {
  const start = html.indexOf('<section id="page-settings"');
  const end = start >= 0 ? html.indexOf('</main>', start) : -1;
  if (start < 0 || end < 0) return html;
  let out = html.slice(0, start) + SETTINGS_FIDELITY_SECTION + '\n  ' + html.slice(end);
  out = out.replace('</head>', '<style>' + SETTINGS_FIDELITY_CSS + '</style></head>');
  out = out.replace('</body>', '<script>' + SETTINGS_FIDELITY_SCRIPT + '</script></body>');
  return out;
}
