export const TOOLS_FIDELITY_CSS = String.raw`
/* MCP Tools fidelity: runtime-backed workbench, capability scope rail, persistent detail. */
#page-mcp-tools{padding:17px 24px 18px}
#page-mcp-tools .hero{height:83px}
.tools-protocol-fidelity{height:62px;margin-top:10px;border:1px solid #dfe9f4;border-radius:11px;background:#fff;box-shadow:var(--shadow);display:grid;grid-template-columns:120px 1fr;align-items:center;padding:0 11px;gap:10px}.tools-protocol-title span{display:block;font-size:6.3px;letter-spacing:.09em;color:#8496b7;font-weight:800}.tools-protocol-title b{display:block;margin-top:3px;font-size:9px;color:#173d76}.tools-protocol-flow{display:grid;grid-template-columns:1fr 14px 1fr 14px 1fr 14px 1fr 14px 1fr;align-items:center}.tools-protocol-stage{text-align:center;min-width:0}.tools-protocol-stage i{width:21px;height:21px;border-radius:7px;background:#eef6ff;color:#2979d8;display:grid;place-items:center;margin:0 auto 3px}.tools-protocol-stage i svg{width:11px;height:11px}.tools-protocol-stage b{display:block;font-size:6.1px;color:#315382;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.tools-protocol-stage span{display:block;margin-top:1px;font-size:5.3px;color:#8999b6;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.tools-protocol-stage.disabled i{background:#f3f5f8;color:#8b9ab1}.tools-protocol-stage.disabled b{color:#7689a8}.tools-protocol-link{height:1px;background:linear-gradient(90deg,#cbd8e6,#68b8df,#62ccb5)}.tools-protocol-link.disabled{background:#dfe6ed}
.tools-fidelity-workbench{height:calc(100% - 165px);margin-top:10px;display:grid;grid-template-columns:150px minmax(0,1fr) 300px;gap:10px}
.tools-scope-fidelity,.tools-catalog-fidelity,.tools-inspector-fidelity{height:100%;border:1px solid #dfe9f4;border-radius:12px;background:#fff;box-shadow:var(--shadow);overflow:hidden}
.tools-scope-head{height:43px;border-bottom:1px solid #e6edf5;padding:0 10px;display:flex;align-items:center}.tools-scope-head div span{display:block;font-size:6.2px;letter-spacing:.08em;color:#8496b6;font-weight:800}.tools-scope-head div b{display:block;margin-top:2px;font-size:8.7px;color:#173d76}.tools-scope-list{padding:7px;display:grid;gap:4px}.tools-scope-btn{height:34px;border:1px solid transparent;border-radius:8px;background:transparent;color:#5f769d;display:grid;grid-template-columns:24px 1fr auto;align-items:center;gap:6px;padding:0 7px;text-align:left}.tools-scope-btn:hover{background:#f6faff}.tools-scope-btn.active{background:linear-gradient(90deg,#edf6ff,#f8fbff);border-color:#d3e3f2;color:#1f5fa8}.tools-scope-btn .ico{width:24px;height:24px;border-radius:7px;background:#f0f5fb;color:#5274a7;display:grid;place-items:center}.tools-scope-btn.active .ico{background:#e5f2ff;color:#2178d8}.tools-scope-btn svg{width:12px;height:12px}.tools-scope-btn b{font-size:6.5px}.tools-scope-btn small{font-size:5.5px;color:#8d9cb8}.tools-scope-foot{margin:7px;border:1px solid #e3eaf2;border-radius:8px;background:#fbfdff;padding:8px;font-size:5.8px;line-height:1.4;color:#788cac}.tools-scope-foot b{display:block;margin-bottom:3px;color:#315685}
.tools-catalog-fidelity{display:flex;flex-direction:column}.tools-catalog-head{height:43px;border-bottom:1px solid #e6edf5;padding:0 9px;display:flex;align-items:center;gap:7px}.tools-catalog-head .searchbox{height:29px;min-width:190px;flex:1}.tools-catalog-head #tools-summary{font-size:6.1px;color:#7d90b4;white-space:nowrap}.tools-annotation-strip{height:35px;border-bottom:1px solid #e9eff5;background:#fbfdff;display:flex;align-items:center;gap:5px;padding:0 8px}.tools-annotation-strip>span{font-size:5.8px;color:#8999b6;margin-right:2px}.tools-annotation-strip .protocol-pill{height:23px;padding:0 7px;border:1px solid #dfe7f0;border-radius:12px;background:#fff;color:#667da5;font-size:5.7px}.tools-annotation-strip .protocol-pill.active{background:#edf6ff;border-color:#cfe0ef;color:#226ab9}.tools-list-fidelity{flex:1;min-height:0;overflow:auto;padding:6px}.tools-list-fidelity .tool-row{min-height:43px!important;border:1px solid #e4ebf3!important;border-radius:8px!important;background:#fbfdff!important;margin-bottom:5px!important;padding:7px 8px!important;grid-template-columns:minmax(0,1fr) auto 14px!important;gap:7px!important}.tools-list-fidelity .tool-row:hover{background:#fff!important;border-color:#cbddeb!important}.tools-list-fidelity .tool-row.selected{background:linear-gradient(90deg,#eef6ff,#fbfdff)!important;box-shadow:inset 3px 0 0 #277fe4!important}.tools-list-fidelity .tool-row b{font-size:6.7px!important;color:#244d83!important}.tools-list-fidelity .tool-row p{font-size:5.7px!important;line-height:1.35!important;color:#8596b5!important;margin:2px 0 0!important;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.tools-list-fidelity .annotation-list{display:flex;gap:3px;flex-wrap:wrap;justify-content:flex-end}.tools-list-fidelity .ann{height:17px!important;padding:0 5px!important;font-size:5.3px!important}
.tools-inspector-fidelity{display:flex;flex-direction:column}.tools-inspector-head{height:43px;border-bottom:1px solid #e6edf5;padding:0 10px;display:flex;align-items:center}.tools-inspector-head div span{display:block;font-size:6.2px;letter-spacing:.08em;color:#8596b5;font-weight:800}.tools-inspector-head div b{display:block;margin-top:2px;font-size:8.7px;color:#173d76}.tools-inspector-head em{margin-left:auto;font-style:normal;font-size:5.8px;color:#7187ad}.tools-inspector-fidelity #tool-detail{flex:1;min-height:0;overflow:auto;padding:10px!important;border:0!important}.tools-inspector-fidelity #tool-detail h2{font-size:9px!important;color:#1c477f!important;margin:0 0 7px!important;word-break:break-word}.tools-inspector-fidelity #tool-detail .desc{font-size:6.3px!important;line-height:1.5!important;color:#7288ad!important;margin-bottom:8px!important}.tools-inspector-fidelity #tool-detail .schema{max-height:170px!important;overflow:auto!important;border:1px solid #e1e9f2!important;border-radius:8px!important;background:#f7faff!important;padding:8px!important;font-size:5.8px!important;line-height:1.4!important;color:#3e608c!important}.tools-inspector-fidelity #tool-detail .detail-actions{margin-top:8px!important;display:flex!important;gap:6px!important}.tools-inspector-fidelity #tool-detail .detail-actions .btn{height:27px!important}.tools-inspector-fidelity #tool-detail .annotation-list{display:flex;gap:4px;flex-wrap:wrap}.tools-inspector-boundary{height:44px;border-top:1px solid #e6edf5;background:#f8fbff;padding:7px 9px;display:flex;gap:7px;align-items:center;color:#7489aa;font-size:5.8px;line-height:1.35}.tools-inspector-boundary svg{width:14px;height:14px;color:#2679d8;flex:none}.tools-hidden-by-scope{display:none!important}
@media(max-width:1000px){.tools-fidelity-workbench{grid-template-columns:135px 1fr}.tools-inspector-fidelity{display:none}}
`;

export const TOOLS_FIDELITY_SECTION = String.raw`
    <section id="page-mcp-tools" class="page tools-fidelity-page">
      <section class="hero"><div class="eyebrow">MCP Tools</div><h1>Tool Catalog & Execution Surface</h1><p>Runtime-backed tools/list metadata, safety annotations and schemas in a dedicated MCP workbench.</p><div class="hero-actions"><button class="btn" data-action="refresh-tools"><svg><use href="#i-refresh"/></svg>Reload catalog</button></div><svg class="hero-wave" viewBox="0 0 360 75" preserveAspectRatio="none"><path d="M0 53 C80 6 145 75 220 35S310 26 360 43" fill="none" stroke="#35aee3"/><path d="M0 66 C95 33 154 70 238 52S320 49 360 61" fill="none" stroke="#50cdb7"/></svg></section>
      <section class="tools-protocol-fidelity"><div class="tools-protocol-title"><span>MCP PROTOCOL SURFACE</span><b>Catalog to evidence</b></div><div class="tools-protocol-flow"><div class="tools-protocol-stage"><i><svg class="icon"><use href="#i-shield"/></svg></i><b>Admin session</b><span>authenticated</span></div><div class="tools-protocol-link"></div><div class="tools-protocol-stage"><i><svg class="icon"><use href="#i-nodes"/></svg></i><b>tools/list mirror</b><span id="tools-protocol-count">runtime catalog</span></div><div class="tools-protocol-link"></div><div class="tools-protocol-stage"><i><svg class="icon"><use href="#i-doc"/></svg></i><b>Metadata</b><span>schema + description</span></div><div class="tools-protocol-link"></div><div class="tools-protocol-stage"><i><svg class="icon"><use href="#i-shield"/></svg></i><b>Guard hints</b><span>annotations</span></div><div class="tools-protocol-link disabled"></div><div class="tools-protocol-stage disabled"><i><svg class="icon"><use href="#i-bolt"/></svg></i><b>Invocation</b><span>not exposed in Admin</span></div></div></section>
      <section class="tools-fidelity-workbench">
        <aside class="tools-scope-fidelity"><div class="tools-scope-head"><div><span>CAPABILITY MAP</span><b>Tool families</b></div></div><div class="tools-scope-list"><button class="tools-scope-btn active" data-tool-scope="all"><span class="ico"><svg class="icon"><use href="#i-nodes"/></svg></span><b>All tools</b><small id="scope-count-all">—</small></button><button class="tools-scope-btn" data-tool-scope="cloudflare"><span class="ico"><svg class="icon"><use href="#i-db"/></svg></span><b>Cloudflare</b><small id="scope-count-cloudflare">—</small></button><button class="tools-scope-btn" data-tool-scope="internet"><span class="ico"><svg class="icon"><use href="#i-search"/></svg></span><b>Internet</b><small id="scope-count-internet">—</small></button><button class="tools-scope-btn" data-tool-scope="huggingface"><span class="ico"><svg class="icon"><use href="#i-cube"/></svg></span><b>Hugging Face</b><small id="scope-count-huggingface">—</small></button><button class="tools-scope-btn" data-tool-scope="execution"><span class="ico"><svg class="icon"><use href="#i-terminal"/></svg></span><b>Execution</b><small id="scope-count-execution">—</small></button><button class="tools-scope-btn" data-tool-scope="proxyharvest"><span class="ico"><svg class="icon"><use href="#i-heart"/></svg></span><b>ProxyHarvest</b><small id="scope-count-proxyharvest">—</small></button></div><div class="tools-scope-foot"><b>Runtime-backed only</b>Family grouping is derived from names returned by the live Admin catalog; the tool list itself is never hardcoded here.</div></aside>
        <article class="tools-catalog-fidelity"><div class="tools-catalog-head"><div class="searchbox"><svg><use href="#i-search"/></svg><input id="tools-search" placeholder="Search tool name or capability"></div><span id="tools-summary">Loading…</span></div><div id="tool-annotation-rail" class="tools-annotation-strip"><span>Annotations</span><button class="protocol-pill active" data-tool-filter="all"><b>All</b><span id="tool-count-all">Runtime catalog</span></button><button class="protocol-pill" data-tool-filter="readonly"><b>Read only</b><span id="tool-count-readonly">—</span></button><button class="protocol-pill" data-tool-filter="destructive"><b>Destructive</b><span id="tool-count-destructive">—</span></button><button class="protocol-pill" data-tool-filter="openworld"><b>Open world</b><span id="tool-count-openworld">—</span></button></div><div id="tools-body" class="tools-list-fidelity"><div class="loading-box"><div class="skeleton" style="width:220px"></div></div></div></article>
        <aside class="tools-inspector-fidelity"><div class="tools-inspector-head"><div><span>SELECTED TOOL INSPECTOR</span><b>Protocol metadata</b></div><em>read-only Admin surface</em></div><div id="tool-detail"><div class="empty"><b>Select a tool</b><span>Schema and annotations will appear here.</span></div></div><div class="tools-inspector-boundary"><svg class="icon"><use href="#i-shield"/></svg><span>The Admin API exposes catalog metadata, not tool invocation. Disabled Invoke stays intentionally non-operational.</span></div></aside>
      </section>
    </section>
`;

export const TOOLS_FIDELITY_SCRIPT = String.raw`(function(){
'use strict';
var scope='all',scheduled=false;
function text(el){return el?el.textContent.trim():'';}
function rows(){return Array.prototype.slice.call(document.querySelectorAll('#tools-body [data-tool-select]'));}
function name(row){return row.dataset.toolSelect||text(row.querySelector('b'));}
function family(n){n=String(n||'');if(n.indexOf('cf_')===0)return'cloudflare';if(n.indexOf('web_')===0)return'internet';if(n.indexOf('hf_')===0)return'huggingface';if(n==='run_code'||n==='list_code_runtimes'||n.indexOf('gh_')===0)return'execution';if(n.indexOf('proxyharvest_')===0)return'proxyharvest';return'other';}
function refresh(){scheduled=false;var list=rows(),counts={all:list.length,cloudflare:0,internet:0,huggingface:0,execution:0,proxyharvest:0};list.forEach(function(r){var f=family(name(r));if(counts[f]!=null)counts[f]++;r.classList.toggle('tools-hidden-by-scope',scope!=='all'&&f!==scope);});Object.keys(counts).forEach(function(k){var el=document.getElementById('scope-count-'+k);if(el)el.textContent=counts[k];});var proto=document.getElementById('tools-protocol-count');if(proto)proto.textContent=list.length+' loaded tools';}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(refresh);}
var body=document.getElementById('tools-body');if(body)new MutationObserver(schedule).observe(body,{childList:true,subtree:true,characterData:true});document.querySelectorAll('[data-tool-scope]').forEach(function(btn){btn.addEventListener('click',function(){scope=btn.dataset.toolScope||'all';document.querySelectorAll('[data-tool-scope]').forEach(function(x){x.classList.toggle('active',x===btn);});refresh();});});document.querySelectorAll('[data-tool-filter]').forEach(function(btn){btn.addEventListener('click',function(){setTimeout(schedule,0);});});var search=document.getElementById('tools-search');if(search)search.addEventListener('input',function(){setTimeout(schedule,0);});schedule();
})();`;

export function applyToolsFidelity(html: string): string {
  const start = html.indexOf('<section id="page-mcp-tools"');
  const end = start >= 0 ? html.indexOf('<section id="page-routing"', start) : -1;
  if (start < 0 || end < 0) return html;
  let out = html.slice(0, start) + TOOLS_FIDELITY_SECTION + '\n\n    ' + html.slice(end);
  out = out.replace('</head>', '<style>' + TOOLS_FIDELITY_CSS + '</style></head>');
  out = out.replace('</body>', '<script>' + TOOLS_FIDELITY_SCRIPT + '</script></body>');
  return out;
}
