export const USAGE_FIDELITY_CSS = String.raw`
/* Usage fidelity: honest observability surface; no fabricated request/token/cost telemetry. */
#page-usage{padding:17px 24px 18px}
#page-usage .hero{height:83px}
.usage-lineage{height:62px;margin-top:10px;border:1px solid #dfe9f4;border-radius:11px;background:#fff;box-shadow:var(--shadow);display:grid;grid-template-columns:145px 1fr auto;align-items:center;gap:10px;padding:0 12px;overflow:hidden}.usage-lineage-title span{display:block;font-size:6.4px;letter-spacing:.09em;color:#8295b7;font-weight:800}.usage-lineage-title b{display:block;margin-top:3px;font-size:9.3px;color:#173e77}.usage-lineage-flow{display:grid;grid-template-columns:1fr 16px 1fr 16px 1fr 16px 1fr;align-items:center}.usage-lineage-node{text-align:center}.usage-lineage-node i{width:23px;height:23px;border-radius:7px;background:#eef6ff;color:#287adb;display:grid;place-items:center;margin:0 auto 3px}.usage-lineage-node i svg{width:12px;height:12px}.usage-lineage-node b{display:block;font-size:6.4px;color:#315382}.usage-lineage-node span{display:block;margin-top:1px;font-size:5.5px;color:#8999b7}.usage-lineage-link{height:1px;background:linear-gradient(90deg,#cad8e6,#66b8df,#60ccb4)}.usage-contract-badge{height:26px;padding:0 9px;border:1px solid #dce7f3;border-radius:13px;background:#f8fbff;display:flex;align-items:center;gap:6px;font-size:6.3px;color:#5d739c;white-space:nowrap}.usage-contract-badge i{width:6px;height:6px;border-radius:50%;background:#2a83df}
.usage-fidelity-overview{height:168px;margin-top:10px;display:grid;grid-template-columns:1.1fr 1.25fr 1.05fr;gap:10px}.usage-fidelity-card{border:1px solid #dfe9f4;border-radius:12px;background:#fff;box-shadow:var(--shadow);overflow:hidden}.usage-card-head-fidelity{height:40px;border-bottom:1px solid #e6edf5;padding:0 11px;display:flex;align-items:center}.usage-card-head-fidelity div span{display:block;font-size:6.2px;letter-spacing:.08em;color:#8596b6;font-weight:800}.usage-card-head-fidelity div b{display:block;margin-top:2px;font-size:9px;color:#173e77}.usage-card-head-fidelity>span{margin-left:auto;font-size:6.2px;color:#7990b4}
.usage-audit-posture{padding:9px 11px;height:128px;display:grid;grid-template-columns:104px 1fr;gap:10px}.usage-audit-number{display:grid;place-items:center;border-right:1px solid #e7edf4;text-align:center}.usage-audit-number strong{display:block;font-size:25px;color:#123d76;line-height:1}.usage-audit-number span{display:block;margin-top:4px;font-size:6.4px;color:#8595b5}.usage-activity-ribbon{position:relative;height:54px;margin-top:5px}.usage-ribbon-line{position:absolute;left:4px;right:4px;top:28px;height:1px;background:#dce6ef}.usage-ribbon-points{position:absolute;left:4px;right:4px;top:22px;height:14px;display:flex;align-items:center;gap:5px;overflow:hidden}.usage-ribbon-point{width:7px;height:7px;border-radius:50%;background:#2f82dc;box-shadow:0 0 0 3px rgba(47,130,220,.08);flex:none}.usage-ribbon-empty{height:54px;display:grid;place-items:center;color:#8a9ab6;font-size:6.2px}.usage-audit-foot{margin-top:4px;font-size:6.2px;color:#7288ad;line-height:1.42}
.coverage-matrix{height:128px;padding:8px 10px;display:grid;grid-template-columns:1fr 1fr;gap:5px}.coverage-row{border:1px solid #e3ebf3;border-radius:8px;background:#fbfdff;display:grid;grid-template-columns:8px 1fr auto;align-items:center;gap:6px;padding:0 7px;min-height:31px}.coverage-row i{width:7px;height:7px;border-radius:50%;background:#a4b1c1}.coverage-row.available i{background:#12ad69}.coverage-row.unavailable i{background:#d39b2e}.coverage-row b{font-size:6.6px;color:#315382}.coverage-row span{font-size:5.7px;color:#8999b7}.coverage-row em{font-style:normal;font-size:5.6px;color:#6e84aa}.coverage-row.unavailable em{color:#9b6c18}
.usage-footprint{height:128px;padding:9px 10px;display:grid;grid-template-columns:92px 1fr;align-items:center;gap:8px}.usage-footprint-ring{width:82px;height:82px;border-radius:50%;background:conic-gradient(#3783db 0 25%,#2ab68b 25% 50%,#8b72d7 50% 75%,#9daabd 75% 100%);position:relative;display:grid;place-items:center}.usage-footprint-ring:after{content:"";position:absolute;inset:10px;border-radius:50%;background:#fff}.usage-footprint-ring div{position:relative;z-index:1;text-align:center}.usage-footprint-ring b{display:block;font-size:11px;color:#244e84}.usage-footprint-ring span{display:block;margin-top:2px;font-size:5.6px;color:#8798b5}.usage-footprint-list{display:grid;gap:5px}.usage-footprint-row{display:grid;grid-template-columns:7px 1fr auto;gap:5px;align-items:center}.usage-footprint-row i{width:6px;height:6px;border-radius:50%;background:#3783db}.usage-footprint-row:nth-child(2) i{background:#2ab68b}.usage-footprint-row:nth-child(3) i{background:#8b72d7}.usage-footprint-row:nth-child(4) i{background:#9daabd}.usage-footprint-row span{font-size:6.2px;color:#7288ad}.usage-footprint-row b{font-size:6.7px;color:#315483}
.usage-fidelity-detail{height:calc(100% - 345px);margin-top:10px;display:grid;grid-template-columns:1.2fr 1fr .82fr;gap:10px}.usage-detail-card{height:100%;border:1px solid #dfe9f4;border-radius:12px;background:#fff;box-shadow:var(--shadow);overflow:hidden}.usage-detail-head-fidelity{height:39px;border-bottom:1px solid #e6edf5;padding:0 10px;display:flex;align-items:center}.usage-detail-head-fidelity h2{margin:0;font-size:9px;color:#173d76}.usage-detail-head-fidelity span{margin-left:auto;font-size:6px;color:#8194b6}.usage-actions-fidelity{height:calc(100% - 39px);overflow:auto;padding:6px 8px}.usage-actions-fidelity .recent-action{min-height:35px;border:1px solid #e6edf4;border-radius:8px;background:#fbfdff;padding:7px 8px;margin-bottom:5px;display:flex;align-items:center}.usage-actions-fidelity .recent-action b{font-size:6.8px;color:#315383}.usage-actions-fidelity .recent-action time{margin-left:auto;font-size:5.8px;color:#8b9ab6}.usage-health-evidence{height:calc(100% - 39px);overflow:auto;padding:7px 8px}.usage-health-sample{min-height:35px;border:1px solid #e5ecf4;border-radius:8px;background:#fbfdff;padding:7px 8px;margin-bottom:5px;display:grid;grid-template-columns:8px 1fr auto;gap:6px;align-items:center}.usage-health-sample i{width:7px;height:7px;border-radius:50%;background:#9aaabd}.usage-health-sample.HEALTHY i{background:#12ad69}.usage-health-sample.RATE_LIMITED i{background:#d39b2e}.usage-health-sample.AUTH_ERROR i,.usage-health-sample.UPSTREAM_ERROR i{background:#d45f6b}.usage-health-sample b{display:block;font-size:6.7px;color:#315382}.usage-health-sample span{display:block;margin-top:2px;font-size:5.7px;color:#8798b6}.usage-health-sample em{font-style:normal;font-size:6.1px;color:#6078a0}.telemetry-gap{height:calc(100% - 39px);padding:9px}.telemetry-gap-callout{height:100%;border:1px solid #eadcb9;border-radius:9px;background:linear-gradient(180deg,#fffaf0,#fffdf8);padding:10px;display:flex;flex-direction:column}.telemetry-gap-callout .gap-icon{width:29px;height:29px;border-radius:8px;background:#fff3d8;color:#a87316;display:grid;place-items:center}.telemetry-gap-callout .gap-icon svg{width:15px;height:15px}.telemetry-gap-callout b{display:block;margin-top:8px;font-size:7.8px;color:#805d1c}.telemetry-gap-callout p{margin:5px 0 0;font-size:6.2px;line-height:1.5;color:#816f4b}.telemetry-gap-list{margin-top:8px;display:grid;gap:4px}.telemetry-gap-list span{font-size:5.9px;color:#8a774f}.telemetry-gap-footer{margin-top:auto;border-top:1px solid #eddfbd;padding-top:7px;font-size:5.8px;color:#8a774f;line-height:1.4}
@media(max-width:1000px){.usage-fidelity-overview{grid-template-columns:1fr 1fr}.usage-fidelity-overview .usage-fidelity-card:last-child{display:none}.usage-fidelity-detail{grid-template-columns:1fr 1fr}.usage-fidelity-detail .usage-detail-card:last-child{display:none}}
`;

export const USAGE_FIDELITY_SECTION = String.raw`
    <section id="page-usage" class="page usage-fidelity-page">
      <section class="hero"><div class="eyebrow">Usage</div><h1>Usage & Observability</h1><p>Operational evidence from the data the backend actually exposes — unavailable telemetry stays explicitly unavailable.</p><div class="hero-actions"><button class="btn" data-action="refresh-usage"><svg><use href="#i-refresh"/></svg>Refresh</button></div><svg class="hero-wave" viewBox="0 0 360 75" preserveAspectRatio="none"><path d="M0 53 C80 6 145 75 220 35S310 26 360 43" fill="none" stroke="#35aee3"/><path d="M0 66 C95 33 154 70 238 52S320 49 360 61" fill="none" stroke="#50cdb7"/></svg></section>
      <section class="usage-lineage"><div class="usage-lineage-title"><span>OBSERVABILITY LINEAGE</span><b>Evidence before analytics</b></div><div class="usage-lineage-flow"><div class="usage-lineage-node"><i><svg class="icon"><use href="#i-doc"/></svg></i><b>Audit</b><span>activity events</span></div><div class="usage-lineage-link"></div><div class="usage-lineage-node"><i><svg class="icon"><use href="#i-heart"/></svg></i><b>Health</b><span>persisted checks</span></div><div class="usage-lineage-link"></div><div class="usage-lineage-node"><i><svg class="icon"><use href="#i-nodes"/></svg></i><b>Runtime</b><span>registry posture</span></div><div class="usage-lineage-link"></div><div class="usage-lineage-node"><i><svg class="icon"><use href="#i-bars"/></svg></i><b>Usage UI</b><span>honest coverage</span></div></div><div class="usage-contract-badge"><i></i><span>/admin/api/usage</span></div></section>
      <section class="usage-fidelity-overview">
        <article class="usage-fidelity-card"><div class="usage-card-head-fidelity"><div><span>AUDIT FOOTPRINT</span><b>Activity available now</b></div><span id="usage-recent-caption">recent window</span></div><div class="usage-audit-posture"><div class="usage-audit-number"><div><strong id="usage-total">—</strong><span>audit events</span></div></div><div><div id="usage-activity-ribbon" class="usage-activity-ribbon"><div class="usage-ribbon-line"></div><div id="usage-ribbon-points" class="usage-ribbon-points"></div></div><div class="usage-audit-foot"><b id="usage-recent">—</b> recent actions returned by the current usage contract. The ribbon represents loaded events only, not request volume.</div></div></div></article>
        <article class="usage-fidelity-card"><div class="usage-card-head-fidelity"><div><span>INSTRUMENTATION MATRIX</span><b>What the Admin backend can support</b></div><span>contract truth</span></div><div class="coverage-matrix"><div class="coverage-row available"><i></i><div><b>Audit activity</b><span>current usage endpoint</span></div><em>available</em></div><div class="coverage-row available"><i></i><div><b>Provider health</b><span>health evidence</span></div><em>available</em></div><div class="coverage-row available"><i></i><div><b>Runtime posture</b><span>overview registry</span></div><em>available</em></div><div class="coverage-row unavailable"><i></i><div><b>Request / token volume</b><span>no Admin contract</span></div><em>unavailable</em></div><div class="coverage-row unavailable"><i></i><div><b>Spend / cost</b><span>no Admin contract</span></div><em>unavailable</em></div><div class="coverage-row unavailable"><i></i><div><b>Latency percentiles</b><span>not aggregated</span></div><em>unavailable</em></div></div></article>
        <article class="usage-fidelity-card"><div class="usage-card-head-fidelity"><div><span>CONTROL-PLANE POSTURE</span><b>Runtime footprint</b></div><span>cross-page state</span></div><div class="usage-footprint"><div class="usage-footprint-ring"><div><b id="usage-footprint-primary">—</b><span>active routes</span></div></div><div class="usage-footprint-list"><div class="usage-footprint-row"><i></i><span>Providers</span><b id="usage-fp-providers">—</b></div><div class="usage-footprint-row"><i></i><span>Callable models</span><b id="usage-fp-models">—</b></div><div class="usage-footprint-row"><i></i><span>MCP tools</span><b id="usage-fp-tools">—</b></div><div class="usage-footprint-row"><i></i><span>Unavailable aliases</span><b id="usage-fp-unavailable">—</b></div></div></div></article>
      </section>
      <section class="usage-fidelity-detail"><article class="usage-detail-card"><div class="usage-detail-head-fidelity"><h2>Audit event lens</h2><span>real recent actions</span></div><div id="usage-actions" class="usage-actions-fidelity"></div></article><article class="usage-detail-card"><div class="usage-detail-head-fidelity"><h2>Diagnostic samples</h2><span id="usage-health-count">health history</span></div><div id="usage-health-evidence" class="usage-health-evidence"><div class="empty"><b>Waiting for health evidence</b><span>No synthetic chart will be drawn.</span></div></div></article><aside class="usage-detail-card"><div class="usage-detail-head-fidelity"><h2>Instrumentation gap</h2><span>explicitly unavailable</span></div><div class="telemetry-gap"><div class="telemetry-gap-callout"><div class="gap-icon"><svg class="icon"><use href="#i-info"/></svg></div><b>No request/token accounting contract</b><p>This Admin backend currently does not expose request counts, token consumption, spend, or percentile telemetry. The UI will not derive or fabricate those analytics.</p><div class="telemetry-gap-list"><span>• no synthetic request graph</span><span>• no inferred cost</span><span>• no invented token counts</span></div><div class="telemetry-gap-footer">Add these surfaces only when a real authoritative telemetry contract exists.</div></div></div></aside></section>
    </section>
`;

export const USAGE_FIDELITY_SCRIPT = String.raw`(function(){
'use strict';
var scheduled=false;
function text(el){return el?el.textContent.trim():'';}
function stateText(cell){var s=cell&&cell.querySelector('.state');return text(s)||'UNKNOWN';}
function drawActivity(){var host=document.getElementById('usage-ribbon-points'),actions=Array.prototype.slice.call(document.querySelectorAll('#usage-actions .recent-action'));host.innerHTML='';if(!actions.length){host.innerHTML='<span class="usage-ribbon-empty">No recent actions returned</span>';document.getElementById('usage-recent-caption').textContent='empty window';return;}actions.slice(0,18).forEach(function(a){var d=document.createElement('span');d.className='usage-ribbon-point';d.title=text(a);host.appendChild(d);});document.getElementById('usage-recent-caption').textContent=actions.length+' loaded actions';}
function drawFootprint(){document.getElementById('usage-footprint-primary').textContent=text(document.getElementById('ov-routes'))||'—';document.getElementById('usage-fp-providers').textContent=text(document.getElementById('ov-providers'))||'—';document.getElementById('usage-fp-models').textContent=text(document.getElementById('ov-models'))||'—';document.getElementById('usage-fp-tools').textContent=text(document.getElementById('ov-tools'))||'—';var sub=text(document.getElementById('ov-routes-sub')),m=sub.match(/(\d+)\s+unavailable/i);document.getElementById('usage-fp-unavailable').textContent=m?m[1]:'—';}
function drawHealth(){var host=document.getElementById('usage-health-evidence'),rows=Array.prototype.slice.call(document.querySelectorAll('#health-body tr')).filter(function(r){return r.querySelectorAll('td').length>=5;});document.getElementById('usage-health-count').textContent=rows.length+' persisted checks';if(!rows.length){host.innerHTML='<div class="empty"><b>No health samples loaded</b><span>No diagnostic chart is fabricated.</span></div>';return;}host.innerHTML='';rows.slice(0,8).forEach(function(r){var c=r.querySelectorAll('td'),state=stateText(c[2]);var sample=document.createElement('div');sample.className='usage-health-sample '+String(state).replaceAll(' ','_');var dot=document.createElement('i');var copy=document.createElement('div');var b=document.createElement('b');b.textContent=text(c[1].querySelector('.cell-title'))||text(c[1]);var span=document.createElement('span');span.textContent=state+' · '+text(c[0]);copy.append(b,span);var em=document.createElement('em');em.textContent=text(c[3])||'—';sample.append(dot,copy,em);host.appendChild(sample);});}
function refresh(){scheduled=false;drawActivity();drawFootprint();drawHealth();}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(refresh);}
['usage-actions','health-body','ov-routes','ov-providers','ov-models','ov-tools','ov-routes-sub'].forEach(function(id){var el=document.getElementById(id);if(el)new MutationObserver(schedule).observe(el,{childList:true,subtree:true,characterData:true});});schedule();
})();`;

export function applyUsageFidelity(html: string): string {
  const start = html.indexOf('<section id="page-usage"');
  const end = start >= 0 ? html.indexOf('<section id="page-logs"', start) : -1;
  if (start < 0 || end < 0) return html;
  let out = html.slice(0, start) + USAGE_FIDELITY_SECTION + '\n\n    ' + html.slice(end);
  out = out.replace('</head>', '<style>' + USAGE_FIDELITY_CSS + '</style></head>');
  out = out.replace('</body>', '<script>' + USAGE_FIDELITY_SCRIPT + '</script></body>');
  return out;
}
